Repository ibexa/documentation-developer, pull requests merged in 2018-06, with the labels that each got.

#296 EZP-29153: Enterprise beginner tutorial audit
  docs/guide/landing_page_rendering.md
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
  docs/tutorials/enterprise_beginner/2_prepare_the_landing_page.md
  docs/tutorials/enterprise_beginner/2_preparing_the_landing_page.md
  docs/tutorials/enterprise_beginner/3_use_existing_blocks.md
  docs/tutorials/enterprise_beginner/3_using_existing_blocks.md
  docs/tutorials/enterprise_beginner/4_create_a_custom_block.md
  docs/tutorials/enterprise_beginner/ez_enterprise_beginner_tutorial_-_its_a_dogs_world.md
  mkdocs.yml
Labels: Ready to merge, Special case (see comments)

#125 Add anonymous_user_id setting description.
  docs/guide/configuration.md
  docs/guide/http_cache.md
Labels: Ready to merge, Special case (see comments)

#285 Expand Null Field Type Example to cover all needs
  docs/api/field_type_reference.md
Labels: Ready to merge

#297 EZP-29209: Front-end Notification System
  docs/cookbook/sending_notifications.md
  docs/guide/configuration.md
Labels: Ready to merge

#299 Add missing COTF props
  docs/guide/extending_modules.md
Labels: Ready to merge

#300 several corrections in personalization
  docs/guide/personalization.md
Labels: Ready to merge

#295 EZP-29153: Platform beginner tutorial audit
  docs/tutorials/platform_beginner/1_get_ready.md
  docs/tutorials/platform_beginner/1_getting_ready.md
  docs/tutorials/platform_beginner/2_create_the_content_model.md
  docs/tutorials/platform_beginner/2_creating_your_content_model.md
  docs/tutorials/platform_beginner/3_customize_the_front_page.md
  docs/tutorials/platform_beginner/3_customizing_the_general_layout.md
  docs/tutorials/platform_beginner/4_display_a_list_of_content_items.md
  docs/tutorials/platform_beginner/4_displaying_content_of_a_ride.md
  docs/tutorials/platform_beginner/5_displaying_the_list_of_rides_on_the_homepage.md
  docs/tutorials/platform_beginner/5_improve_configuration.md
  docs/tutorials/platform_beginner/6_embed_content.md
  docs/tutorials/platform_beginner/6_enabling_account_registration.md
  docs/tutorials/platform_beginner/7_customize_login_and_register_forms.md
  docs/tutorials/platform_beginner/7_enable_account_registration.md
  docs/tutorials/platform_beginner/building_a_bicycle_route_tracker_in_ez_platform.md
  docs/tutorials/platform_beginner/img/assets.zip
  docs/tutorials/platform_beginner/img/bike_ride_adding_landmarks_to_the_ride_content_type.png
  docs/tutorials/platform_beginner/img/bike_ride_adding_pois_to_the_ride_content_type.png
  docs/tutorials/platform_beginner/img/bike_tutorial_all_rides_admin.png
  docs/tutorials/platform_beginner/img/bike_tutorial_create_content.png
  docs/tutorials/platform_beginner/img/bike_tutorial_create_folder.png
  docs/tutorials/platform_beginner/img/bike_tutorial_details_tab_for_locationid.png
  docs/tutorials/platform_beginner/img/bike_tutorial_hello_world.png
  docs/tutorials/platform_beginner/img/bike_tutorial_homepage_with_images.png
  docs/tutorials/platform_beginner/img/bike_tutorial_index_final.png
  docs/tutorials/platform_beginner/img/bike_tutorial_listing_web_dir.png
  docs/tutorials/platform_beginner/img/bike_tutorial_nav_hub.png
  docs/tutorials/platform_beginner/img/bike_tutorial_new_homepage.png
  docs/tutorials/platform_beginner/img/bike_tutorial_poi_relation.png
  docs/tutorials/platform_beginner/img/bike_tutorial_preview_full_ride.png
  docs/tutorials/platform_beginner/img/bike_tutorial_ride_list.png
  docs/tutorials/platform_beginner/img/bike_tutorial_ride_view.png
  docs/tutorials/platform_beginner/img/bike_tutorial_ride_with_landmarks.png
  docs/tutorials/platform_beginner/img/step6_admin_roles.png
  docs/tutorials/platform_beginner/img/step6_newuser_loggedin_restrictions.png
  docs/tutorials/platform_beginner/img/step6_policy.png
  docs/tutorials/platform_beginner/img/step6_register_page.png
  docs/tutorials/platform_beginner/img/step6_role_biker.png
  mkdocs.yml
Labels: Special case (see comments)

#301 EZEE-2028 eZ Form captcha image is corrupted behind Varnish
  docs/releases/updating_ez_platform.md
Labels: Ready to merge

#305 Fix default view template variable name
  docs/guide/content_rendering.md
Labels: Ready to merge

#304 Add correct Twig function name: ez_first_filled_image_field_identifier
  docs/guide/twig_functions_reference.md
Labels: Ready to merge

#308 Fixed configuration file path in CORS cookbook
  docs/cookbook/making_cross_origin_http_requests.md
Labels: Ready to merge

#309 EZP-29225 permissions for "Content/Urltranslator"
  docs/guide/permissions.md
Labels: Ready to merge

#310 Added information about overwriting default NelmioCorsBundle configuration
  docs/cookbook/making_cross_origin_http_requests.md
Labels: Ready to merge

#312 Added missing note about ez_notifications
  docs/migrating/migrating_from_ez_publish_platform.md
Labels: Ready to merge

#311 Add anchor to MySQL/MariaDB versions note
  docs/getting_started/requirements_and_system_configuration.md
Labels: Ready to merge

#289 EZP-28868: Standard design
  docs/guide/design_engine.md
Labels: Ready to merge

#306 DEMO-169: Add pagelayout setting
  docs/guide/templates.md
Labels: Ready to merge

#313 EZP-25487: Warning about clearing persistence cache when changing image variations
  docs/guide/images.md
Labels: Ready to merge

#314 Remove mentions of Schedule Block and Form Builder
  docs/getting_started/ez_enterprise.md
  docs/guide/extending_form_builder.md
  docs/guide/landing_page_rendering.md
  docs/tutorials/enterprise_beginner/ez_enterprise_beginner_tutorial_-_its_a_dogs_world.md
  mkdocs.yml
Labels: Ready to merge

#317 Installation link update
  docs/getting_started/install_ez_platform.md
Labels: Ready to merge

#318 EZEE-2081: Move NotificationBundle into Kernel
  docs/cookbook/sending_notifications.md
  docs/guide/repository.md
  docs/guide/signalslots.md
Labels: Ready to merge

#316 Bundles starter pack
  docs/getting_started/bundles_starter_pack.md
  docs/getting_started/get_started_with_ez_platform.md
  mkdocs.yml
Labels: Ready to merge

#319 Copy subtree and resize image commands
  docs/guide/configuration.md
  docs/guide/images.md
Labels: Ready to merge

#302 Various updates to 2.2
  docs/getting_started/install_manually.md
  docs/getting_started/install_using_composer.md
  docs/getting_started/troubleshooting.md
  docs/guide/permissions.md
Labels: Ready to merge

#298 [EZP-29121] Added UI Guidelines to documentation, basic structure
  docs/css/bootstrap-iso.css
  docs/css/custom.css
  docs/css/ez-guidelines-buttons.css
  docs/css/ez-guidelines-colors.css
  docs/css/ez-guidelines-icons.css
  docs/css/ez-guidelines-typography.css
  docs/css/ez-guidelines-utilities.css
  docs/css/ez-guidelines.css
  docs/fonts/ez-icons.ttf
  docs/fonts/ez-icons.woff
  docs/guidelines/Introduction.md
  docs/guidelines/components/buttons.md
  docs/guidelines/design_principles/Accessibility.md
  docs/guidelines/design_principles/Philosophy.md
  docs/guidelines/resources/colors.md
  docs/guidelines/resources/icons.md
  docs/guidelines/resources/typography.md
  docs/images/ez-icons.svg
  material/base.html
  material/partials/integrations/bootstrap.html
  mkdocs.yml
  requirements.txt
  tools/prepare_guidelines_css/README.md
  tools/prepare_guidelines_css/build.sh
  tools/prepare_guidelines_css/prefix_bootstrap.less
  tools/prepare_guidelines_css/prefix_ez.less
Labels: Ready to merge

#315 Page builder, part 1
  docs/api/field_type_reference.md
  docs/getting_started/ez_enterprise.md
  docs/guide/bundles.md
  docs/guide/content_rendering.md
  docs/guide/extending_page.md
  docs/guide/http_cache.md
  docs/guide/landing_page_rendering.md
  docs/guide/page_rendering.md
  docs/guide/siteaccess.md
  docs/migrating/migrating_from_ez_publish.md
  docs/migrating/migrating_from_ez_publish_platform.md
  mkdocs.yml
Labels: Ready to merge
