Repository ibexa/documentation-developer, pull requests merged in 2018-10, with the labels that each got.

#403 EZP-29443: Combined installation guide and getting started cleanup
  docs/cookbook/installing-on-mac-os-and-windows.md
  docs/getting_started/ez_enterprise.md
  docs/getting_started/ez_platform_features.md
  docs/getting_started/install_ez_enterprise.md
  docs/getting_started/install_ez_platform.md
  docs/getting_started/install_manually.md
  docs/getting_started/install_using_composer.md
  docs/getting_started/install_using_docker.md
  docs/getting_started/quickstart.md
  docs/getting_started/requirements.md
  docs/getting_started/set_up_directory_permissions.md
  docs/getting_started/starting_ez_platform.md
  docs/getting_started/troubleshooting.md
  docs/guide/clustering.md
  docs/migrating/migrating_from_ez_publish_platform.md
  docs/references.md
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
  docs/tutorials/field_type/1_create_the_bundle.md
  docs/tutorials/platform_beginner/1_get_ready.md
  mkdocs.yml
Labels: Ready to merge

#307 EZP-28890 Added Crowdin in-context translation
  docs/community_resources/img/crowdin_translation.png
  docs/community_resources/translations.md
Labels: Needs dev review

#410 Form Builder
  docs/api/field_type_reference.md
  docs/guide/extending_form_builder.md
  mkdocs.yml
Labels: Ready to merge

#412 Update to 2.3
  docs/releases/updating_ez_platform.md
Labels: Ready to merge

#409 2.3 release notes
  docs/releases/ez_platform_v2.3.md
  docs/releases/img/2.3_content_scheduler.png
  docs/releases/img/2.3_form_builder.png
  docs/releases/img/2.3_form_builder_submissions.png
  docs/releases/img/2.3_image_asset.png
  docs/releases/img/2.3_schedule_tab.png
  docs/releases/img/2.3_timeline_list.png
  docs/releases/img/2.3_udw_selection.png
  docs/releases/img/2.3_user_preferences.png
  mkdocs.yml
Labels: Ready to merge

#416 EZEE-2434: Location for form-uploaded files
  docs/guide/configuration.md
Labels: Ready to merge

#419 Fix Extending Form Builder classes
  docs/guide/extending_form_builder.md
Labels: Ready to merge

#421 Fixed a typo in a link's syntax
  docs/migrating/migrating_from_ez_publish_platform.md
Labels: Ready to merge

#422 Update setting_up_amazon_aws_s3_clustering.md
  docs/cookbook/setting_up_amazon_aws_s3_clustering.md
Labels: Ready to merge

#424 EZEE-2526: Missing index on ezpage_map_blocks_zones causes long query execution time
  docs/releases/updating_ez_platform.md
Labels: Ready to merge

#425 [Install] Fix several issues around composer usage
  docs/getting_started/install_ez_platform.md
Labels: Ready to merge

#423 [2.x] Remove composer --no-dev option as we need dev for 2.x install
  docs/getting_started/install_ez_platform.md
Labels: Ready to merge

#429 EZP-27292: Tweet tutorial - add links to tags in repo
  docs/tutorials/field_type/1_create_the_bundle.md
  docs/tutorials/field_type/2_implement_the_tweet_value_class.md
  docs/tutorials/field_type/3_implement_the_tweet_type_class.md
  docs/tutorials/field_type/4_register_the_field_type_as_a_service.md
  docs/tutorials/field_type/5_implement_the_legacy_storage_engine_converter.md
  docs/tutorials/field_type/6_introduce_a_template.md
  docs/tutorials/field_type/7_allow_adding_and_editing_the_field_in_back_office.md
  docs/tutorials/field_type/8_add_a_validation.md
Labels: Ready to merge

#430 Warning about block config not being SiteAccess-aware
  docs/guide/extending_page.md
Labels: Ready to merge

#431 EZP-29665 Better diagrams
  docs/api/img/create_content_sequence.png
  docs/api/img/diagrams_source/create_content_sequence.xml
  docs/api/img/diagrams_source/field_type_overview.xml
  docs/api/img/diagrams_source/publish_content_sequence.xml
  docs/api/img/field_type_overview.png
  docs/api/img/publish_content_sequence.png
  docs/guide/architecture.md
  docs/guide/img/config_content_structure.png
  docs/guide/img/content_model_diagram.png
  docs/guide/img/content_model_item_diagram.png
  docs/guide/img/content_model_type_diagram.png
  docs/guide/img/diagram_source/config_content_structure.xml
  docs/guide/img/diagram_source/content_model_diagram.xml
  docs/guide/img/diagram_source/content_model_item_diagram.xml
  docs/guide/img/diagram_source/content_model_type_diagram.xml
  docs/guide/img/diagram_source/ez5_architecture.xml
  docs/guide/img/diagram_source/full_content_export.xml
  docs/guide/img/diagram_source/incremental_content_export.xml
  docs/guide/img/diagram_source/node_visibility_hide.xml
  docs/guide/img/diagram_source/node_visibility_hide_invisible.xml
  docs/guide/img/diagram_source/node_visibility_unhide1.xml
  docs/guide/img/diagram_source/node_visibility_unhide2.xml
  docs/guide/img/diagram_source/organising_templates.xml
  docs/guide/img/diagram_source/server_setup.xml
  docs/guide/img/diagram_source/signal_slots_diagram.xml
  docs/guide/img/diagram_source/spi_cache.xml
  docs/guide/img/ez5_architecture.png
  docs/guide/img/full_content_export.png
  docs/guide/img/incremental_content_export.png
  docs/guide/img/node_visibility_hide.png
  docs/guide/img/node_visibility_hide_invisible.png
  docs/guide/img/node_visibility_unhide1.png
  docs/guide/img/node_visibility_unhide2.png
  docs/guide/img/organising_templates.png
  docs/guide/img/recommendation_fullcontentexport.png
  docs/guide/img/recommendation_incrementalcontentexport.png
  docs/guide/img/server_setup.png
  docs/guide/img/signal_slots_diagram.png
  docs/guide/img/spi_cache.png
  docs/guide/multisite.md
  docs/guide/personalization.md
  docs/images/color_source.xml
  docs/tutorials/enterprise_beginner/img/diagram_source/enterprise_tut_file_structure.xml
  docs/tutorials/enterprise_beginner/img/enterprise_tut_file_structure.png
  docs/tutorials/field_type/1_create_the_bundle.md
  docs/tutorials/field_type/img/diagram_source/list_of_contents.xml
  docs/tutorials/field_type/img/list_of_contents.png
  docs/tutorials/platform_beginner/3_customize_the_front_page.md
  docs/tutorials/platform_beginner/img/bike_tutorial_listing_web.png
  docs/tutorials/platform_beginner/img/bike_tutorial_listing_web_dir.png
  docs/tutorials/platform_beginner/img/diagram_source/bike_tutorial_listing_web.xml
Labels: Ready to merge

#420 EZP-28688: Update enterprise tutorial to 2.3
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
  docs/tutorials/enterprise_beginner/2_prepare_the_landing_page.md
  docs/tutorials/enterprise_beginner/3_use_existing_blocks.md
  docs/tutorials/enterprise_beginner/4_create_a_custom_block.md
  docs/tutorials/enterprise_beginner/ez_enterprise_beginner_tutorial_-_its_a_dogs_world.md
  docs/tutorials/enterprise_beginner/img/enterprise_tut_after_list_schedule_block.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_choosing_airtime.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_content_list_window.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_drag_block.gif
  docs/tutorials/enterprise_beginner/img/enterprise_tut_empty_single_block.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_main_screen.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_new_layout.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_overflow_warning.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_page_with_featured_articles.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_select_articles.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_select_layout.png
Labels: Ready to merge

#433 Fixed translation mapping in solr multi core example
  docs/guide/solr.md
Labels: Ready to merge

#426 Basics -> Supported Response Format
  docs/api/rest_api_guide.md
Labels: Ready for MERGE

#437 Rtd jQuery, version switcher, css syntax
  docs/css/custom.css
  docs/js/custom.js
Labels: Ready for MERGE

#436 Add missing Page block attributes
  docs/guide/extending_page.md
Labels: Ready for MERGE

#438 Add note about enabling Link manager in install guide
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#432 eZ Platform Cloud requirements
  docs/getting_started/requirements.md
Labels: Ready for MERGE
