Repository ibexa/documentation-developer, pull requests merged in 2018-03, with the labels that each got.

#201 Add info about TTL for Landing Page blocks
  docs/guide/http_cache.md
Labels: Ready to merge

#200 detailed info on BASIC Auth, Troubleshooting and diagrams for content exchange
  docs/guide/img/recommendation_fullcontentexport.png
  docs/guide/img/recommendation_incrementalcontentexport.png
  docs/guide/recommendation.md
Labels: Ready to merge

#204 REST API guide audit I
  docs/api/general_rest_usage.md
  docs/api/public_php_api.md
  docs/api/rest_api_guide.md
Labels: Ready to merge

#179 API'page title
  docs/api/api.md
  mkdocs.yml
Labels: Ready to merge

#205 Fix environment option
  docs/releases/updating_ez_platform.md
Labels: Ready to merge

#207 Clean up remaining v1 terminology
  docs/getting_started/ez_platform_features.md
  docs/getting_started/img/navigation_hub.png
  docs/getting_started/starting_ez_platform.md
  docs/getting_started/troubleshooting.md
  docs/guide/bundles.md
  docs/guide/permissions.md
Labels: Ready to merge

#210 EZP-28903: Note about clearing Redis cache
  docs/guide/repository.md
Labels: Ready to merge, Special case (see comments)

#187 Update "Custom controllers" part of the "Content Rendering" documentation
  docs/guide/content_rendering.md
Labels: Special case (see comments)

#213 EZP-28238: Object states
  docs/guide/img/assigning_an_object_state.png
  docs/guide/img/object_state_lock.png
  docs/guide/repository.md
Labels: Ready to merge

#215 Custom tags
  docs/guide/extending_ez_platform_ui.md
Labels: Ready to merge

#216 EZP-28792: Change password
  docs/guide/user_management.md
  mkdocs.yml
Labels: Ready to merge

#217 REST: search with FieldCriterion
  docs/guide/search.md
Labels: Ready to merge

#220 Content on the fly properties in UDW
  docs/guide/extending_ez_platform_ui.md
Labels: Ready to merge

#224 Added information about UpdateUserTokenSignal.
  docs/guide/repository.md
Labels: Ready to merge

#223 LandingPage ContentType modification caution
  docs/guide/field_type_reference.md
Labels: Ready to merge

#225 Fix typo in Performance documentation
  docs/guide/performance.md
Labels: Ready to merge

#227 Added information about parameter usage in solr configuration.
  docs/guide/search.md
Labels: Ready to merge

#222 Update some clarifications to system requirements
  docs/getting_started/requirements_and_system_configuration.md
Labels: Ready to merge

#209 REST API guide audit II
  docs/api/extending_the_rest_api.md
  docs/api/js_client.md
  docs/api/rest_api_reference.md
  mkdocs.yml
Labels: Ready to merge

#211 REST API guide audit III
  docs/api/general_rest_usage.md
  docs/api/rest_api_guide.md
Labels: Ready to merge

#221 Removes outstanding TODOs
  docs/community_resources/contributing.md
  docs/getting_started/troubleshooting.md
  docs/migrating/migrating_from_ez_publish_platform.md
Labels: Ready to merge

#214 v2.1.0 release notes
  docs/releases/ez_platform_v2.1.0.md
  docs/releases/img/cotf.png
  docs/releases/img/draft_conflict.png
  docs/releases/img/filtered_search.png
  docs/releases/img/forgot_password.png
  docs/releases/img/object_state_lock.png
  docs/releases/img/url_aliases.png
  mkdocs.yml
Labels: Ready to merge

#231 Fixes code snippets in "extending AdminUI menu" section
  docs/guide/extending_ez_platform_ui.md
Labels: Ready to merge

#234 EZP-28585: Added flag to URLService\UpdateUrlSignal indicating that URL address was changed
  docs/guide/repository.md
Labels: Ready to merge

#226 Public PHP API audit
  docs/api/public_php_api.md
Labels: Ready to merge

#239 Fix small typo (duplicate single quotes)
  docs/tutorials/platform_beginner/7_customize_login_and_register_forms.md
Labels: Ready to merge
