Repository ibexa/documentation-developer, pull requests merged in 2019-12, with the labels that each got.

#880 Version warning - fixed url
  docs/js/custom.js
Labels: Ready for MERGE

#845 EZP-30985: Remove deprecated features from eZ
  docs/guide/controllers.md
  docs/guide/extending/img/custom_tag_ezyt.png
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#882 Removal of deprecated Creating a Tweet Field Type tutorial in master
  docs/api/field_type_reference.md
  docs/getting_started/bundles_starter_pack.md
  docs/guide/bundles.md
  docs/guide/content_model.md
  docs/guide/extending/extending_ez_platform.md
  docs/migrating/migrating_from_ez_publish.md
  mkdocs.yml
Labels: Ready for MERGE

#862 EZP-30951: Added support for searching (Not)Empty Field values
  docs/guide/search.md
Labels: Ready for MERGE

#858 EZP-31100: Update namespaces in `ezplatform-page-fieldtype
  docs/api/field_type_form_and_template.md
  docs/releases/ez_platform_v3.0_deprecations.md
  docs/tutorials/field_type/7_allow_adding_and_editing_the_field_in_back_office.md
  docs/tutorials/field_type/8_add_a_validation.md
Labels: Ready for MERGE

#863 GraphQL – updates
  docs/api/graphql.md
  docs/api/graphql_operations.md
Labels: Ready for MERGE

#884 EZP-30905: Deprecated MatcherInterface removed
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#883 EZP-30517: Kernel RichText deprecated code dropped
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#885 EZP-30975: Star Rating Field Type removed
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Needs DOC review

#886 introduce alphabetical order in bc&depr section
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#887 EZP-30971: Deprecated Role Service methods removed
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#881 EZP-30973: Use SiteAccess-aware Repository by default
  docs/api/public_php_api_browsing.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#891 EZP-30837: Updated classes moved from repository-forms to ezplatform-admin-ui
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#892 EZP-30962: Deprecated permission-related methods removed
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#889 EZP-30806: Added example of REST search query with logical operators
  docs/api/general_rest_usage.md
Labels: Ready for MERGE

#894 EZP-30934: Remove usage of deprecated getCurrentUser method
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#897 Clarify repository-forms availability in v3
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#734 Generic Field Type - basic info and mini tutorial
  docs/guide/extending_field_type.md
  docs/guide/img/extending_field_type_create.png
  docs/guide/img/extending_field_type_definition.png
  docs/guide/img/extending_field_type_hello_world.png
  mkdocs.yml
Labels: Ready for MERGE

#733 Generic Field Type tutorial
  docs/tutorials/generic_field_type/1_implement_the_point2d_value_class.md
  docs/tutorials/generic_field_type/2_define_point2d_field_type.md
  docs/tutorials/generic_field_type/3_create_form_for_point2d.md
  docs/tutorials/generic_field_type/4_introduce_a_template.md
  docs/tutorials/generic_field_type/5_add_a_field.md
  docs/tutorials/generic_field_type/6_settings.md
  docs/tutorials/generic_field_type/7_add_a_validation.md
  docs/tutorials/generic_field_type/8_data_migration.md
  docs/tutorials/generic_field_type/creating_a_point2d_field_type.md
  docs/tutorials/generic_field_type/img/create_new_content_type.png
  docs/tutorials/generic_field_type/img/creating_new_point2d.png
  docs/tutorials/generic_field_type/img/field_definition_format_field.png
  docs/tutorials/generic_field_type/img/menu_point2d.png
  docs/tutorials/generic_field_type/img/new_field_definition.png
  docs/tutorials/generic_field_type/img/new_point2d.png
  docs/tutorials/generic_field_type/img/point2d_field_definition.png
  docs/tutorials/generic_field_type/img/point2d_validation.png
  mkdocs.yml
Labels: Ready for MERGE, Special case (see comments)

#898 EZP-30979: Content Version comparison of TextLine Fields
  docs/guide/bundles.md
  docs/guide/extending/custom_fieldtype_comparison.md
  mkdocs.yml
Labels: Ready for MERGE

#895 Proofread changes in General REST usage section
  docs/api/general_rest_usage.md
Labels: Ready for MERGE

#900 [2.5] Proofread changes in General REST usage section
  docs/api/general_rest_usage.md
Labels: Ready for MERGE

#899 Update v3 project update with latest changes
  docs/releases/ez_platform_v3.0_project_update.md
Labels: Ready for MERGE

#902 Fix config in First Steps
  docs/getting_started/first_steps.md
Labels: Ready for MERGE

#904 EZP-31208 Move Field Type information from Tweet tutorial to API guide
  docs/api/field_type_api.md
  docs/api/field_type_storage.md
  docs/api/field_type_type_and_value.md
  docs/tutorials/field_type/1_create_the_bundle.md
  docs/tutorials/field_type/2_implement_the_tweet_value_class.md
  docs/tutorials/field_type/3_implement_the_tweet_type_class.md
  docs/tutorials/field_type/4_register_the_field_type_as_a_service.md
  docs/tutorials/field_type/5_implement_the_legacy_storage_engine_converter.md
  docs/tutorials/field_type/6_introduce_a_template.md
  docs/tutorials/field_type/7_allow_adding_and_editing_the_field_in_back_office.md
  docs/tutorials/field_type/8_add_a_validation.md
  docs/tutorials/field_type/creating_a_tweet_field_type.md
  docs/tutorials/field_type/img/diagram_source/list_of_contents.xml
  docs/tutorials/field_type/img/fieldtype_tutorial_final_result.png
  docs/tutorials/field_type/img/fieldtype_tutorial_repo.png
  docs/tutorials/field_type/img/list_of_contents.png
Labels: Ready for MERGE

#888 EZEE-2855: Move flex workflow to Symfony workflow
  docs/guide/bundles.md
  docs/guide/img/workflow_notification.png
  docs/guide/img/workflow_panel.png
  docs/guide/img/workflow_reviewers.png
  docs/guide/sending_notifications.md
  docs/guide/workflow.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#905 Extending modules remodel
  docs/guide/config_back_office.md
  docs/guide/extending/extending_ez_platform.md
  docs/guide/extending/extending_modules.md
  docs/guide/extending/extending_multifile_upload.md
  docs/guide/extending/extending_subitems_list.md
  docs/guide/extending/extending_udw.md
  mkdocs.yml
Labels: Ready for MERGE

#901 [LegacyBridge] Clearify scope of support for Legacy bridge on eZ Platform 1.x and 2.x
  docs/getting_started/requirements.md
  docs/index.md
  docs/migrating/legacy_bridge.md
  mkdocs.yml
Labels: Ready for MERGE
