Repository ibexa/documentation-developer, pull requests merged in 2019-10, with the labels that each got.

#785 GraphQL schema generated automatically
  docs/api/graphql.md
Labels: Ready for MERGE

#766 Cookbook cleanup: Relocating 'Creating custom drop-downs' and 'Creating drag and drop interface'
  docs/guide/creating_custom_dropdowns.md
  docs/guide/drag_and_drop.md
  docs/guide/img/dropdown_expanded_state.jpg
  docs/guide/img/dropdown_multiple_selection.jpg
  mkdocs.yml
Labels: Ready for MERGE

#769 Cookbook cleanup: Relocating "Importing settings from a bundle"
  docs/cookbook/importing_settings_from_a_bundle.md
  docs/guide/bundles.md
  docs/guide/content_rendering.md
  docs/tutorials/field_type/6_introduce_a_template.md
  mkdocs.yml
Labels: Ready for MERGE

#787 Repairing links in mkdocs.yml
  mkdocs.yml
Labels: Ready for MERGE

#744 EZP-30624: Added SQL for dfs_schema in the Clustering guide
  docs/guide/clustering.md
Labels: Ready for MERGE, Special case (see comments)

#770 Cookbook cleanup: Relocating "Exposing SiteAccess-aware configuration for bundle"
  docs/cookbook/exposing_siteaccess_aware_configuration_for_your_bundle.md
  docs/guide/configuration.md
  docs/guide/multi_language_siteaccesses.md
  docs/guide/siteaccess.md
  docs/guide/siteaccess_matching.md
  mkdocs.yml
Labels: Ready for MERGE

#771 Cookbook cleanup: Relocating "Sending notifications" and "Customizing Form Builder email notifications
  docs/cookbook/customizing_form_builder_email_notifications.md
  docs/guide/extending_form_builder.md
  docs/guide/img/email_notification.png
  docs/guide/img/notification2.png
  docs/guide/img/notification3.png
  docs/guide/sending_notifications.md
  mkdocs.yml
Labels: Ready for MERGE

#786 EZP-30636: ezplatform extension
  docs/api/field_type_form_and_template.md
  docs/api/field_type_reference.md
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/getting_started/first_steps.md
  docs/guide/back_office_translations.md
  docs/guide/bundles.md
  docs/guide/clustering.md
  docs/guide/clustering_aws_s3.md
  docs/guide/config_back_office.md
  docs/guide/config_repository.md
  docs/guide/content_model.md
  docs/guide/content_rendering.md
  docs/guide/controllers.md
  docs/guide/custom_policies.md
  docs/guide/design_engine.md
  docs/guide/extending_ez_platform.md
  docs/guide/extending_modules.md
  docs/guide/extending_online_editor.md
  docs/guide/file_management.md
  docs/guide/http_cache.md
  docs/guide/images.md
  docs/guide/internationalization.md
  docs/guide/multisite.md
  docs/guide/persistence_cache.md
  docs/guide/search_engines.md
  docs/guide/security.md
  docs/guide/sessions.md
  docs/guide/siteaccess.md
  docs/guide/siteaccess_matching.md
  docs/guide/solr.md
  docs/guide/templates.md
  docs/guide/twig_functions_reference.md
  docs/guide/url_management.md
  docs/guide/user_generated_content.md
  docs/guide/user_management.md
  docs/guide/workflow.md
  docs/migrating/migrating_from_ez_publish_platform.md
  docs/releases/ez_platform_v3.0_deprecations.md
  docs/tutorials/extending_admin_ui/4_adding_a_custom_tag.md
  docs/tutorials/field_type/6_introduce_a_template.md
  docs/tutorials/platform_beginner/3_customize_the_front_page.md
  docs/tutorials/platform_beginner/6_improve_configuration.md
  docs/tutorials/platform_beginner/7_embed_content.md
  docs/tutorials/platform_beginner/8_enable_account_registration.md
  docs/updating/4_update_2.4.md
Labels: Ready for MERGE

#789 Cookbook cleanup [2.5]: SiteAccess-aware configuration & SiteAccess Matching
  docs/cookbook/exposing_siteaccess_aware_configuration_for_your_bundle.md
  docs/cookbook/setting_up_multi_language_siteaccesses.md
  docs/guide/configuration.md
  docs/guide/siteaccess.md
  docs/guide/siteaccess_matching.md
  mkdocs.yml
Labels: Ready for MERGE

#791 Cookbook cleanup [2.5]: Importing conf from a bundle
  docs/cookbook/importing_settings_from_a_bundle.md
  docs/guide/bundles.md
  docs/guide/content_rendering.md
  docs/tutorials/field_type/6_introduce_a_template.md
  mkdocs.yml
Labels: Ready for MERGE

#790 Cookbook cleanup [2.5]: Creating custom elements
  docs/guide/creating_custom_dropdowns.md
  docs/guide/drag_and_drop.md
  docs/guide/img/dropdown_expanded_state.jpg
  docs/guide/img/dropdown_multiple_selection.jpg
  mkdocs.yml
Labels: Ready for MERGE

#793 Cookbook cleanup [2.5]: Sections on notifications
  docs/cookbook/customizing_form_builder_email_notifications.md
  docs/guide/extending_form_builder.md
  docs/guide/img/email_notification.png
  docs/guide/img/notification.png
  docs/guide/img/notification2.png
  docs/guide/img/notification3.png
  docs/guide/sending_notifications.md
  mkdocs.yml
Labels: Ready for MERGE

#792 Cookbook cleanup [2.5]: Multi-language SiteAccess
  docs/community_resources/support_maintenance_faq.md
  docs/getting_started/first_steps.md
  docs/guide/internationalization.md
  docs/guide/multi_language_siteaccesses.md
  mkdocs.yml
Labels: Ready for MERGE

#795 Cookbook cleanup [1.13]: SiteAccess-aware configuration & SiteAccess Matching
  docs/cookbook/exposing_siteaccess_aware_configuration_for_your_bundle.md
  docs/cookbook/setting_up_multi_language_siteaccesses.md
  docs/guide/configuration.md
  docs/guide/siteaccess.md
  docs/guide/siteaccess_matching.md
  docs/tutorials/extending_platformui/2_set_up_the_configuration.md
  mkdocs.yml
Labels: Ready for MERGE

#797 Repairing broken links to siteaccess_matching.md#available-matchers
  docs/getting_started/first_steps.md
  docs/guide/devops.md
  docs/references.md
Labels: Ready for MERGE

#799 [1.13] Making the "Extending Form Builder" section separate
  docs/guide/extending_form_builder.md
  docs/guide/other_extensibility.md
  mkdocs.yml
Labels: Ready for MERGE

#796 Cookbook cleanup [1.13]: Multi-language SiteAccess
  docs/getting_started/first_steps.md
  docs/guide/internationalization.md
  docs/guide/multi_language_siteaccesses.md
  mkdocs.yml
Labels: Ready for MERGE

#788 EZP-30661: Improve the "Extending eZ Platform guide" section
  docs/api/field_type_reference.md
  docs/guide/architecture.md
  docs/guide/config_back_office.md
  docs/guide/extending/creating_custom_dropdowns.md
  docs/guide/extending/drag_and_drop.md
  docs/guide/extending/extending_back_office.md
  docs/guide/extending/extending_dashboard.md
  docs/guide/extending/extending_ez_platform.md
  docs/guide/extending/extending_form_builder.md
  docs/guide/extending/extending_menus.md
  docs/guide/extending/extending_modules.md
  docs/guide/extending/extending_online_editor.md
  docs/guide/extending/extending_page.md
  docs/guide/extending/extending_settings.md
  docs/guide/extending/extending_tabs.md
  docs/guide/extending/extending_workflow.md
  docs/guide/extending/img/dropdown_expanded_state.jpg
  docs/guide/extending/img/dropdown_multiple_selection.jpg
  docs/guide/extending/img/email_notification.png
  docs/guide/extending/img/tabs_system_info.png
  docs/guide/extending/richtext_block.md
  docs/guide/extending_ez_platform.md
  docs/guide/http_cache.md
  docs/guide/twig_functions_reference.md
  docs/references.md
  docs/releases/ez_platform_v2.4.md
  docs/releases/ez_platform_v2.5.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  docs/tutorials/extending_admin_ui/1_creating_a_dashboard_tab.md
  docs/updating/4_update_2.2.md
  mkdocs.yml
Labels: Ready for MERGE

#800 EZP-30661: Improve the Extending eZ Platform guide
  docs/api/field_type_reference.md
  docs/guide/architecture.md
  docs/guide/config_back_office.md
  docs/guide/extending/creating_custom_dropdowns.md
  docs/guide/extending/drag_and_drop.md
  docs/guide/extending/extending_back_office.md
  docs/guide/extending/extending_dashboard.md
  docs/guide/extending/extending_ez_platform.md
  docs/guide/extending/extending_form_builder.md
  docs/guide/extending/extending_menus.md
  docs/guide/extending/extending_modules.md
  docs/guide/extending/extending_online_editor.md
  docs/guide/extending/extending_page.md
  docs/guide/extending/extending_settings.md
  docs/guide/extending/extending_tabs.md
  docs/guide/extending/extending_workflow.md
  docs/guide/extending/img/dropdown_expanded_state.jpg
  docs/guide/extending/img/dropdown_multiple_selection.jpg
  docs/guide/extending/img/email_notification.png
  docs/guide/extending/img/tabs_system_info.png
  docs/guide/extending/richtext_block.md
  docs/guide/extending_ez_platform.md
  docs/guide/http_cache.md
  docs/guide/twig_functions_reference.md
  docs/references.md
  docs/releases/ez_platform_v2.4.md
  docs/releases/ez_platform_v2.5.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  docs/tutorials/extending_admin_ui/2_creating_a_dashboard_tab.md
  docs/updating/4_update_2.2.md
  mkdocs.yml
Labels: Ready for MERGE

#798 Cookbook cleanup [1.13]: Importing conf from a bundle
  docs/cookbook/importing_settings_from_a_bundle.md
  docs/guide/bundles.md
  docs/guide/content_rendering.md
  docs/tutorials/field_type/6_introduce_a_template.md
  mkdocs.yml
Labels: Ready for MERGE

#783 EZP-30911: Added option to pass `location-id` param to URL alias reg command
  docs/guide/url_management.md
Labels: Ready for MERGE, Special case (see comments)

#801 Cookbook cleanup [1.13]: Section on notifications
  docs/guide/custom_notifications_for_flex_workflow.md
  docs/guide/img/notification.png
  mkdocs.yml
Labels: Ready for MERGE

#806 unifying content and repairing links
  docs/guide/bundles.md
  docs/guide/multi_language_siteaccesses.md
  docs/guide/siteaccess.md
Labels: Ready for MERGE

#804 Cookbook cleanup [1.7]: Multi-language SiteAccess
  docs/getting_started/first_steps.md
  docs/guide/internationalization.md
  docs/guide/multi_language_siteaccesses.md
  docs/guide/siteaccess.md
  mkdocs.yml
Labels: Ready for MERGE

#779 EZP-30797: Password expiration, EZP-30983: Password reuse
  docs/guide/img/password_expiry.png
  docs/guide/user_management.md
Labels: Needs DEV review, Special case (see comments)

#794 EZP-30797: Password expiry db script
  docs/updating/4_update_2.5.md
Labels: Ready for MERGE

#807 2.5.6 release notes
  docs/releases/ez_platform_v2.5.md
Labels: Ready for MERGE

#802 Cookbook cleanup [1.7]: SiteAccess-aware configuration & SiteAccess M…
  docs/cookbook/exposing_siteaccess_aware_configuration_for_your_bundle.md
  docs/getting_started/first_steps.md
  docs/guide/configuration.md
  docs/guide/devops.md
  docs/guide/siteaccess.md
  docs/guide/siteaccess_matching.md
  docs/references.md
  docs/tutorials/extending_platformui/2_set_up_the_configuration.md
  mkdocs.yml
Labels: Ready for MERGE

#803 Cookbook cleanup [1.7]: Importing conf from a bundle
  docs/cookbook/importing_settings_from_a_bundle.md
  docs/guide/bundles.md
  docs/guide/content_rendering.md
  docs/tutorials/field_type/6_introduce_a_template.md
  mkdocs.yml
Labels: Ready for MERGE

#810 Cookbook cleanup [1.7]: Section on notifications
  docs/guide/custom_notifications_for_flex_workflow.md
  docs/guide/img/notification.png
  mkdocs.yml
Labels: Ready for MERGE

#808 Warning about OE configuration
  docs/guide/extending/extending_online_editor.md
Labels: Ready for MERGE

#809 Warning about database update
  docs/updating/4_update_database.md
Labels: Ready for MERGE

#805 EZP-30835: Solr 7.7
  docs/guide/solr.md
Labels: Ready for MERGE

#775 EZP-30726: Location and children support in GraphQ
  docs/api/graphql_queries.md
Labels: Ready for MERGE

#811 Cookbook cleanup: Relocating 'Display Content item children'
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/guide/displaying_children_of_a_content_item.md
  mkdocs.yml
Labels: Ready for MERGE

#814 Cookbook cleanup [2.5]: Relocating 'Display Content item children'
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/guide/displaying_children_of_a_content_item.md
  mkdocs.yml
Labels: Ready for MERGE

#816 Cookbook cleanup [1.7]: Relocating 'Display Content item children'
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/guide/displaying_children_of_a_content_item.md
  mkdocs.yml
Labels: Ready for MERGE

#817 Cookbook cleanup [1.13]: Relocating 'Display Content item children'
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/guide/displaying_children_of_a_content_item.md
  mkdocs.yml
Labels: Ready for MERGE

#812 Cookbook cleanup: Relocating 'Retrieving root Location'
  docs/guide/retrieving_root_location.md
  mkdocs.yml
Labels: Ready for MERGE

#818 Cookbook cleanup [2.5]: Relocating 'Retrieving root Location'
  docs/guide/retrieving_root_location.md
  mkdocs.yml
Labels: Ready for MERGE

#819 Cookbook cleanup [1.7]: Relocating 'Retrieving root Location'
  docs/guide/retrieving_root_location.md
  mkdocs.yml
Labels: Ready for MERGE

#820 Cookbook cleanup [1.13]: Relocating 'Retrieving root Location'
  docs/guide/retrieving_root_location.md
  mkdocs.yml
Labels: Ready for MERGE

#813 Cookbook cleanup: Relocating "Authenticating user with multiple user providers"
  docs/cookbook/authenticating_a_user_with_multiple_user_providers.md
  docs/guide/security.md
  docs/guide/user_management.md
  docs/index.md
  mkdocs.yml
Labels: Ready for MERGE

#821 Cookbook cleanup [2.5]: Relocating "Authenticating user with multiple user providers"
  docs/cookbook/authenticating_a_user_with_multiple_user_providers.md
  docs/guide/security.md
  docs/guide/user_management.md
  docs/index.md
  mkdocs.yml
Labels: Ready for MERGE

#822 Cookbook cleanup [1.7]: Relocating "Authenticating user with multiple user providers"
  docs/guide/security.md
  docs/guide/user_management.md
  docs/index.md
  mkdocs.yml
Labels: Ready for MERGE

#823 Cookbook cleanup [1.13]: Relocating "Authenticating user with multiple user providers"
  docs/guide/security.md
  docs/guide/user_management.md
  docs/index.md
  mkdocs.yml
Labels: Ready for MERGE

#826 [Launchpad] Clearify it's supported by community
  docs/getting_started/install_ez_platform.md
  docs/guide/performance.md
Labels: Ready for MERGE

#759 EZP-30898: Created v3.0 upgrade instruction for custom installers
  docs/releases/ez_platform_v3.0_deprecations.md
  docs/releases/ez_platform_v3.0_project_update.md
Labels: Ready for MERGE, Special case (see comments)

#763 Cookbook cleanup: Relocating 'Install on macOS or Windows'
  docs/community_resources/installing-on-mac-os-and-windows.md
  docs/getting_started/install_ez_platform.md
  mkdocs.yml
Labels: Ready for MERGE

#815 EZP-30843: Adding Tab groups using Components
  docs/guide/extending/extending_tabs.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#824 Cookbook cleanup: Relocating Rest API sections
  docs/api/creating_content_with_binary_attachments_via_rest_api.md
  docs/api/creating_custom_rest_api_response.md
  docs/api/making_cross_origin_http_requests.md
  mkdocs.yml
Labels: Ready for MERGE

#830 Cookbook cleanup [2.5]: Relocating Rest API sections
  docs/api/creating_content_with_binary_attachments_via_rest_api.md
  docs/api/creating_custom_rest_api_response.md
  docs/api/making_cross_origin_http_requests.md
  mkdocs.yml
Labels: Ready for MERGE

#831 Cookbook cleanup [1.7]: Relocating Rest API sections
  docs/api/converting_request_parameters_into_api_objects.md
  docs/api/creating_content_with_binary_attachments_via_rest_api.md
  docs/api/creating_custom_rest_api_response.md
  docs/api/making_cross_origin_http_requests.md
  docs/api/paginating_api_search_results.md
  mkdocs.yml
Labels: Ready for MERGE

#832 Cookbook cleanup [1.13]: Relocating Rest API sections
  docs/api/creating_content_with_binary_attachments_via_rest_api.md
  docs/api/creating_custom_rest_api_response.md
  docs/api/making_cross_origin_http_requests.md
  mkdocs.yml
Labels: Ready for MERGE

#825 Cookbook cleanup: Relocating RouteReference
  docs/guide/routereference.md
  mkdocs.yml
Labels: Ready for MERGE

#833 Cookbook cleanup [2.5]: 'Relocating RouteReference'
  docs/guide/routereference.md
  mkdocs.yml
Labels: Ready for MERGE

#834 Cookbook cleanup [1.7]: 'Relocating RouteReference'
  docs/guide/routereference.md
  mkdocs.yml
Labels: Ready for MERGE

#764 Cookbook cleanup: Relocating 'Display content using simple templates'
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/getting_started/first_steps.md
  docs/guide/templates.md
  mkdocs.yml
Labels: Ready for MERGE

#835 Cookbook cleanup: concluding jobs
  docs/api/creating_custom_rest_api_response.md
  docs/cookbook/img/notification.png
  docs/guide/templates.md
  docs/index.md
  mkdocs.yml
Labels: Ready for MERGE

#837 Cookbook cleanup [2.5]: Concluding jobs
  docs/api/creating_custom_rest_api_response.md
  docs/guide/signalslots.md
  docs/index.md
Labels: Ready for MERGE

#838 Cookbook cleanup [1.7]: Relocating 'Display content using simple templates
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/getting_started/first_steps.md
  docs/guide/templates.md
  mkdocs.yml
Labels: Ready for MERGE

#839 Cookbook cleanup [1.7]: Concluding jobs
  docs/api/creating_custom_rest_api_response.md
  docs/guide/signalslots.md
  docs/index.md
Labels: Ready for MERGE

#840 Cookbook cleanup [1.13]: Relocating 'Display content using simple templates
  docs/cookbook/displaying_content_with_simple_templates.md
  docs/getting_started/first_steps.md
  docs/guide/templates.md
  mkdocs.yml
Labels: Ready for MERGE

#841 Cookbook cleanup [1.13]: Concluding jobs
  docs/guide/bundles.md
  docs/guide/content_rendering.md
  docs/guide/custom_notifications_for_flex_workflow.md
  docs/guide/multi_language_siteaccesses.md
  docs/guide/signalslots.md
  docs/index.md
Labels: Ready for MERGE

#842 As of Solr 1.5.8, the FullText criterion accepts additional parameters
  docs/guide/search.md
Labels: Ready for MERGE

#843 repairing link to configresolver
  docs/guide/retrieving_root_location.md
Labels: Ready for MERGE

#844 Extending password settings section
  docs/guide/user_management.md
Labels: Ready for MERGE

#847 cleaning up the deprecations and BCs section
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#848 Added eZ user checker to security config
  docs/guide/security.md
  docs/releases/ez_platform_v3.0_project_update.md
Labels: Ready for MERGE

#851 RichText limitation removed
  docs/migrating/migrating_from_ez_publish_platform.md
Labels: Ready for MERGE

#846 Update twig_functions_reference.md to include information on "original" image variation
  docs/guide/twig_functions_reference.md
Labels: Ready for MERGE
