Repository ibexa/documentation-developer, pull requests merged in 2019-11, with the labels that each got.

#854 How to generate direct download link
  docs/guide/file_management.md
Labels: Ready for MERGE

#853 Symfony version update
  docs/migrating/migrating_from_ez_publish_platform.md
Labels: Ready for MERGE

#855 Workaround for missing SVG files support
  docs/guide/images.md
Labels: Ready for MERGE

#856 Suggest the design engine for default templates
  docs/guide/content_rendering.md
Labels: Ready for MERGE

#850 EZP-30985 via admi-ui:#1109: credentials_expired.html.twig template relocated
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#849 Text style update
  docs/guidelines/Introduction.md
  docs/guidelines/design_principles/Accessibility.md
  docs/guidelines/design_principles/Philosophy.md
  mkdocs.yml
Labels: Ready for MERGE

#860 Adding missing info on importing new conf file with custom tags
  docs/guide/extending/extending_online_editor.md
Labels: Ready for MERGE

#852 EZP-30567, EZP-30689: Querytype fix and pagination
  docs/guide/controllers.md
  docs/guide/displaying_children_of_a_content_item.md
Labels: Ready for MERGE

#864 EZP-30621: Dropped deprecated LegacyStorage Gateways
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#865 Add information about reporting issues in Enterprise
  docs/community_resources/report_follow_issues.md
Labels: Ready for MERGE

#867 Fix structure of services.yml
  docs/guide/sending_notifications.md
Labels: Ready for MERGE

#861 EZP-30933: Custom Tag with "link" attribute type
  docs/guide/extending/extending_online_editor.md
Labels: Ready for MERGE

#868 Added link to custom tag documentation in tutorial
  docs/tutorials/extending_admin_ui/6_adding_a_custom_tag.md
Labels: Ready for MERGE

#866 Cache adapter recommendations
  docs/guide/persistence_cache.md
Labels: Ready for MERGE

#870 Adding screenshots presenting custom tags
  docs/guide/extending/extending_online_editor.md
  docs/guide/extending/img/custom_tag_ezyt.png
  docs/guide/extending/img/custom_tag_factbox.png
  docs/guide/extending/img/custom_tag_link.png
Labels: Needs DOC review

#871 Links to Symfony doc updated
  docs/api/creating_custom_rest_api_response.md
  docs/api/extending_the_rest_api.md
  docs/api/field_type_form_and_template.md
  docs/api/field_type_type_and_value.md
  docs/api/public_php_api_browsing.md
  docs/api/public_php_api_managing_repository.md
  docs/api/public_php_api_search.md
  docs/community_resources/installing-on-mac-os-and-windows.md
  docs/getting_started/bundles_starter_pack.md
  docs/getting_started/install_ez_platform.md
  docs/getting_started/requirements.md
  docs/guide/bundles.md
  docs/guide/configuration.md
  docs/guide/content_rendering.md
  docs/guide/controllers.md
  docs/guide/devops.md
  docs/guide/environments.md
  docs/guide/extending/extending_ez_platform.md
  docs/guide/extending/extending_modules.md
  docs/guide/extending/extending_page.md
  docs/guide/http_cache.md
  docs/guide/performance.md
  docs/guide/persistence_cache.md
  docs/guide/routereference.md
  docs/guide/search.md
  docs/guide/security.md
  docs/guide/service_container.md
  docs/guide/sessions.md
  docs/guide/siteaccess.md
  docs/guide/templates.md
  docs/guide/twig_functions_reference.md
  docs/guide/workflow.md
  docs/releases/earlier_releases.md
  docs/releases/ez_platform_v2.5.md
  docs/tutorials/field_type/1_create_the_bundle.md
  docs/tutorials/field_type/4_register_the_field_type_as_a_service.md
  docs/updating/3_update_app.md
Labels: Ready for MERGE

#670 Fix config in user management
  docs/guide/user_management.md
Labels: QA approved, Ready for MERGE

#857 enableSingleRuntimeChunk() caution to avoid having multiple JS calls
  docs/guide/bundles.md
Labels: Ready for MERGE

#872 EZP-30837: Content forms package
  docs/api/field_type_form_and_template.md
  docs/guide/bundles.md
  docs/guide/custom_policies.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#876 Add ext-dom to requirements
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#877 Add allowedContentTypes UWD prop
  docs/guide/extending/extending_modules.md
Labels: Ready for MERGE

#875 Expand Default content availability flag description
  docs/guide/content_management.md
  docs/guide/content_model.md
  docs/guide/img/availability_flag.png
Labels: Ready for MERGE

#874 Updating links to match code and documentation version - v1.7
  docs/api/converting_request_parameters_into_api_objects.md
  docs/api/extending_the_rest_api.md
  docs/api/field_type_api.md
  docs/api/field_type_reference.md
  docs/api/field_type_search.md
  docs/api/field_type_storage.md
  docs/api/field_type_type_and_value.md
  docs/api/general_rest_usage.md
  docs/api/js_client.md
  docs/api/making_cross_origin_http_requests.md
  docs/api/paginating_api_search_results.md
  docs/api/public_php_api.md
  docs/api/public_php_api_browsing.md
  docs/api/public_php_api_locations.md
  docs/api/public_php_api_managing_content.md
  docs/api/public_php_api_search.md
  docs/api/rest_api_guide.md
  docs/api/rest_api_reference.md
  docs/community_resources/development_guidelines.md
  docs/community_resources/installing-on-mac-os-and-windows.md
  docs/community_resources/translations.md
  docs/getting_started/bundles_starter_pack.md
  docs/getting_started/install_ez_platform.md
  docs/guide/bundles.md
  docs/guide/config_dynamic.md
  docs/guide/content_model.md
  docs/guide/content_rendering.md
  docs/guide/controllers.md
  docs/guide/environments.md
  docs/guide/extending_form_builder.md
  docs/guide/images.md
  docs/guide/internationalization.md
  docs/guide/limitations.md
  docs/guide/performance.md
  docs/guide/persistence_cache.md
  docs/guide/personalization.md
  docs/guide/search.md
  docs/guide/security.md
  docs/guide/templates.md
  docs/guide/twig_functions_reference.md
  docs/references.md
  docs/releases/earlier_releases.md
  docs/releases/ez_platform_v1.10.0.md
  docs/releases/ez_platform_v2.2.0.md
  docs/releases/ez_platform_v2.3.md
  docs/releases/ez_platform_v2.4.md
  docs/releases/ez_platform_v2.5.md
  docs/tutorials/extending_platformui/1_create_the_extension_bundle.md
  docs/tutorials/extending_platformui/3_alter_the_javascript_application_routing.md
  docs/tutorials/extending_platformui/5_configure_the_navigation.md
  docs/tutorials/extending_platformui/6_build_the_content_list.md
  docs/tutorials/extending_platformui/7_paginate_results.md
  docs/tutorials/extending_platformui/conclusion.md
  docs/tutorials/field_type/6_introduce_a_template.md
  docs/updating/4_update_2.2.md
  docs/updating/4_update_2.5.md
  docs/updating/4_update_database.md
Labels: Ready for MERGE
