Repository ibexa/documentation-developer, pull requests merged in 2019-09, with the labels that each got.

#728 Clarify cleantrash Policy usage
  docs/guide/permissions.md
Labels: Ready for MERGE, Special case (see comments)

#742 New cleanupVersions command parameter
  docs/guide/config_repository.md
Labels: Ready for MERGE, Special case (see comments)

#752 EZP-30792: Remove deprecated functions, props etc. in JS
  docs/guide/extending_modules.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#753 Adding info about deprecation of `onlyContentOnTheFly`
  docs/guide/extending_modules.md
Labels: Ready for MERGE

#754 Add caution about $_POST PHP ini limit while editing large CTs
  docs/guide/content_model.md
Labels: Ready for MERGE

#758 EZP-30912: Added a note about deprecated Clean and DbBased Installers
  docs/releases/ez_platform_v2.5.md
Labels: Ready for MERGE

#760 Siteaccess > SiteAccess in TOC
  mkdocs.yml
Labels: Ready for MERGE

#761 JavaScript client removal
  docs/api/js_client.md
  docs/api/rest_api_guide.md
  mkdocs.yml
Labels: Ready for MERGE

#772 Link update according to Git Bash warnings
  docs/api/public_php_api_managing_repository.md
  docs/guide/content_management.md
  docs/migrating/migrating_from_ez_publish.md
  docs/releases/earlier_releases.md
  docs/releases/ez_platform_v1.10.0.md
  docs/releases/ez_platform_v1.11.0.md
  docs/releases/ez_platform_v1.13.0_lts.md
  docs/releases/ez_platform_v1.4.0_release_notes.md
  docs/releases/ez_platform_v1.9.0.md
  docs/releases/ez_platform_v2.5.md
  docs/releases/ez_studio_16.02_release_notes.md
  docs/releases/ez_studio_2016.04_release_notes.md
  docs/tutorials/platform_beginner/3_customize_the_front_page.md
Labels: Ready for MERGE

#729 2.5.4 release notes
  docs/releases/ez_platform_v2.5.md
Labels: Ready for MERGE

#767 Deprecations update
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Needs DOC review

#776 Display a list of content items fix pagination in v3 Platform beginner tutorial
  docs/tutorials/platform_beginner/5_display_a_list_of_content_items.md
Labels: Ready for MERGE

#773 Display a list of content items fix pagination
  docs/tutorials/platform_beginner/4_display_a_list_of_content_items.md
Labels: Ready for MERGE

#778 EZP-30911: Added option to pass `location-id` param to URL alias reg command
  docs/guide/url_management.md
Labels: Ready for MERGE

#777 EZP-30906: Removed deprecated templating component integration
  docs/guide/content_rendering.md
  docs/guide/extending_online_editor.md
  docs/guide/security.md
  docs/guide/twig_functions_reference.md
  docs/guide/user_management.md
  docs/releases/ez_platform_v3.0_deprecations.md
  docs/releases/ez_platform_v3.0_project_update.md
  docs/tutorials/field_type/6_introduce_a_template.md
Labels: Ready for MERGE

#774 Improve Redis configuration section
  docs/guide/persistence_cache.md
Labels: Ready for MERGE

#781 EZP-30948: Remove Setup and Design folders
  docs/guide/config_repository.md
  docs/guide/content_management.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#784 EZP-30623: Dropped obsolete tables from the database schema
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE, Special case (see comments)
