Repository ibexa/documentation-developer, pull requests merged in 2019-08, with the labels that each got.

#715 EZP-30753: loadSection improvement
  docs/releases/ez_platform_v2.5.md
Labels: Ready for MERGE

#714 EZP-30773: PHP API: Search
  docs/api/public_php_api_search.md
  docs/cookbook/paginating_api_search_results.md
  docs/guide/search.md
  mkdocs.yml
Labels: Ready for MERGE

#716 Remove pagination limit
  docs/guide/config_back_office.md
Labels: Ready for MERGE

#717 EZEE-2866 Loss in performance due to missing indexes in Page Builder (Update docs)
  docs/updating/4_update_2.5.md
Labels: Ready for MERGE

#720 File path update
  docs/guide/extending_online_editor.md
Labels: Ready for MERGE

#627 Update signals_reference.md
  docs/guide/signals_reference.md
Labels: Ready for MERGE

#719 Adding step5 to tests (Sf3)
  docs/tutorials/enterprise_beginner/4_create_a_custom_block.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  tests/README.md
  tests/features/EnterpriseTutorial.feature
  tests/source_files/step2/landingpagetemplate.html.twig
  tests/source_files/step2/layoutdefinition.yml
  tests/source_files/step2/sidebartemplate.html.twig
  tests/source_files/step3/article.html.twig
  tests/source_files/step3/contentlisttemplate.html.twig
  tests/source_files/step3/contentscheduler.css
  tests/source_files/step3/landingpage.css
  tests/source_files/step3/scheduleblock.html.twig
  tests/source_files/step4/RandomBlockListener.php
  tests/source_files/step4/random.html.twig
  tests/source_files/step4/randomblock.css
  tests/source_files/step5/form_field_theme.html.twig
  tests/source_files/step5/form_newsletter_view.html.twig
  tests/source_files/step5/form_style.css
  tests/src/Context/ConfigurationContext.php
Labels: Ready for MERGE

#718 Adding step5 to tests
  docs/tutorials/enterprise_beginner/4_create_a_custom_block.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  tests/features/EnterpriseTutorial.feature
  tests/source_files/step2/landingpagetemplate.html.twig
  tests/source_files/step2/layoutdefinition.yaml
  tests/source_files/step2/sidebartemplate.html.twig
  tests/source_files/step3/article.html.twig
  tests/source_files/step3/contentlisttemplate.html.twig
  tests/source_files/step3/contentscheduler.css
  tests/source_files/step3/landingpage.css
  tests/source_files/step3/scheduleblock.html.twig
  tests/source_files/step4/RandomBlockListener.php
  tests/source_files/step4/random.html.twig
  tests/source_files/step4/randomblock.css
  tests/source_files/step5/form_field_theme.html.twig
  tests/source_files/step5/form_newsletter_view.html.twig
  tests/source_files/step5/form_style.css
  tests/src/Context/ConfigurationContext.php
Labels: Ready for MERGE

#721 Remove signals_reference.md
  docs/guide/signals_reference.md
Labels: Ready for MERGE

#722 Procedure for installing tutorial script updated
  tests/README.md
Labels: Ready for MERGE

#723 copy changes from #722 to 2.5
  tests/README.md
Labels: Ready for MERGE

#725 EZP-30815 Dropped SPI\FieldType Events
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#724 EZP-30547 Config resolver for SiteAccess
  docs/cookbook/setting_up_multi_language_siteaccesses.md
  docs/guide/siteaccess.md
Labels: Ready for MERGE

#727 EZP-30775: PHP API: Managing
  docs/api/public_php_api_creating_content.md
  docs/api/public_php_api_locations.md
  docs/api/public_php_api_managing_content.md
  docs/api/public_php_api_managing_repository.md
  docs/cookbook/converting_request_parameters_into_api_objects.md
  mkdocs.yml
Labels: Ready for MERGE

#730 EZP-30795 Rename eZ Services to eZ Personalization in doc
  README.md
  docs/guide/bundles.md
  docs/guide/personalization.md
  docs/index.md
  docs/references.md
  mkdocs.yml
Labels: Ready for MERGE

#726 doc website changes: center fig captions & add h1 to navbar
  docs/css/custom.css
  docs/js/custom.js
  material/partials/toc.html
Labels: Ready for MERGE

#732 EZP-30774: PHP API: Creating content
  docs/api/public_php_api_creating_content.md
Labels: Ready for MERGE

#737 EZP-30809 All ezsettings provided by AdminUI should be set for admin_group siteaccess
  docs/guide/extending_ez_platform.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Needs DEV review

#738 EZP-30814 Remove Twig deprecations
  docs/guide/extending_online_editor.md
  docs/guide/twig_functions_reference.md
  docs/tutorials/enterprise_beginner/3_use_existing_blocks.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  docs/tutorials/field_type/6_introduce_a_template.md
  tests/source_files/step3/scheduleblock.html.twig
  tests/source_files/step5/form_field_theme.html.twig
Labels: Ready for MERGE

#735 Deprecated code in EzSystems\EzPlatformAdminUi\UserSetting
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#740 info on removed choiceLoaders added
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#739 fixing broken link to `SlugConverter.php`
  docs/guide/url_management.md
Labels: Ready for MERGE

#736 Colors introduced to Workflow transitions
  docs/guide/workflow.md
Labels: Ready for MERGE

#745 EZP-30544: Migrate Http Cache Bundle to FOS Cache Bundle v2
  docs/guide/http_cache.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#741 CS-7683 EZ on debian and Sorl 6 Java downgrade
  docs/getting_started/requirements.md
  docs/guide/solr.md
Labels: Ready for MERGE

#747 Replace Youtube as custom tag example
  docs/guide/extending_online_editor.md
  docs/tutorials/extending_admin_ui/4_adding_a_custom_tag.md
  docs/tutorials/extending_admin_ui/extending_admin_ui.md
  docs/tutorials/extending_admin_ui/img/custom_tag.png
Labels: Ready for MERGE

#731 EZP-30880: As a Developer I want MatcherFactory to avoid...
  docs/guide/content_rendering.md
  docs/guide/siteaccess.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE, Special case (see comments)

#652 Replace SignalSlots with Symfony Events
  docs/guide/http_cache.md
  docs/guide/img/diagram_source/spi_cache.xml
  docs/guide/img/signal_slots_diagram.png
  docs/guide/img/spi_cache.png
  docs/guide/persistence_cache.md
  docs/guide/signals_reference.md
  docs/guide/signalslots.md
  docs/references.md
  mkdocs.yml
Labels: Ready for MERGE

#750 EZP-30393: Move Online Editor front-end code
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#749 Note about outdated package used in one of the recommended 3rd party bundles
  docs/cookbook/authenticating_a_user_with_multiple_user_providers.md
Labels: Ready for MERGE
