Repository ibexa/documentation-developer, pull requests merged in 2020-12, with the labels that each got.

#1233 EZP-32168: New front page
  docs/css/custom.css
  docs/css/front-page.css
  docs/images/ez-icons.svg
  docs/images/page.svg
  docs/index.md
Labels: Ready for MERGE

#1240 Update internationalization.md
  docs/guide/internationalization.md
Labels: Ready for MERGE

#1242 Filename fix in reco client article
  docs/guide/personalization/recommendation_client.md
Labels: Needs DEV review, Needs DOC review

#1245 EZP-32151: Added Pagerfanta adapters for Repository Filtering
  docs/api/public_php_api_search.md
Labels: Ready for MERGE

#1239 Updated note about changing app secret
  docs/getting_started/install_ez_platform.md
Labels: Needs DOC review

#1247 Dropped obsolete installers
  docs/guide/shop_configuration/shop_configuration.md
Labels: Ready for MERGE

#1246 EZP-32062: Remove language switcher doc section
  docs/guide/internationalization.md
  docs/guide/routereference.md
Labels: Ready for MERGE

#1248 Remove remaining mentions of assetic
  docs/guide/multi_language_siteaccesses.md
  docs/updating/6_dump_assets.md
  docs/upgrading/7_dump_assets.md
Labels: Ready for MERGE

#1250 Fix the custom tags template line in the yaml configuration
  docs/tutorials/extending_admin_ui/4_adding_a_custom_tag.md
Labels: Ready for MERGE

#1251 Flatten navigation structure
  mkdocs.yml
Labels: Ready for MERGE

#1255 EZP-32163 - diagrams update
  docs/api/field_type_api.md
  docs/api/img/create_content_sequence.png
  docs/api/img/diagrams_source/load_content_sequence.xml
  docs/api/img/diagrams_source/update_content_sequence.xml
  docs/api/img/load_content_sequence.png
  docs/api/img/publish_content_sequence.png
  docs/api/img/update_content_sequence.png
Labels: Needs DOC review

#1243 EC-220: User management revision
  docs/api/commerce_api/field_type_reference/sesprofiledata.md
  docs/guide/checkout/order_confirmation.md
  docs/guide/customers/customer_api/configuration_for_customer_data.md
  docs/guide/customers/customer_api/customer_api.md
  docs/guide/customers/customer_api/customer_profile_data.md
  docs/guide/customers/customer_templates.md
  docs/guide/customers/customers.md
  docs/guide/customers/customers_api/configuration_for_customer_data.md
  docs/guide/customers/customers_api/customer_fields_in_the_cms.md
  docs/guide/customers/customers_api/customer_profile_data_components/customer_profile_data_components.md
  docs/guide/customers/customers_api/customer_profile_data_components/customer_profile_data_events.md
  docs/guide/customers/customers_api/customer_profile_data_components/customer_profile_data_listeners.md
  docs/guide/customers/customers_api/customer_profile_data_components/customer_profile_data_model.md
  docs/guide/customers/customers_api/customer_profile_data_components/customer_profile_data_services.md
  docs/guide/customers/customers_api/customer_profile_data_controller.md
  docs/guide/customers/customers_faq.md
  docs/guide/customers/customers_templating.md
  docs/guide/customers/managing_delivery_addresses.md
  docs/guide/customers/vat_handling.md
  docs/guide/forms/form_api/dataprocessors.md
  docs/guide/forms/form_api/predataprocessors.md
  docs/guide/img/customer_3.png
  docs/guide/img/customer_4.png
  docs/guide/img/customer_templating.png
  docs/guide/img/customers_faq.png
  docs/guide/img/customers_vat_setting_2.png
  docs/guide/img/delegate.png
  docs/guide/img/delegate_access_from_menu.png
  docs/guide/img/delegate_successful.png
  docs/guide/img/login_1.png
  docs/guide/img/login_2.png
  docs/guide/img/undelegate.png
  docs/guide/job_system.md
  docs/guide/logging/tokencontroller_logging.md
  docs/guide/login_and_registration/forgot_change_password.md
  docs/guide/login_and_registration/login_and_registration.md
  docs/guide/login_and_registration/login_and_registration_configuration.md
  docs/guide/login_and_registration/login_and_registration_cookbook.md
  docs/guide/login_and_registration/login_and_registration_faq.md
  docs/guide/login_and_registration/login_and_registration_templates.md
  docs/guide/newsletter/additional_newsletter_data.md
  docs/guide/newsletter/newsletter.md
  docs/guide/newsletter/newsletter_configuration.md
  docs/guide/newsletter/newsletter_interface.md
  docs/guide/newsletter/newsletter_templates.md
  docs/guide/order_history/orderhistory_templates.md
  docs/guide/permissions.md
  docs/guide/shop_features/user_management.md
  docs/guide/user_management/access_control.md
  docs/guide/user_management/delegate_function.md
  docs/guide/user_management/login_and_registration.md
  docs/guide/user_management/token.md
  docs/guide/user_management/token/token.md
  docs/guide/user_management/token/tokencontroller.md
  docs/guide/user_management/tracking.md
  mkdocs.yml
Labels: Ready for MERGE

#1254 Clean up Reference page
  docs/references.md
Labels: Ready for MERGE

#1257 S menu be gone
  docs/extending/img/extending_form_builder_country_field.png
  docs/extending/img/extending_richtext_block.png
  docs/guide/img/object_state_lock.png
  docs/releases/img/2.3_content_scheduler.png
Labels: Needs DOC review

#1252 EZEE-3219: Checkout and Basket components
  docs/guide/basket/basket_api/basket_routing.md
  docs/guide/basket/basket_templates.md
  docs/guide/checkout/checkout_api/checkout_controllers.md
  docs/guide/checkout/checkout_api/forms/checkout_delivery_address_form.md
  docs/guide/checkout/checkout_api/forms/checkout_invoice_address_form.md
  docs/guide/checkout/checkout_api/forms/checkout_shipping_payment_form.md
  docs/guide/checkout/checkout_api/forms/checkout_summary_form.md
  docs/guide/checkout/checkout_api/forms/configuration_for_checkout_forms.md
  docs/guide/checkout/checkout_api/forms/order_summary.md
  docs/guide/checkout/checkout_templates.md
  docs/guide/checkout/local_orders.md
  docs/guide/checkout/order_confirmation.md
  docs/guide/img/checkout_1.png
  docs/guide/img/checkout_6.png
  docs/guide/img/checkout_events_2.png
Labels: Ready for MERGE

#1244 EZP-32163 - diagrams update
  docs/api/field_type_api.md
  docs/api/img/create_content_sequence.png
  docs/api/img/diagrams_source/create_content_sequence.xml
  docs/api/img/diagrams_source/load_content_sequence.xml
  docs/api/img/diagrams_source/publish_content_sequence.xml
  docs/api/img/diagrams_source/update_content_sequence.xml
  docs/api/img/load_content_sequence.png
  docs/api/img/publish_content_sequence.png
  docs/api/img/update_content_sequence.png
Labels: Needs DOC review

#1253 ContentTranslatedName and CustomField Sort Clauses
  docs/guide/search/aggregation_reference/rawrange_aggregation.md
  docs/guide/search/aggregation_reference/rawstats_aggregation.md
  docs/guide/search/aggregation_reference/rawterm_aggregation.md
  docs/guide/search/sort_clause_reference.md
  docs/guide/search/sort_clause_reference/contenttranslatedname_sort_clause.md
  docs/guide/search/sort_clause_reference/customfield_sort_clause.md
  mkdocs.yml
Labels: Ready for MERGE

#1256 Missing Twig functions
  docs/guide/twig_functions_reference.md
Labels: Ready for MERGE

#1259 EZP-32182: Note about enhanced Location handling in GraphQL
  docs/api/graphql.md
  docs/api/graphql_queries.md
Labels: Ready for MERGE

#1261 Fix - Add objectElement to the ValueObjectVisitor example
  docs/api/extending_the_rest_api.md
Labels: Ready for MERGE

#1249 EZP-32199 - SF documentation changes
  docs/guide/site_factory.md
  docs/guide/siteaccess.md
Labels: Needs DEV review

#1267 Update FieldValueUrl class
  docs/extending/extending_thumbnails.md
Labels: Ready for MERGE

#1260 EZEE-3219: Basket and Product components
  docs/api/commerce_api/business_api/baseoperation/addproducts.md
  docs/api/commerce_api/business_api/baseoperation/getbasket.md
  docs/api/commerce_api/business_api/businessapi_invocation_service.md
  docs/guide/catalog/catalog_templates.md
  docs/guide/catalog/product_variants/product_variants.md
Labels: Ready for MERGE

#1264 Remove old release notes
  docs/releases/earlier_releases.md
  docs/releases/ez_enterprise_v1.4_release_notes.md
  docs/releases/ez_enterprise_v1.5.0_release_notes.md
  docs/releases/ez_platform_1.4.2_release_notes.md
  docs/releases/ez_platform_1.5.1_release_notes.md
  docs/releases/ez_platform_15.12.1_release_notes.md
  docs/releases/ez_platform_15.12_release_notes.md
  docs/releases/ez_platform_16.02_release_notes.md
  docs/releases/ez_platform_2016.04_release_notes.md
  docs/releases/ez_platform_and_ez_enterprise_v1.6.0.md
  docs/releases/ez_platform_v1.4.0_release_notes.md
  docs/releases/ez_platform_v1.5.0_release_notes.md
  docs/releases/ez_studio_15.12.1_release_notes.md
  docs/releases/ez_studio_15.12_release_notes.md
  docs/releases/ez_studio_16.02_release_notes.md
  docs/releases/ez_studio_2016.04_release_notes.md
  mkdocs.yml
Labels: Ready for MERGE

#1265 EZEE-3337 - Image Editor configuration
  docs/guide/image_editor.md
  mkdocs.yml
Labels: Needs DEV review, Needs DOC review

#1268 Update release process
  docs/community_resources/contributing.md
  docs/community_resources/release_process.md
Labels: Ready for MERGE

#1269 Legacy search engine with commerce
  docs/guide/search/search_engines.md
  docs/guide/search/shop_search/shop_search.md
Labels: Ready for MERGE

#1273 Login form components
  docs/extending/custom_components.md
Labels: Ready for MERGE
