Repository ibexa/documentation-developer, pull requests merged in 2020-07, with the labels that each got.

#1087 DB update caution: Do not force it
  docs/updating/4_update_database.md
Labels: Ready for MERGE

#1096 Fix xml namespaces in FT reference
  docs/api/field_type_reference.md
Labels: Ready for MERGE

#1098 Note about Rector commands
  docs/updating/upgrading_to_v3.md
Labels: Ready for MERGE

#1094 Specified conventions for core packages structure and namespaces
  docs/community_resources/package_structure.md
  mkdocs.yml
Labels: Ready for MERGE

#1101 Fixed broken link in Enable account registration
  docs/tutorials/platform_beginner/8_enable_account_registration.md
Labels: Ready for MERGE

#1071 Rewrite & broadly expand HttpCache doc
  docs/guide/http_cache.md
Labels: Ready for MERGE

#1095 Search in trash documented
  docs/api/public_php_api_managing_content.md
  docs/api/public_php_api_search.md
  docs/guide/search/search.md
  docs/guide/search/search_in_trash_reference.md
  docs/guide/search/sort_clause_reference/contenttypename_sort_clause.md
  docs/guide/search/sort_clause_reference/datetrashed_sort_clause.md
  docs/guide/search/sort_clause_reference/userlogin_sort_clause.md
  mkdocs.yml
Labels: Needs DEV review, Needs DOC review

#1102 Fix custom Query Type example
  docs/guide/controllers.md
Labels: Ready for MERGE

#1103 link update
  docs/guide/content_rendering.md
Labels: Ready for MERGE

#1104 EZEE-3176: Added FieldGroup Limitation type
  docs/guide/limitation_reference.md
  docs/guide/limitations.md
Labels: Ready for MERGE

#1100 Save incomplete draft
  docs/guide/content_model.md
Labels: Needs DEV review, Needs DOC review

#1107 Correct link to kernel upgrade guide for utf8mb4
  docs/updating/4_update_2.2.md
Labels: Ready for MERGE

#1099 EZP-31569: Repository filtering
  docs/api/public_php_api_search.md
  docs/guide/search/criteria_reference/field_criterion.md
  docs/guide/search/criteria_reference/fieldrelation_criterion.md
  docs/guide/search/criteria_reference/fulltext_criterion.md
  docs/guide/search/criteria_reference/isfieldempty_criterion.md
  docs/guide/search/criteria_reference/maplocationdistance_criterion.md
  docs/guide/search/search_criteria_reference.md
  docs/guide/search/sort_clause_reference.md
  docs/guide/search/sort_clause_reference/field_sort_clause.md
  docs/guide/search/sort_clause_reference/ismainlocation_sort_clause.md
  docs/guide/search/sort_clause_reference/maplocationdistance_sort_clause.md
  docs/guide/search/sort_clause_reference/random_sort_clause.md
Labels: Ready for MERGE

#1067 3.1 release notes
  docs/index.md
  docs/releases/ez_platform_v3.1.md
  docs/releases/img/3.1_collapsible_fields.png
  docs/releases/img/3.1_collapsible_fields_edit.png
  docs/releases/img/3_1_Content_browser_Tree_view.png
  docs/releases/img/3_1_URL_Management.png
  docs/releases/img/3_1_filter_elements.png
  mkdocs.yml
Labels: Ready for MERGE

#1106 Updating to v3.1
  docs/guide/site_factory.md
  docs/updating/4_update_2.3.md
  docs/updating/4_update_2.5.md
  docs/updating/4_update_3.1.md
  docs/updating/4_update_database.md
  mkdocs.yml
Labels: Ready for MERGE

#1109 Site Factory screenshots update
  docs/guide/img/site_factory_disabled.png
  docs/guide/img/site_factory_icon.png
  docs/guide/img/site_factory_site_list.png
  docs/guide/site_factory.md
Labels: Ready for MERGE

#1110 Update screenshots for Enterprise tutorial v3.1
  docs/tutorials/enterprise_beginner/img/enterprise_tut_choosing_airtime.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_empty_single_block.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_new_layout.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_select_articles.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_select_layout.png
Labels: Ready for MERGE

#1113 EZP-31588: As a Developer I want to configure search engine features …
  docs/releases/ez_platform_v3.1.md
Labels: Ready for MERGE

#1114 3.1 Screenshot update
  docs/community_resources/img/incontext_translation_ezplatform_crowdin.png
  docs/extending/img/extending_field_type_create.png
  docs/extending/img/udw_tabs.png
  docs/getting_started/img/first-steps-add-translation.png
  docs/getting_started/img/first-steps-create-content.png
  docs/getting_started/img/first-steps-create-ct.png
  docs/getting_started/img/first-steps-create-language.png
  docs/getting_started/img/first-steps-preview-content.png
  docs/getting_started/img/first-steps-translated-content.png
  docs/getting_started/img/welcome_page.png
  docs/guide/img/admin_panel_users.png
  docs/guide/img/content_structure_media_library.png
  docs/guide/img/web_debug_toolbar.png
  docs/guide/img/workflow_panel.png
Labels: Ready for MERGE

#1108 Elastic config description
  docs/guide/search/elastic.md
  mkdocs.yml
Labels: Needs DOC review

#1097 Elastic search extensibility
  docs/guide/search/criteria_reference/isuserbased_criterion.md
  docs/guide/search/criteria_reference/isuserenabled_criterion.md
  docs/guide/search/criteria_reference/useremail_criterion.md
  docs/guide/search/criteria_reference/userid_criterion.md
  docs/guide/search/criteria_reference/userlogin_criterion.md
  docs/guide/search/elastic.md
  docs/guide/search/extend_elasticsearch.md
  docs/guide/search/sort_clause_reference/random_sort_clause.md
  mkdocs.yml
Labels: Ready for MERGE

#1078 Update example template for user registration form
  docs/guide/user_management.md
Labels: Ready for MERGE

#1115 EZP-31651: Search bundle
  docs/guide/search/search.md
  docs/guide/templates.md
Labels: Ready for MERGE

#1111 Add tab extension and styling
  docs/css/custom.css
  mkdocs.yml
Labels: Ready for MERGE
