Repository ibexa/documentation-developer, pull requests merged in 2020-10, with the labels that each got.

#1153 Fix Solr boost caution to be correct
  docs/guide/search/solr.md
Labels: Ready for MERGE

#1141 Modify theme to fit new branding guidelines
  docs/css/custom.css
  docs/css/docs.switcher.css
  docs/fonts/Noto_Sans/LICENSE.txt
  docs/fonts/Noto_Sans/NotoSans-Bold.ttf
  docs/fonts/Noto_Sans/NotoSans-BoldItalic.ttf
  docs/fonts/Noto_Sans/NotoSans-Italic.ttf
  docs/fonts/Noto_Sans/NotoSans-Regular.ttf
  docs/fonts/Work_Sans/OFL.txt
  docs/fonts/Work_Sans/README.txt
  docs/fonts/Work_Sans/WorkSans-Regular.ttf
  docs/getting_started/install_ez_enterprise.md
  docs/getting_started/requirements.md
  docs/guide/persistence_cache.md
  docs/guide/sessions.md
  docs/images/alert-triangle.svg
  docs/images/developer-community-github-1.svg
  docs/images/ez-by-ibexa-logo.svg
  docs/images/ibexa-dxp-logo.svg
  docs/images/light-bulb-shine.svg
  docs/images/notes-edit.svg
  material/base.html
  material/partials/header.html
  material/partials/source.html
Labels: Ready for MERGE

#1155 Fix link to cron instructions for Link Manager
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#1149 update_redis_sentinel
  docs/guide/persistence_cache.md
Labels: Ready for MERGE

#1161 [3.x] Update doc regarding Redis Sentinel
  docs/guide/persistence_cache.md
Labels: Ready for MERGE

#1158 Fixed deprecation of controller references
  docs/guide/content_rendering.md
  docs/guide/controllers.md
  docs/guide/displaying_children_of_a_content_item.md
  docs/guide/templates.md
  docs/tutorials/enterprise_beginner/3_use_existing_blocks.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  docs/tutorials/platform_beginner/5_display_a_list_of_content_items.md
  docs/tutorials/platform_beginner/6_improve_configuration.md
  docs/tutorials/platform_beginner/7_embed_content.md
  docs/updating/4_update_2.2.md
Labels: Ready for MERGE

#1154 Add missing development server instructions
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#1157 EZEE-3289 - DFS configuration change
  docs/guide/clustering.md
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Needs DEV review, Needs DOC review

#1140 EZP-31462: Password hash command
  docs/upgrading/8_commit_test_merge.md
Labels: Ready for MERGE

#1151 Combine OSS, Enterprise and Commerce installation guides
  docs/getting_started/install_ez_platform.md
  docs/getting_started/troubleshooting.md
  docs/guide/databases.md
  docs/guide/site_factory.md
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
  mkdocs.yml
Labels: Ready for MERGE

#1166 EZP-31853: Inline custom tags in text toolbar only
  docs/extending/extending_online_editor.md
Labels: Ready for MERGE

#1164 Fixed mistakes in code examples
  docs/extending/extending_field_type.md
Labels: Ready for MERGE

#1163 EZP-31231: Updated Custom Styles documentation in regard to exposed 'id' parameter
  docs/guide/extending/extending_online_editor.md
Labels: Ready for MERGE

#1170 Fix field type tutorial
  docs/tutorials/generic_field_type/3_create_form_for_point2d.md
  docs/tutorials/generic_field_type/6_settings.md
  docs/tutorials/generic_field_type/8_data_migration.md
Labels: Ready for MERGE

#1168 Explain `InputAddItemToBasket` and `OutputAddItemToBasket` aliases
  docs/api/commerce_api/business_api/businessapi_invocation_service.md
Labels: Ready for MERGE

#1169 [HttpCache] Add limitations to example of using vary by cookie header
  docs/guide/http_cache.md
Labels: Ready for MERGE

#1176 EZEE-3303 - search engine comparison
  docs/guide/search/search.md
Labels: Needs DEV review, Needs DOC review

#1134 Explain how to pass the configuration to the UDW
  docs/extending/extending_udw.md
Labels: Needs DEV review

#1165 EZP-31851: ez_render Twig helpers
  docs/guide/templates.md
  docs/guide/twig_functions_reference.md
Labels: Ready for MERGE

#1183 EZP-31875: Implemented JWT authentication Controller
  docs/api/general_rest_usage.md
  docs/api/graphql.md
  docs/guide/security.md
Labels: Ready for MERGE

#1186 DAM connector
  docs/api/field_type_reference.md
  docs/guide/config_connector.md
  docs/guide/images.md
  mkdocs.yml
Labels: Ready for MERGE

#1172 EZEE-3224: Segmentation API
  docs/api/public_php_api_managing_users.md
  docs/guide/admin_panel.md
  docs/guide/img/admin_panel_segment.png
  docs/guide/img/admin_panel_segment_groups.png
  docs/guide/limitation_reference.md
  docs/guide/limitations.md
  docs/guide/permissions.md
  mkdocs.yml
Labels: Ready for MERGE

#1162 v3.2 release notes
  docs/index.md
  docs/releases/ez_platform_v3.1.md
  docs/releases/ibexa_dxp_v3.2.md
  docs/releases/img/3.2_commerce_cockpit.png
  docs/releases/img/3.2_new_login_page.png
  docs/releases/img/3.2_new_ui_content_structure.png
  docs/releases/img/3.2_targeting_block.png
  mkdocs.yml
Labels: Ready for MERGE

#1156 Proof HTTP cache page
  docs/guide/http_cache.md
Labels: Ready for MERGE

#1189 Enhance “Importing products API” examples
  docs/guide/econtent/econtent_cookbook/econtent_how_to_import_products/importing_products_api.md
Labels: Ready for MERGE

#1190 3.2 Update script
  docs/updating/4_update_3.2.md
  mkdocs.yml
Labels: Ready for MERGE

#1194 Update available password hashes
  docs/api/field_type_reference.md
Labels: Ready for MERGE

#1191 Use only satis hostname, not path
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#1196 3.2 release notes
  docs/index.md
  docs/releases/ez_platform_v3.1.md
  docs/releases/ibexa_dxp_v3.2.md
  docs/releases/img/3.2_commerce_cockpit.png
  docs/releases/img/3.2_new_login_page.png
  docs/releases/img/3.2_new_ui_content_structure.png
  docs/releases/img/3.2_targeting_block.png
  mkdocs.yml
Labels: Ready for MERGE

#1199 Update enterprise tutorial to 3.2
  docs/tutorials/enterprise_beginner/2_prepare_the_landing_page.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  docs/tutorials/enterprise_beginner/img/enterprise_tut_choosing_airtime.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_content_list_unstyled.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_content_list_window.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_empty_page.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_empty_single_block.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_first_form.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_form_collect_sub.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_form_creation.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_home_is_an_lp.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_image_in_article_ct.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_main_screen.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_new_layout.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_page_with_featured_articles.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_select_articles.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_select_layout.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_starting_point.png
Labels: Ready for MERGE

#1198 Update beginner tutorial to 3.2
  docs/tutorials/platform_beginner/img/bike_ride_adding_landmarks_to_the_ride_content_type.png
  docs/tutorials/platform_beginner/img/bike_tutorial_all_rides_admin.png
  docs/tutorials/platform_beginner/img/bike_tutorial_create_content_type.png
  docs/tutorials/platform_beginner/img/bike_tutorial_create_folder.png
  docs/tutorials/platform_beginner/img/bike_tutorial_hello_world.png
  docs/tutorials/platform_beginner/img/bike_tutorial_homepage_install_clean.png
  docs/tutorials/platform_beginner/img/bike_tutorial_nav_hub.png
  docs/tutorials/platform_beginner/img/bike_tutorial_preview_full_ride.png
  docs/tutorials/platform_beginner/img/bike_tutorial_ride_list.png
  docs/tutorials/platform_beginner/img/bike_tutorial_ride_with_landmarks.png
  docs/tutorials/platform_beginner/img/step8_admin_anonymous_policies.png
  docs/tutorials/platform_beginner/img/step8_register_page.png
  docs/tutorials/platform_beginner/img/step_8_role_mgmt_screen.png
Labels: Ready for MERGE

#1188 EZEE-3170 Docs for User Group skeletons
  docs/guide/site_factory.md
Labels: Needs DEV review

#1201 Update 4_update_3.2.md
  docs/updating/4_update_3.2.md
Labels: Ready for MERGE

#1159 Added explanation on what QueryType is when it's introduced
  docs/tutorials/platform_beginner/5_display_a_list_of_content_items.md
Labels: Needs DOC review

#1202 Update Admin UI tutorial 3.2
  docs/tutorials/extending_admin_ui/img/content_list_dropdown.png
  docs/tutorials/extending_admin_ui/img/content_list_edit.png
  docs/tutorials/extending_admin_ui/img/content_list_unfiltered.png
  docs/tutorials/extending_admin_ui/img/custom_tag.png
  docs/tutorials/extending_admin_ui/img/custom_tag_available_tags.png
  docs/tutorials/extending_admin_ui/img/custom_tag_factbox.png
  docs/tutorials/extending_admin_ui/img/dashboard.png
  docs/tutorials/extending_admin_ui/img/dashboard_articles_tab.png
  docs/tutorials/extending_admin_ui/img/top_menu.png
Labels: Needs DOC review

#1203 EZP-31834: Review of Extending eZ Platform tutorials
  docs/extending/custom_icons.md
  docs/extending/extending_dashboard.md
  docs/extending/extending_settings.md
  mkdocs.yml
Labels: Ready for MERGE

#1128 EZP-31593 Move REST API descriptions from old reference to developer doc
  docs/api/general_rest_usage.md
  docs/api/rest_api_authentication.md
  docs/api/rest_api_best_practices.md
  mkdocs.yml
Labels: Ready for MERGE

#1207 EZP-31734: Improve layout
  docs/css/custom.css
  docs/js/custom.js
  material/base.html
  material/partials/header.html
  material/partials/source.html
  material/partials/toc.html
Labels: Ready for MERGE
