Repository ibexa/documentation-developer, pull requests merged in 2020-08, with the labels that each got.

#1119 Updated images for the platform beginner tutorial
  docs/tutorials/platform_beginner/8_enable_account_registration.md
  docs/tutorials/platform_beginner/img/bike_tutorial_all_rides_admin.png
  docs/tutorials/platform_beginner/img/bike_tutorial_hello_world.png
  docs/tutorials/platform_beginner/img/bike_tutorial_homepage_install_clean.png
  docs/tutorials/platform_beginner/img/bike_tutorial_nav_hub.png
  docs/tutorials/platform_beginner/img/step6_admin_anonymous_policies.png
  docs/tutorials/platform_beginner/img/step6_register_page.png
  docs/tutorials/platform_beginner/img/step8_admin_anonymous_policies.png
  docs/tutorials/platform_beginner/img/step8_register_page.png
  docs/tutorials/platform_beginner/img/step_6_role_mgmt_screen.png
  docs/tutorials/platform_beginner/img/step_8_role_mgmt_screen.png
Labels: Needs DOC review

#1123 Typo fix
  docs/guide/retrieving_root_location.md
Labels: Ready for MERGE

#1117 Extending Admin UI and Generic FT - tutorial screenshot update
  docs/tutorials/extending_admin_ui/img/content_list_edit.png
  docs/tutorials/extending_admin_ui/img/content_list_unfiltered.png
  docs/tutorials/extending_admin_ui/img/custom_tag.png
  docs/tutorials/extending_admin_ui/img/custom_tag_available_tags.png
  docs/tutorials/extending_admin_ui/img/custom_tag_factbox.png
  docs/tutorials/extending_admin_ui/img/dashboard.png
  docs/tutorials/extending_admin_ui/img/images_tab_in_udw.png
  docs/tutorials/extending_admin_ui/img/top_menu.png
  docs/tutorials/extending_admin_ui/img/udw_before.png
  docs/tutorials/generic_field_type/3_create_form_for_point2d.md
  docs/tutorials/generic_field_type/5_add_a_field.md
  docs/tutorials/generic_field_type/img/create_new_content_type.png
  docs/tutorials/generic_field_type/img/field_definition_format_field.png
  docs/tutorials/generic_field_type/img/new_field_definition.png
  docs/tutorials/generic_field_type/img/point2d_field_definition.png
Labels: Ready for MERGE

#1118 EZP-31699 Enrich admin and content management doc sections with screenshots
  docs/guide/admin_panel.md
  docs/guide/content_management.md
  docs/guide/img/admin_panel.png
  docs/guide/img/admin_panel_assignments.png
  docs/guide/img/admin_panel_content_type_groups.png
  docs/guide/img/admin_panel_content_types.png
  docs/guide/img/admin_panel_languages.png
  docs/guide/img/admin_panel_object_state_groups.png
  docs/guide/img/admin_panel_policies.png
  docs/guide/img/admin_panel_roles.png
  docs/guide/img/admin_panel_sections.png
  docs/guide/img/admin_panel_system_info.png
  docs/guide/img/admin_panel_users.png
  docs/guide/img/content_management_drafts.png
  docs/guide/img/content_management_forms.png
  docs/guide/img/content_management_locations.png
  docs/guide/img/content_management_media.png
  docs/guide/img/content_management_relations.png
  docs/guide/img/content_management_tree.png
  docs/guide/img/content_management_visibility.png
Labels: Ready for MERGE

#1122 Database version parameter added
  docs/community_resources/installing-on-mac-os-and-windows.md
  docs/getting_started/install_ez_platform.md
  docs/guide/databases.md
Labels: Needs DEV review, Needs DOC review

#1120 Add Elasticsearch to requirements
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1121 Calendar PHP API
  docs/api/public_php_api_managing_content.md
Labels: Ready for MERGE

#1125 EZP-31725: Ubuntu 20.04 as an official requirement for an OS with PHP…
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1126 Added ezplatform-elastic-search-engine to list of enterprise bundles
  docs/guide/bundles.md
Labels: Ready for MERGE

#1131 Proposed AppBundle tip in upgrading_to_v3.md
  docs/updating/upgrading_to_v3.md
Labels: Ready for MERGE

#1130 Minor improvements of Upgrading eZ Platform to v3 page
  docs/updating/img/diagram_source/folder_structure_v3.xml
  docs/updating/img/folder_structure_v3.png
  docs/updating/upgrading_to_v3.md
Labels: Ready for MERGE
