Repository ibexa/documentation-developer, pull requests merged in 2020-11, with the labels that each got.

#1212 Clarify how default scope settings can affect all site-accesses, including admin
  docs/guide/siteaccess.md
  docs/guide/templates.md
Labels: Ready for MERGE

#1211 Hide UI guidelines for 3.2
  mkdocs.yml
Labels: Ready for MERGE

#1209 EZP-32120: Security checklist
  docs/community_resources/installing-on-mac-os-and-windows.md
  docs/getting_started/install_ez_platform.md
  docs/guide/security.md
  docs/guide/security_checklist.md
  mkdocs.yml
Labels: Ready for MERGE

#1214 [install_ez_platform.md] Get App Secret using command line instead of php script
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#1208 GraphQL example using array of clauses and ascending sorting
  docs/api/graphql_queries.md
Labels: Ready for MERGE

#1221 Fix custom Block attribute config
  docs/extending/extending_page.md
Labels: Ready for MERGE

#1217 EZP-32120: Security checklist v2
  docs/community_resources/installing-on-mac-os-and-windows.md
  docs/getting_started/install_ez_platform.md
  docs/guide/security.md
  docs/guide/security_checklist.md
  mkdocs.yml
Labels: Ready for MERGE

#1220 EZP-32107: Added Score sort clause
  docs/guide/search/sort_clause_reference.md
  docs/guide/search/sort_clause_reference/score_sort_clause.md
  mkdocs.yml
Labels: Ready for MERGE

#1222 EZEE-3352 - Perso documentation changes
  docs/guide/personalization/developer_guide/legacy_recommendation_api.md
  docs/guide/personalization/developer_guide/recommendation_api.md
  docs/guide/personalization/developer_guide/tracking_api.md
  docs/guide/personalization/developer_guide/tracking_with_yct.md
  docs/guide/personalization/developer_guide/user_api.md
  docs/guide/personalization/img/recommendation_overview.png
  docs/guide/personalization/personalization_quickstart.md
  docs/guide/personalization/recommendation_client.md
Labels: Needs DEV review, Needs DOC review

#1219 EC-243 Elasticsearch in eCommerce description
  docs/getting_started/install_ez_platform.md
  docs/guide/img/content_management_tree.png
  docs/guide/search/elastic.md
  docs/guide/shop_features/search.md
  docs/releases/ibexa_dxp_v3.2.md
Labels: Needs DEV review, Needs DOC review

#1210 Remove MFU configuration
  docs/guide/configuration.md
  docs/guide/file_management.md
Labels: Ready for MERGE

#1216 Add category for Page block attributes
  docs/extending/extending_page.md
Labels: Ready for MERGE

#1133 Update custom policies for Symfony 5 compliance.
  docs/guide/custom_policies.md
Labels: Ready for QA

#1215 EC-218: Basket revision
  docs/guide/basket/basket.md
  docs/guide/basket/basket_api/basket_api.md
  docs/guide/basket/basket_api/basket_data_model.md
  docs/guide/basket/basket_api/basket_events.md
  docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
  docs/guide/basket/basket_api/basket_events/basket_events.md
  docs/guide/basket/basket_api/basket_routing.md
  docs/guide/basket/basket_api/basketservice.md
  docs/guide/basket/basket_configuration.md
  docs/guide/basket/basket_faq.md
  docs/guide/basket/basket_features/additional_data_in_the_basket_line.md
  docs/guide/basket/basket_features/basket_messages.md
  docs/guide/basket/basket_features/basket_storage_time.md
  docs/guide/basket/basket_features/calculating_prices.md
  docs/guide/basket/basket_features/discontinued_products.md
  docs/guide/basket/basket_features/product_quantity_validation.md
  docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
  docs/guide/basket/basket_templates.md
  docs/guide/basket/basket_ui/adding_products_to_a_stored_basket_or_wishlist.md
  docs/guide/basket/basket_ui/adding_products_to_the_basket.md
  docs/guide/basket/basket_ui/basket_ui.md
  docs/guide/basket/calculating_prices.md
  docs/guide/img/basket_additional_data_2.png
  mkdocs.yml
Labels: Ready for MERGE

#1171 EZP-27458: Aggregation API
  docs/api/public_php_api_search.md
  docs/guide/search/aggregation_reference.md
  docs/guide/search/extend_elasticsearch.md
  docs/guide/search/search.md
  mkdocs.yml
Labels: Ready for MERGE

#1127 Extending page doc update (EZEE-2947)
  docs/extending/extending_page.md
Labels: Ready for MERGE

#1218 EZP-32096: Provide possibility to configure icon sets per siteaccess
  docs/guide/config_back_office.md
  docs/guide/twig_functions_reference.md
Labels: Ready for MERGE

#1226 Removed PB upgrade steps already covered by vendor/ezsystems/ezpublis…
  docs/updating/4_update_2.2.md
Labels: Ready for MERGE

#1227 EZP-32157: Added option to choose SA when creating custom alias
  docs/guide/url_management.md
Labels: Ready for MERGE

#1225 EC-218: Quick order, vouchers, payment revision
  docs/guide/img/payment_1.png
  docs/guide/img/payment_10.jpg
  docs/guide/img/payment_12.png
  docs/guide/img/payment_13.png
  docs/guide/img/payment_14.png
  docs/guide/img/payment_15.png
  docs/guide/img/payment_16.png
  docs/guide/img/payment_17.png
  docs/guide/img/payment_18.png
  docs/guide/img/payment_19.png
  docs/guide/img/payment_2.png
  docs/guide/img/payment_20.png
  docs/guide/img/payment_3.png
  docs/guide/img/payment_4.png
  docs/guide/img/payment_5.png
  docs/guide/img/payment_6.png
  docs/guide/img/payment_7.png
  docs/guide/img/payment_8.png
  docs/guide/img/payment_9.png
  docs/guide/img/quickorder_1.png
  docs/guide/img/quickorder_11.png
  docs/guide/img/quickorder_13.png
  docs/guide/img/quickorder_14.png
  docs/guide/img/quickorder_5.png
  docs/guide/img/vouchers_faq.png
  docs/guide/payment/building_new_payment_plugins.md
  docs/guide/payment/payment.md
  docs/guide/payment/payment_api.md
  docs/guide/payment/payment_configuration/invoice.md
  docs/guide/payment/payment_configuration/ogone.md
  docs/guide/payment/payment_configuration/paypal.md
  docs/guide/payment/payment_configuration/telecash.md
  docs/guide/payment/payment_faq.md
  docs/guide/payment/payment_troubleshooting.md
  docs/guide/payment/paypal.md
  docs/guide/quick_order/quick_order.md
  docs/guide/quick_order/quick_order_api.md
  docs/guide/quick_order/quick_order_configuration.md
  docs/guide/quick_order/quick_order_faq.md
  docs/guide/quick_order/quick_order_templates.md
  docs/guide/vouchers/voucher_templates.md
  docs/guide/vouchers/vouchers.md
  docs/guide/vouchers_from_erp/vouchers_faq.md
  docs/guide/vouchers_from_erp/vouchers_from_erp.md
  mkdocs.yml
Labels: Ready for MERGE

#1228 EZEE-3247 - Upgrade Guide update
  docs/guide/site_factory.md
  docs/upgrading/3_upgrade_app.md
  docs/upgrading/4_10_upgrade_other.md
  docs/upgrading/4_9_upgrade_other.md
  docs/upgrading/4_9_upgrade_site_factory.md
  docs/upgrading/5_upgrade_database.md
  docs/upgrading/upgrading_to_v3.md
  mkdocs.yml
Labels: Needs DOC review

#1229 EC-218: Pricing review
  docs/api/commerce_api/fields_for_ecommerce_data/pricefield.md
  docs/guide/erp_integration/remotepriceprovider.md
  docs/guide/img/price_engine_1.png
  docs/guide/img/price_engine_2.png
  docs/guide/img/price_engine_3.png
  docs/guide/img/price_engine_4.png
  docs/guide/img/price_engine_5.png
  docs/guide/pricing/price_api/localvatservice.md
  docs/guide/pricing/price_api/price_data_model.md
  docs/guide/pricing/price_api/price_providers.md
  docs/guide/pricing/price_api/standardcountryzoneservice.md
  docs/guide/pricing/price_api/standardpricefactory.md
  docs/guide/pricing/price_api/standardtemplatedebitorservice.md
  docs/guide/pricing/price_engine.md
  docs/guide/pricing/price_engine_api/price_engine_constants.md
  docs/guide/pricing/price_engine_api/price_engine_services/chainpriceservice/chainpriceservice.md
  docs/guide/pricing/price_engine_api/price_engine_services/chainpriceservice/price_providers/localpriceprovider.md
  docs/guide/pricing/price_engine_api/price_engine_services/chainpriceservice/price_providers/price_providers.md
  docs/guide/pricing/price_engine_api/price_engine_services/ez5scaledpriceservice.md
  docs/guide/pricing/price_engine_api/price_engine_services/localvatservice.md
  docs/guide/pricing/price_engine_api/price_engine_services/standardpricefactory.md
  docs/guide/pricing/price_engine_api/price_engine_services/standardtemplatedebitorservice.md
  docs/guide/pricing/price_engine_cookbook/price_engine_cookbook.md
  docs/guide/pricing/price_engine_cookbook/recipe_how_to_implement_new_price_provider.md
  docs/guide/pricing/price_engine_cookbook/recipe_how_to_work_with_pricerequest_and_priceresponse.md
  docs/guide/pricing/price_engine_faq.md
  docs/guide/pricing/price_engine_templates/price_engine_templates.md
  docs/guide/pricing/price_engine_templates/rendering_for_prices.md
  docs/guide/pricing/price_templates.md
  mkdocs.yml
Labels: Ready for MERGE

#1238 Multisite minor branding fix
  docs/guide/multisite.md
Labels: Needs DOC review

#1234 Security checklist: Refer also to dev guidelines
  docs/community_resources/development_guidelines.md
  docs/guide/security_checklist.md
Labels: Ready for MERGE

#1223 [Update 2.5] Add mention of powered by header and how to configure it
  docs/updating/4_update_2.5.md
Labels: Ready for MERGE
