Repository ibexa/documentation-developer, pull requests merged in 2021-01, with the labels that each got.

#1271 EZP-32110: Exposed more search result data from Pagefanta adapters
  docs/api/public_php_api_search.md
Labels: Ready for MERGE

#1272 Minimal ezcommerce functionality to Content and Experience editions
  docs/guide/basket/basket.md
  docs/guide/basket/basket_api/basket_data_model.md
  docs/guide/basket/basket_api/basket_events.md
  docs/guide/basket/basket_api/basket_routing.md
  docs/guide/basket/basket_api/basketservice.md
  docs/guide/basket/basket_configuration.md
  docs/guide/basket/basket_templates.md
  docs/guide/basket/calculating_prices.md
  docs/guide/basket/wishlist_and_stored_baskets.md
  docs/guide/breadcrumbs/breadcrumbs.md
  docs/guide/breadcrumbs/breadcrumbs_api.md
  docs/guide/breadcrumbs/breadcrumbs_templates.md
  docs/guide/breadcrumbs/custom_breadcrumbs.md
  docs/guide/catalog/catalog.md
  docs/guide/catalog/catalog_api/catalog_element.md
  docs/guide/catalog/catalog_api/customer_skus.md
  docs/guide/catalog/catalog_api/extending_a_catalogfactory.md
  docs/guide/catalog/catalog_api/productnode.md
  docs/guide/catalog/catalog_api/producttype.md
  docs/guide/catalog/catalog_api/routing_system.md
  docs/guide/catalog/catalog_templates.md
  docs/guide/catalog/product_rendering.md
  docs/guide/catalog/product_variants/product_variant_api.md
  docs/guide/catalog/product_variants/product_variants.md
  docs/guide/catalog/product_variants/setting_up_variants_from_external_source.md
  docs/guide/payment/payment.md
  docs/guide/payment/payment_api.md
  docs/guide/payment/payment_troubleshooting.md
  docs/guide/search/shop_search/extending_search/adding_elements_to_autosuggestion.md
  docs/guide/search/shop_search/extending_search/custom_search.md
  docs/guide/search/shop_search/extending_search/custom_search_conditions.md
  docs/guide/search/shop_search/extending_search/custom_sorting_options.md
  docs/guide/search/shop_search/extending_search/indexer_plugin_for_custom_field_types.md
  docs/guide/search/shop_search/extending_search/indexing_email_data.md
  docs/guide/search/shop_search/extending_search/indexing_file_content.md
  docs/guide/search/shop_search/extending_search/modifying_the_search_query.md
  docs/guide/search/shop_search/search_api.md
  docs/guide/search/shop_search/search_autosuggest.md
  docs/guide/search/shop_search/search_configuration.md
  docs/guide/search/shop_search/search_indexing.md
  docs/guide/search/shop_search/search_synonyms.md
  docs/guide/search/shop_search/search_templates.md
  docs/guide/search/shop_search/searching_for_products.md
  docs/guide/search/shop_search/shop_search.md
  docs/guide/search/shop_search/using_solr_spellcheck.md
  docs/guide/shop_features/catalog.md
  docs/guide/shop_features/payment_and_shipping.md
  docs/guide/shop_features/pricing.md
  docs/guide/shop_features/search.md
  docs/guide/shop_features/shop_features.md
Labels: Ready for MERGE

#1270 EZP-31617 - Enabling Personalization
  docs/guide/personalization/enabling_personalization.md
  mkdocs.yml
Labels: Needs DEV review

#1276 Fix a note in "Enabling perso"
  docs/guide/personalization/enabling_personalization.md
Labels: Needs DOC review

#1258 EZP-31309: Migration bundle
  docs/guide/data_migration.md
  mkdocs.yml
Labels: Ready for MERGE

#1274 Update bundle descriptions
  docs/getting_started/bundles_starter_pack.md
  docs/guide/bundles.md
  mkdocs.yml
Labels: Ready for MERGE

#1279 Fixed wrong path to OE custom button JS code
  docs/extending/online_editor_button.md
Labels: Ready for MERGE

#1277 EZP-32259: Replace ezplatform with ibexa in commands
  docs/api/graphql.md
  docs/api/public_php_api_managing_content.md
  docs/getting_started/install_ez_platform.md
  docs/getting_started/troubleshooting.md
  docs/guide/basket/basket_configuration.md
  docs/guide/cache/content_cache_refresh/content_cache_refresh.md
  docs/guide/cache/content_cache_refresh/http_caching.md
  docs/guide/cache/navigation_cache.md
  docs/guide/clustering.md
  docs/guide/clustering_aws_s3.md
  docs/guide/config_back_office.md
  docs/guide/config_repository.md
  docs/guide/data_providers/data_providers.md
  docs/guide/econtent/econtent_cookbook/econtent_how_to_import_products/importing_and_indexing_data_sql.md
  docs/guide/econtent/econtent_cookbook/econtent_how_to_import_products/importing_products_api.md
  docs/guide/econtent/econtent_features/indexing_econtent_data/indexing_econtent_data.md
  docs/guide/econtent/econtent_features/staging_system.md
  docs/guide/erp_integration/checkout_order/failed_order_process/lost_orders.md
  docs/guide/erp_integration/erp_communication/erp_communication.md
  docs/guide/erp_integration/erp_communication/erp_components/erp_component_messages/erp_message_class_generator.md
  docs/guide/erp_integration/erp_communication/guides/creating_a_new_erp_message/create_project_specific_message.md
  docs/guide/erp_integration/erp_communication/guides/creating_a_new_erp_message/create_standard_message.md
  docs/guide/erp_integration/erp_communication/guides/creating_a_new_erp_message/creating_a_new_erp_message.md
  docs/guide/images.md
  docs/guide/internationalization.md
  docs/guide/job_system.md
  docs/guide/multi_language_siteaccesses.md
  docs/guide/personalization/recommendation_client.md
  docs/guide/search/elastic.md
  docs/guide/search/search.md
  docs/guide/search/shop_search/extending_search/indexer_plugin_for_custom_field_types.md
  docs/guide/search/shop_search/search_indexing.md
  docs/guide/search/solr.md
  docs/guide/shop_configuration/required_crontab_tasks.md
  docs/guide/url_management.md
  docs/guide/user_management/user_management.md
  docs/migrating/common_issues.md
Labels: Ready for MERGE

#1280 EZP-31659: Support for getting the results for a location
  docs/guide/controllers.md
Labels: Ready for MERGE

#1282 Fixed formatting in ez_render parameter list
  docs/guide/twig_functions_reference.md
Labels: Ready for MERGE

#1281 EZP-32277: Support for setting up Trusted Proxies via ENVs or symfony semantic configuration
  docs/guide/http_cache.md
Labels: Ready for MERGE

#1263 3.3 release notes
  docs/index.md
  docs/releases/ibexa_dxp_v3.3.md
  docs/releases/img/3.3_perso_ui.png
  mkdocs.yml
Labels: Ready for MERGE

#1266 Update installation instruction
  docs/getting_started/img/Using_Composer_Auth_token.png
  docs/getting_started/install_ez_platform.md
  docs/index.md
Labels: Ready for MERGE

#1283 Fixed indentation in Random Block Listener example
  docs/tutorials/enterprise_beginner/4_create_a_custom_block.md
Labels: Ready for MERGE

#1286 Installation: add to vcs and fix command
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#1278 Update Win/Macos installation guide
  docs/community_resources/installing-on-mac-os-and-windows.md
  docs/getting_started/install-on-mac-os-and-windows.md
  docs/getting_started/install_ez_platform.md
  mkdocs.yml
Labels: Ready for MERGE

#1284 Update Beginner tutorial to v3.3
  docs/index.md
  docs/tutorials/platform_beginner/2_create_the_content_model.md
  docs/tutorials/platform_beginner/3_customize_the_front_page.md
  docs/tutorials/platform_beginner/building_a_bicycle_route_tracker_in_ez_platform.md
  docs/tutorials/platform_beginner/img/bike_tutorial_all_rides_admin.png
  docs/tutorials/platform_beginner/img/bike_tutorial_homepage_install_clean.png
  docs/tutorials/platform_beginner/img/bike_tutorial_nav_hub.png
  mkdocs.yml
Labels: Ready for MERGE

#1287 Update Experience tutorial to 3.3
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
  docs/tutorials/enterprise_beginner/2_prepare_the_landing_page.md
  docs/tutorials/enterprise_beginner/3_use_existing_blocks.md
  docs/tutorials/enterprise_beginner/4_create_a_custom_block.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  docs/tutorials/enterprise_beginner/ez_enterprise_beginner_tutorial_-_its_a_dogs_world.md
  docs/tutorials/enterprise_beginner/img/enterprise_tut_hide_content.png
  mkdocs.yml
Labels: Ready for MERGE

#1290 Equal sign between session name and ID, not colon
  docs/api/rest_api_authentication.md
Labels: Ready for MERGE

#1289 EZP-31616: Event reference
  docs/guide/repository/event_reference/content_events.md
  docs/guide/repository/event_reference/content_type_events.md
  docs/guide/repository/event_reference/event_reference.md
  docs/guide/repository/event_reference/language_events.md
  docs/guide/repository/event_reference/location_events.md
  docs/guide/repository/event_reference/object_state_events.md
  docs/guide/repository/event_reference/other_events.md
  docs/guide/repository/event_reference/page_events.md
  docs/guide/repository/event_reference/role_events.md
  docs/guide/repository/event_reference/section_events.md
  docs/guide/repository/event_reference/site_events.md
  docs/guide/repository/event_reference/trash_events.md
  docs/guide/repository/event_reference/url_events.md
  docs/guide/repository/event_reference/user_events.md
  mkdocs.yml
Labels: Ready for MERGE

#1288 Import file module
  .gitignore
  main.py
Labels: Ready for MERGE

#1295 EZP-32239: Revise Commerce config section
  docs/guide/erp_integration/erp_integration.md
  docs/guide/img/base_configuration.png
  docs/guide/img/configure_erp.png
  docs/guide/img/shop_configuration_settings.png
  docs/guide/job_system.md
  docs/guide/logging/logfile_rotation.md
  docs/guide/pricing/price_api/price_providers.md
  docs/guide/pricing/price_engine_faq.md
  docs/guide/shop_configuration.md
  docs/guide/shop_configuration/advanced_configuration.md
  docs/guide/shop_configuration/configure_erp_connection.md
  docs/guide/shop_configuration/email_server.md
  docs/guide/shop_configuration/required_crontab_tasks.md
  docs/guide/shop_configuration/session_handling.md
  docs/guide/shop_configuration/set_up_a_new_language.md
  docs/guide/shop_configuration/shop_configuration.md
  docs/guide/shop_configuration/storing_sessions_in_memcache.md
  mkdocs.yml
Labels: Ready for MERGE

#1294 Update extending tutorial to use code import
  code_samples/back_office/custom_tags/factbox/config/packages/custom_tags.yaml
  code_samples/back_office/custom_tags/factbox/templates/field_type/ezrichtext/custom_tag/factbox.html.twig
  code_samples/back_office/custom_tags/factbox/translations/custom_tags.en.yaml
  code_samples/back_office/dashboard/article_tab/config/services.yaml
  code_samples/back_office/dashboard/article_tab/src/Tab/Dashboard/Everyone/EveryoneArticleTab.php
  code_samples/back_office/menu/content_list/config/routes.yaml
  code_samples/back_office/menu/content_list/src/Controller/AllContentListController.php
  code_samples/back_office/menu/content_list/src/EventSubscriber/MyMenuSubscriber.php
  code_samples/back_office/menu/content_list/templates/list/all_content_list.html.twig
  code_samples/back_office/menu/content_list_edit_button/src/Controller/AllContentListController.php
  code_samples/back_office/menu/content_list_edit_button/templates/list/all_content_list.html.twig
  code_samples/back_office/menu/filtered_content_list/config/routes.yaml
  code_samples/back_office/menu/filtered_content_list/src/Controller/AllContentListController.php
  code_samples/back_office/menu/filtered_content_list/templates/list/all_content_list.html.twig
  docs/tutorials/extending_admin_ui/1_creating_a_dashboard_tab.md
  docs/tutorials/extending_admin_ui/2_creating_a_content_list.md
  docs/tutorials/extending_admin_ui/3_filtering_the_content_list.md
  docs/tutorials/extending_admin_ui/3b_adding_edit_button_content_list.md
  docs/tutorials/extending_admin_ui/4_adding_a_custom_tag.md
  docs/tutorials/extending_admin_ui/extending_admin_ui.md
  mkdocs.yml
Labels: Ready for MERGE

#1296 S3 cluster configuration fix for 3.x
  docs/guide/clustering_aws_s3.md
Labels: Needs DEV review
