Repository ibexa/documentation-developer, pull requests merged in 2021-11, with the labels that each got.

#1470 IBX-711, IBX-1069: Update migration actions
  code_samples/data_migration/config/custom_services.yaml
  code_samples/data_migration/src/Migrations/Action/AssignSection.php
  code_samples/data_migration/src/Migrations/Action/AssignSectionDenormalizer.php
  code_samples/data_migration/src/Migrations/Action/AssignSectionExecutor.php
  docs/guide/data_migration.md
Labels: Ready for MERGE

#1465 IBX-816 - Revise Image and RichText extensibility doc
  code_samples/back_office/image_editor/config/packages/image_editor.yaml
  code_samples/back_office/image_editor/src/AdditionalInformation.php
  code_samples/back_office/images/config/default_settings.yaml
  code_samples/back_office/images/config/packages/images_basic.yaml
  code_samples/back_office/images/config/packages/images_live.yaml
  code_samples/back_office/images/config/packages/images_remote.yaml
  code_samples/back_office/images/config/routes.yaml
  code_samples/back_office/images/config/services.yaml
  code_samples/back_office/images/src/PlaceholderProvider.php
  code_samples/back_office/images/src/SvgController.php
  code_samples/back_office/images/src/SvgExtension.php
  code_samples/back_office/images/templates/svg_helper.html.twig
  code_samples/back_office/online_editor/assets/js/online_editor/buttons/date.js
  code_samples/back_office/online_editor/assets/js/online_editor/buttons/hr.js
  code_samples/back_office/online_editor/assets/js/online_editor/plugins/date.js
  code_samples/back_office/online_editor/config/packages/custom_buttons.yaml
  code_samples/back_office/online_editor/config/packages/custom_classes.yaml
  code_samples/back_office/online_editor/config/packages/custom_data_attributes.yaml
  code_samples/back_office/online_editor/config/packages/custom_plugin.yaml
  code_samples/back_office/online_editor/config/packages/custom_styles.yaml
  code_samples/back_office/online_editor/config/packages/custom_styles_highlight.yaml
  code_samples/back_office/online_editor/config/packages/custom_styles_note_box.yaml
  code_samples/back_office/online_editor/config/packages/custom_tags.yaml
  code_samples/back_office/online_editor/config/packages/ezplatform_page_fieldtype.yaml
  code_samples/back_office/online_editor/src/event/subscriber/RichTextBlockSubscriber.php
  code_samples/back_office/online_editor/templates/ezfactbox.html.twig
  code_samples/back_office/online_editor/templates/linktag.html.twig
  code_samples/back_office/online_editor/translations/custom_tags.en.yaml
  code_samples/back_office/online_editor/translations/linktag.en.yaml
  docs/extending/extending_image_editor.md
  docs/extending/extending_online_editor.md
  docs/extending/online_editor_button.md
  docs/extending/online_editor_plugin.md
  docs/extending/richtext_block.md
  docs/guide/image_editor.md
  docs/guide/images.md
  mkdocs.yml
Labels: Needs DOC review, Needs DEV review

#1482 IBX-1324: Updated webpack encore config for Personalization
  docs/guide/personalization/recommendation_client.md
Labels: Needs DOC review

#1483 Remove Extending Back Office tutorial
  code_samples/back_office/custom_tags/factbox/config/packages/custom_tags.yaml
  code_samples/back_office/custom_tags/factbox/templates/field_type/ezrichtext/custom_tag/factbox.html.twig
  code_samples/back_office/custom_tags/factbox/translations/custom_tags.en.yaml
  docs/extending/extending_back_office.md
  docs/extending/extending_online_editor.md
  docs/index.md
  docs/migrating/migrating_from_ez_publish.md
  docs/tutorials/extending_admin_ui/1_creating_a_dashboard_tab.md
  docs/tutorials/extending_admin_ui/2_creating_a_content_list.md
  docs/tutorials/extending_admin_ui/3_filtering_the_content_list.md
  docs/tutorials/extending_admin_ui/3b_adding_edit_button_content_list.md
  docs/tutorials/extending_admin_ui/4_adding_a_custom_tag.md
  docs/tutorials/extending_admin_ui/extending_admin_ui.md
  docs/tutorials/extending_admin_ui/img/content_list_dropdown.png
  docs/tutorials/extending_admin_ui/img/content_list_edit.png
  docs/tutorials/extending_admin_ui/img/content_list_unfiltered.png
  docs/tutorials/extending_admin_ui/img/custom_tag.png
  docs/tutorials/extending_admin_ui/img/custom_tag_available_tags.png
  docs/tutorials/extending_admin_ui/img/custom_tag_factbox.png
  docs/tutorials/extending_admin_ui/img/dashboard.png
  docs/tutorials/extending_admin_ui/img/dashboard_articles_tab.png
  docs/tutorials/extending_admin_ui/img/top_menu.png
  mkdocs.yml
Labels: Ready for MERGE

#1488 Move permission use cases
  docs/guide/admin_panel.md
  docs/guide/limitation_reference.md
  docs/guide/permission_use_cases.md
  docs/guide/permissions.md
  mkdocs.yml
Labels: Ready for MERGE

#1489 IBX-1410: Added UserId, UserEmail & UserLogin Criterions handling
  docs/guide/search/criteria_reference/useremail_criterion.md
  docs/guide/search/criteria_reference/userid_criterion.md
  docs/guide/search/criteria_reference/userlogin_criterion.md
Labels: Ready for MERGE

#1486 Example of using focal point
  docs/guide/content_rendering/embed_and_list_content/render_images.md
Labels: Ready for MERGE

#1485 IBX-1130: Add language argument to translatable fields
  docs/api/graphql_queries.md
Labels: Ready for MERGE

#1490 IBX-1438: Improve skeleton merging section in update guide
  docs/updating/from_2.5/to_3.3.md
Labels: Ready for MERGE

#1495 FieldType : how to register the Type class
  docs/api/field_type_type_and_value.md
Labels: Ready for MERGE

#1494 Fix typo in relation cache tags example
  docs/guide/cache/content_aware_cache.md
Labels: Ready for MERGE

#1497 Rebranding, pt. 2
  code_samples/back_office/images/src/PlaceholderProvider.php
  docs/api/field_type/create_custom_field_type_comparison.md
  docs/api/field_type/create_custom_generic_field_type.md
  docs/api/field_type_form_and_template.md
  docs/community_resources/support_maintenance_faq.md
  docs/extending/custom_icons.md
  docs/extending/extending_image_editor.md
  docs/extending/extending_online_editor.md
  docs/getting_started/first_steps.md
  docs/guide/back_office_translations.md
  docs/guide/cache/http_cache_config.md
  docs/guide/cache/symfony_reverse_proxy.md
  docs/guide/clustering_aws_s3.md
  docs/guide/config_back_office.md
  docs/guide/config_connector.md
  docs/guide/config_repository.md
  docs/guide/configuration.md
  docs/guide/content_rendering/design_engine/add_new_design.md
  docs/guide/content_rendering/layout/add_forgot_password.md
  docs/guide/content_rendering/templates/overriding_shop_templates.md
  docs/guide/custom_policies.md
  docs/guide/econtent/staging_system.md
  docs/guide/image_editor.md
  docs/guide/images.md
  docs/guide/internationalization.md
  docs/guide/limitations.md
  docs/guide/multisite/multisite_configuration.md
  docs/guide/multisite/set_up_campaign_siteaccess.md
  docs/guide/multisite/set_up_translation_siteaccess.md
  docs/guide/multisite/site_factory.md
  docs/guide/multisite/site_factory_configuration.md
  docs/guide/multisite/siteaccess_matching.md
  docs/guide/page/create_custom_page_block.md
  docs/guide/performance.md
  docs/guide/persistence_cache.md
  docs/guide/personalization/recommendation_client.md
  docs/guide/project_organization.md
  docs/guide/request_lifecycle.md
  docs/guide/search/solr.md
  docs/guide/security.md
  docs/guide/sessions.md
  docs/guide/url_management.md
Labels: Ready for MERGE

#1496 IBX-1446: Extract examples from PHP API doc into separate files
  code_samples/api/public_php_api/config/packages/views.yaml
  code_samples/api/public_php_api/src/Command/AddLanguageCommand.php
  code_samples/api/public_php_api/src/Command/AddLocationToContentCommand.php
  code_samples/api/public_php_api/src/Command/BookmarkCommand.php
  code_samples/api/public_php_api/src/Command/BrowseLocationsCommand.php
  code_samples/api/public_php_api/src/Command/CalendarCommand.php
  code_samples/api/public_php_api/src/Command/CreateContentCommand.php
  code_samples/api/public_php_api/src/Command/CreateContentTypeCommand.php
  code_samples/api/public_php_api/src/Command/CreateImageCommand.php
  code_samples/api/public_php_api/src/Command/DeleteContentCommand.php
  code_samples/api/public_php_api/src/Command/FilterCommand.php
  code_samples/api/public_php_api/src/Command/FilterLocationCommand.php
  code_samples/api/public_php_api/src/Command/FindComplexCommand.php
  code_samples/api/public_php_api/src/Command/FindContentCommand.php
  code_samples/api/public_php_api/src/Command/FindInTrashCommand.php
  code_samples/api/public_php_api/src/Command/FindUrlCommand.php
  code_samples/api/public_php_api/src/Command/FindWithAggregationCommand.php
  code_samples/api/public_php_api/src/Command/HideLocationCommand.php
  code_samples/api/public_php_api/src/Command/MoveContentCommand.php
  code_samples/api/public_php_api/src/Command/ObjectStateCommand.php
  code_samples/api/public_php_api/src/Command/SectionCommand.php
  code_samples/api/public_php_api/src/Command/SegmentCommand.php
  code_samples/api/public_php_api/src/Command/SetMainLocationCommand.php
  code_samples/api/public_php_api/src/Command/TranslateContentCommand.php
  code_samples/api/public_php_api/src/Command/TrashContentCommand.php
  code_samples/api/public_php_api/src/Command/UpdateContentCommand.php
  code_samples/api/public_php_api/src/Command/ViewContentCommand.php
  code_samples/api/public_php_api/src/Command/ViewContentMetaDataCommand.php
  code_samples/api/public_php_api/src/Command/WorkflowCommand.php
  code_samples/api/public_php_api/src/Controller/CustomController.php
  code_samples/api/public_php_api/src/Controller/CustomFilterController.php
  code_samples/api/public_php_api/src/Controller/PaginationController.php
  code_samples/api/public_php_api/templates/custom.html.twig
  code_samples/api/public_php_api/templates/custom_filter.html.twig
  code_samples/api/public_php_api/templates/custom_pagination.html.twig
  docs/api/public_php_api.md
  docs/api/public_php_api_browsing.md
  docs/api/public_php_api_creating_content.md
  docs/api/public_php_api_managing_content.md
  docs/api/public_php_api_managing_repository.md
  docs/api/public_php_api_managing_users.md
  docs/api/public_php_api_search.md
  docs/api/public_php_api_url_service.md
Labels: Ready for MERGE

#1499 IBX-1446: Extract examples from PHP API doc into separate files
  code_samples/api/public_php_api/config/packages/views.yaml
  code_samples/api/public_php_api/src/Command/AddLanguageCommand.php
  code_samples/api/public_php_api/src/Command/AddLocationToContentCommand.php
  code_samples/api/public_php_api/src/Command/BookmarkCommand.php
  code_samples/api/public_php_api/src/Command/BrowseLocationsCommand.php
  code_samples/api/public_php_api/src/Command/CalendarCommand.php
  code_samples/api/public_php_api/src/Command/CreateContentCommand.php
  code_samples/api/public_php_api/src/Command/CreateContentTypeCommand.php
  code_samples/api/public_php_api/src/Command/CreateImageCommand.php
  code_samples/api/public_php_api/src/Command/DeleteContentCommand.php
  code_samples/api/public_php_api/src/Command/FilterCommand.php
  code_samples/api/public_php_api/src/Command/FilterLocationCommand.php
  code_samples/api/public_php_api/src/Command/FindComplexCommand.php
  code_samples/api/public_php_api/src/Command/FindContentCommand.php
  code_samples/api/public_php_api/src/Command/FindInTrashCommand.php
  code_samples/api/public_php_api/src/Command/FindUrlCommand.php
  code_samples/api/public_php_api/src/Command/FindWithAggregationCommand.php
  code_samples/api/public_php_api/src/Command/HideLocationCommand.php
  code_samples/api/public_php_api/src/Command/MoveContentCommand.php
  code_samples/api/public_php_api/src/Command/ObjectStateCommand.php
  code_samples/api/public_php_api/src/Command/SectionCommand.php
  code_samples/api/public_php_api/src/Command/SegmentCommand.php
  code_samples/api/public_php_api/src/Command/SetMainLocationCommand.php
  code_samples/api/public_php_api/src/Command/TranslateContentCommand.php
  code_samples/api/public_php_api/src/Command/TrashContentCommand.php
  code_samples/api/public_php_api/src/Command/UpdateContentCommand.php
  code_samples/api/public_php_api/src/Command/ViewContentCommand.php
  code_samples/api/public_php_api/src/Command/ViewContentMetaDataCommand.php
  code_samples/api/public_php_api/src/Command/WorkflowCommand.php
  code_samples/api/public_php_api/src/Controller/CustomController.php
  code_samples/api/public_php_api/src/Controller/CustomFilterController.php
  code_samples/api/public_php_api/src/Controller/PaginationController.php
  code_samples/api/public_php_api/templates/custom.html.twig
  code_samples/api/public_php_api/templates/custom_filter.html.twig
  code_samples/api/public_php_api/templates/custom_pagination.html.twig
  docs/api/public_php_api.md
  docs/api/public_php_api_browsing.md
  docs/api/public_php_api_creating_content.md
  docs/api/public_php_api_managing_content.md
  docs/api/public_php_api_managing_repository.md
  docs/api/public_php_api_managing_users.md
  docs/api/public_php_api_search.md
  docs/api/public_php_api_url_service.md
Labels: Ready for MERGE

#1500 Update security_checklist.md
  docs/guide/security_checklist.md
Labels: Ready for MERGE
