Repository ibexa/documentation-developer, pull requests merged in 2021-06, with the labels that each got.

#1377 Added GH action for building the docs
  .github/workflows/build.yaml
  .gitignore
  README.md
Labels: Ready for MERGE

#1379 IBX-378: Expand migration doc by providing samples and additional explanations
  docs/guide/data_migration.md
Labels: Ready for MERGE

#1392 Update images.md
  docs/guide/images.md
Labels: Ready for MERGE

#1393 IBX-381: Image Editor quality setting
  docs/guide/image_editor.md
Labels: Ready for MERGE

#1391 IBX-410: Image rendering
  docs/guide/content_rendering/embed_and_list_content/render_images.md
  docs/guide/content_rendering/image_variations.md
  docs/guide/images.md
  mkdocs.yml
Labels: Ready for MERGE

#1389 [Content rendering] URLs and routes
  docs/guide/content_rendering/twig_function_reference/url_twig_functions.md
  docs/guide/content_rendering/urls_and_routes.md
  docs/guide/routereference.md
  mkdocs.yml
Labels: Ready for MERGE

#1395 Method fix
  docs/guide/custom_policies.md
Labels: Needs DEV review

#1390 IBX-386: Extended DAM configuration
  docs/guide/config_connector.md
Labels: Ready for MERGE

#1396 IBX-401 - Adding custom page block validators
  docs/extending/extending_page.md
Labels: Needs DOC review

#1399 Twig reference fix
  docs/guide/content_rendering/twig_function_reference/url_twig_functions.md
Labels: Needs DOC review

#1401 URLs and routes fix
  docs/guide/content_rendering/urls_and_routes.md
Labels: Needs DOC review

#1400 Add example for accessing binary file via API
  docs/guide/file_management.md
  docs/guide/images.md
Labels: Ready for MERGE

#1397 EZP-32859: Note about translating field group names
  docs/guide/config_repository.md
Labels: Ready for MERGE
