Repository ibexa/documentation-developer, pull requests merged in 2021-03, with the labels that each got.

#1319 EZP-31818: Added note about url_alias issues for language misconfiguration
  docs/guide/url_management.md
Labels: Needs DEV review, Needs DOC review

#1324 Remove outstanding mentions of Legacy Bridge
  docs/guide/clustering.md
  docs/guide/content_rendering.md
  docs/guide/file_management.md
Labels: Ready for MERGE

#1320 New navigation and layout fixes
  docs/css/custom.css
  docs/css/navigation.css
  docs/index.md
  docs/js/custom.js
  mkdocs.yml
  theme/404.html
  theme/partials/version_switcher.html
Labels: Ready for MERGE

#1326 Fix minor tutorial issues
  docs/tutorials/platform_beginner/1_get_ready.md
  docs/tutorials/platform_beginner/3_customize_the_front_page.md
  docs/tutorials/platform_beginner/4_display_single_content_item.md
  docs/tutorials/platform_beginner/5_display_a_list_of_content_items.md
  docs/tutorials/platform_beginner/7_embed_content.md
  docs/tutorials/platform_beginner/8_enable_account_registration.md
Labels: Ready for MERGE

#1325 Ibexa:setup command
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#1323 EZP-32195 - Perso API documentation rewrite pt. 2
  docs/guide/personalization/best_practices/tracking_integration.md
  docs/guide/personalization/developer_guide/tracking_api.md
Labels: Needs DEV review, Needs DOC review

#1317 Revise design engine page
  docs/guide/design_engine.md
Labels: Ready for MERGE

#1327 EZP-32213: Document creating search for the front page
  code_samples/front/search/search_bar/config/packages/views.yaml
  code_samples/front/search/search_bar/templates/themes/standard/full/search.html.twig
  code_samples/front/search/search_bar/templates/themes/standard/pagelayout.html.twig
  code_samples/front/search/search_bar/templates/themes/standard/parts/search_bar.html.twig
  code_samples/front/search/search_bar/templates/themes/standard/parts/search_form.html.twig
  docs/guide/search/adding_search_form.md
  mkdocs.yml
Labels: Ready for MERGE

#1329 Symfony reverse proxy
  docs/guide/http_cache.md
Labels: Ready for MERGE

#1332 Extending the Image Editor
  code_samples/back_office/image_editor/assets/random_dot/random-dot-stem.js
  code_samples/back_office/image_editor/assets/random_dot/random-dot.js
  code_samples/back_office/image_editor/config/packages/image_editor.yaml
  code_samples/back_office/image_editor/config/webpack.config.js
  docs/extending/extending_image_editor.md
  mkdocs.yml
Labels: Needs DOC review

#1333 Improve cross-linking
  docs/api/public_php_api_browsing.md
  docs/api/public_php_api_creating_content.md
  docs/api/public_php_api_managing_repository.md
  docs/api/public_php_api_search.md
  docs/guide/admin_panel.md
  docs/guide/basket/calculating_prices.md
  docs/guide/config_back_office.md
  docs/guide/content_rendering.md
  docs/guide/data_migration.md
  docs/guide/permissions.md
  docs/guide/repository/event_reference/other_events.md
  docs/guide/search/search.md
  docs/guide/shop_features/catalog.md
  docs/guide/shop_features/erp.md
  docs/guide/shop_features/payment_and_shipping.md
  docs/guide/shop_features/pricing.md
  docs/guide/shop_features/product_management.md
  docs/guide/shop_features/shop_features.md
  docs/releases/ez_platform_v3.0_deprecations.md
  docs/updating/3_update_app.md
  mkdocs.yml
Labels: Ready for MERGE

#1328 Fix minor tutorial experience issues
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
  docs/tutorials/enterprise_beginner/2_prepare_the_landing_page.md
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  docs/tutorials/enterprise_beginner/img/enterprise_tut_empty_single_block.png
  docs/tutorials/enterprise_beginner/img/enterprise_tut_image_in_article_ct.png
Labels: Needs DOC review

#1330 Commerce: remove mentions of catalog segmentation and newsletter
  docs/guide/data_providers/data_providers.md
  docs/guide/econtent/catalog_segmentation.md
  docs/guide/econtent/econtent_configuration.md
  docs/guide/newsletter/newsletter.md
  docs/guide/newsletter/newsletter_interface.md
  docs/guide/newsletter/newsletter_templates.md
  docs/guide/search/shop_search/search_autosuggest.md
  docs/guide/shop_features/catalog.md
  mkdocs.yml
Labels: Ready for MERGE

#1336 Fix broken product edition badges
  docs/snippets/commerce_badge.md
  docs/snippets/experience_badge.md
Labels: Ready for MERGE

#1334 Clarify mysql and mariadb requirements
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1338 Further theme fixes
  docs/css/custom.css
  docs/css/front-page.css
  theme/main.html
Labels: Ready for MERGE

#1341 EZP-32316: Migration folders and persistence
  docs/guide/data_migration.md
Labels: Ready for MERGE

#1335 Field types structure redesign
  docs/api/field_type_reference.md
  docs/api/field_type_search.md
  docs/api/field_types_reference/authorfield.md
  docs/api/field_types_reference/binaryfilefield.md
  docs/api/field_types_reference/checkboxfield.md
  docs/api/field_types_reference/contentqueryfield.md
  docs/api/field_types_reference/countryfield.md
  docs/api/field_types_reference/dateandtimefield.md
  docs/api/field_types_reference/datefield.md
  docs/api/field_types_reference/emailaddressfield.md
  docs/api/field_types_reference/floatfield.md
  docs/api/field_types_reference/formfield.md
  docs/api/field_types_reference/imageassetfield.md
  docs/api/field_types_reference/imagefield.md
  docs/api/field_types_reference/integerfield.md
  docs/api/field_types_reference/isbnfield.md
  docs/api/field_types_reference/keywordfield.md
  docs/api/field_types_reference/maplocationfield.md
  docs/api/field_types_reference/matrixfield.md
  docs/api/field_types_reference/mediafield.md
  docs/api/field_types_reference/nullfield.md
  docs/api/field_types_reference/pagefield.md
  docs/api/field_types_reference/relationfield.md
  docs/api/field_types_reference/relationlistfield.md
  docs/api/field_types_reference/richtextfield.md
  docs/api/field_types_reference/selectionfield.md
  docs/api/field_types_reference/textblockfield.md
  docs/api/field_types_reference/textlinefield.md
  docs/api/field_types_reference/timefield.md
  docs/api/field_types_reference/urlfield.md
  docs/api/field_types_reference/userfield.md
  docs/api/field_types_reference/xmltextfield.md
  docs/api/graphql_queries.md
  docs/api/public_php_api_creating_content.md
  docs/guide/bundles.md
  docs/guide/controllers.md
  docs/guide/file_management.md
  docs/guide/image_editor.md
  docs/guide/images.md
  docs/guide/search/aggregation_reference.md
  docs/guide/search/solr.md
  docs/guide/twig_functions_reference.md
  docs/migrating/migrating_from_ez_publish.md
  docs/releases/ez_platform_v2.3.md
  docs/releases/ez_platform_v2.4.md
  docs/releases/ez_platform_v2.5.md
  docs/releases/ez_platform_v3.0.md
  mkdocs.yml
Labels: Needs DOC review

#1342 EZEE-3249: Update wishlist templates
  docs/guide/basket/wishlist_and_stored_baskets.md
Labels: Ready for MERGE

#1321 EZP-32321: Added deleteTranslations target to fix 'content/remove'
  docs/guide/permissions.md
Labels: Ready for MERGE

#1340 EZP-32240: Commerce API revision
  docs/api/commerce_api/business_api/baseoperation/addproducts.md
  docs/api/commerce_api/business_api/baseoperation/baseoperation.md
  docs/api/commerce_api/business_api/baseoperation/getbasket.md
  docs/api/commerce_api/business_api/baseoperation/loadproducts.md
  docs/api/commerce_api/business_api/business_api.md
  docs/api/commerce_api/business_api/businessapi_invocation_service.md
  docs/api/commerce_api/field_type_reference/field_type_reference.md
  docs/api/commerce_api/field_type_reference/productselection.md
  docs/api/commerce_api/field_type_reference/sesexternaldata.md
  docs/api/commerce_api/field_type_reference/sesprofiledata.md
  docs/api/commerce_api/field_type_reference/sesselection.md
  docs/api/commerce_api/field_type_reference/silver.module.md
  docs/api/commerce_api/field_type_reference/specificationstype.md
  docs/api/commerce_api/field_type_reference/varianttype.md
  docs/api/commerce_api/fields_for_ecommerce_data/arrayfield.md
  docs/api/commerce_api/fields_for_ecommerce_data/fields_for_ecommerce_data.md
  docs/api/commerce_api/fields_for_ecommerce_data/filefield.md
  docs/api/commerce_api/fields_for_ecommerce_data/imagefield.md
  docs/api/commerce_api/fields_for_ecommerce_data/pricefield.md
  docs/api/commerce_api/fields_for_ecommerce_data/stockfield.md
  docs/api/commerce_api/fields_for_ecommerce_data/textblockfield.md
  docs/api/commerce_api/fields_for_ecommerce_data/textlinefield.md
  docs/api/commerce_api/helper_services/country_service.md
  docs/api/commerce_api/helper_services/ezhelperservice.md
  docs/api/commerce_api/helper_services/mail_logging.md
  docs/api/commerce_api/helper_services/mailhelperservice.md
  docs/api/commerce_api/img/additional_ez_fieldtypes_1.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_10.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_11.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_12.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_13.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_2.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_3.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_6.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_8.png
  docs/api/commerce_api/img/additional_ez_fieldtypes_9.png
  docs/api/commerce_api/img/business_api_1.png
  docs/api/commerce_api/img/fields_for_ecommerce_data_1.png
  docs/api/commerce_api/sisorestapibundle/basket_functions.md
  docs/api/commerce_api/sisorestapibundle/checkout_functions.md
  docs/api/commerce_api/sisorestapibundle/common.md
  docs/api/commerce_api/sisorestapibundle/customer_functions.md
  docs/api/commerce_api/sisorestapibundle/sisorestapibundle.md
  docs/api/field_type_reference.md
  docs/api/field_types_reference/sesexternaldata.md
  docs/api/field_types_reference/sesprofiledata.md
  docs/api/field_types_reference/sesselection.md
  docs/api/field_types_reference/specificationstype.md
  docs/api/field_types_reference/varianttype.md
  docs/api/shop_business_api.md
  docs/guide/catalog/catalog_api/routing_system.md
  docs/guide/catalog/product.md
  docs/guide/logging/logging.md
  docs/guide/pricing/price_api/price_data_model.md
  docs/references.md
  mkdocs.yml
Labels: Ready for MERGE

#1331 Order history revision
  docs/guide/bundles.md
  docs/guide/erp_integration/erp_communication.md
  docs/guide/img/orderhistory.png
  docs/guide/img/orderhistory_detail.png
  docs/guide/img/orderhistory_invoice.png
  docs/guide/order_history/displaying_custom_column.md
  docs/guide/order_history/order_history.md
  docs/guide/order_history/order_history_configuration.md
  docs/guide/order_history/order_history_features/orderhistory_erp_messages.md
  docs/guide/order_history/order_history_features/orderhistory_local_orders.md
  docs/guide/order_history/order_history_local_orders.md
  docs/guide/order_history/order_history_templates.md
  docs/guide/order_history/orderhistory.md
  docs/guide/order_history/orderhistory_api.md
  docs/guide/order_history/orderhistory_configuration.md
  docs/guide/order_history/orderhistory_templates.md
  docs/guide/order_history/overriding_semantic_configuration.md
  mkdocs.yml
Labels: Ready for MERGE
