Repository ibexa/documentation-developer, pull requests merged in 2021-05, with the labels that each got.

#1364 Improve linking
  docs/community_resources/support_maintenance_faq.md
  docs/guide/shop_features/catalog.md
  docs/migrating/migrating_from_ez_publish_platform.md
Labels: Ready for MERGE

#1356 Forgot password option
  docs/guide/user_management/user_management.md
Labels: Ready for MERGE

#1347 EZEE-3003: Database update script
  docs/updating/5_update_2.5.md
  docs/updating/5_update_3.2.md
  docs/updating/updating_to_3.3.md
Labels: Ready for MERGE

#1368 Update to v3.3: added enable commerce features
  docs/updating/updating_to_3.3.md
Labels: Ready for MERGE

#1361 IBX-180: Template and basic content rendering revision
  code_samples/front/render_content/config/packages/views.yaml
  code_samples/front/render_content/templates/themes/my_theme/fields/author.html.twig
  code_samples/front/render_content/templates/themes/my_theme/full/article.html.twig
  code_samples/front/render_content/templates/themes/my_theme/pagelayout.html.twig
  code_samples/front/render_page/config/packages/ezplatform_page_fieldtype.yaml
  code_samples/front/render_page/config/packages/views.yaml
  code_samples/front/render_page/templates/themes/my_theme/blocks/contentlist.html.twig
  code_samples/front/render_page/templates/themes/my_theme/layouts/sidebar.html.twig
  docs/api/field_types_reference/pagefield.md
  docs/api/public_php_api_browsing.md
  docs/api/public_php_api_search.md
  docs/extending/drag_and_drop.md
  docs/extending/import_assets_from_bundle.md
  docs/guide/content_rendering.md
  docs/guide/content_rendering/assets.md
  docs/guide/content_rendering/design_engine/design_engine.md
  docs/guide/content_rendering/render_content/render_content.md
  docs/guide/content_rendering/render_content/render_page.md
  docs/guide/content_rendering/templates/template_configuration.md
  docs/guide/content_rendering/templates/templates.md
  docs/guide/content_rendering/templates/view_matcher_reference.md
  docs/guide/content_rendering/twig_function_reference/content_twig_functions.md
  docs/guide/controllers.md
  docs/guide/displaying_children_of_a_content_item.md
  docs/guide/page_rendering.md
  docs/guide/project_organization.md
  docs/guide/retrieving_root_location.md
  docs/guide/templates.md
  docs/guide/user_management/user_management.md
  docs/index.md
  docs/migrating/migrating_from_ez_publish.md
  docs/references.md
  docs/snippets/rendering_dump_variable.md
  docs/tutorials/enterprise_beginner/2_prepare_the_landing_page.md
  docs/tutorials/platform_beginner/3_customize_the_front_page.md
  mkdocs.yml
Labels: Ready for MERGE

#1362 EZEE-3499: Update vcl configuration for Fastly
  docs/updating/5_update_2.5.md
  docs/updating/5_update_3.2.md
Labels: Ready for MERGE

#1365 Combine supported and recommended requirements
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1373 IBX-118: Create reusable Commerce JS components
  docs/guide/basket/wishlist_and_stored_baskets.md
  docs/guide/product_comparison/product_comparison_templates.md
  docs/guide/quick_order/quick_order_templates.md
Labels: Ready for MERGE

#1378 IBX-322: Send email notifications from Form Builder 2.5
  docs/guide/extending/extending_form_builder.md
  docs/guide/extending/img/email_notification.png
Labels: Ready for MERGE

#1376 IBX-322: Send email notifications from Form Builder
  docs/extending/extending_form_builder.md
  docs/extending/img/email_notification.png
Labels: Ready for MERGE

#1371 IBX-297: Allow random sorting in ES
  docs/guide/search/sort_clause_reference/random_sort_clause.md
Labels: Ready for MERGE

#1381 RN link absolutization
  docs/releases/ez_platform_v1.10.0.md
  docs/releases/ez_platform_v1.11.0.md
  docs/releases/ez_platform_v1.12.0.md
  docs/releases/ez_platform_v1.13.0_lts.md
  docs/releases/ez_platform_v1.7.0_lts.md
  docs/releases/ez_platform_v1.8.0.md
  docs/releases/ez_platform_v1.9.0.md
  docs/releases/ez_platform_v2.0.0.md
  docs/releases/ez_platform_v2.1.0.md
  docs/releases/ez_platform_v2.2.0.md
  docs/releases/ez_platform_v2.3.md
  docs/releases/ez_platform_v2.4.md
  docs/releases/ez_platform_v2.5.md
  docs/releases/ez_platform_v3.0.md
  docs/releases/ez_platform_v3.0_deprecations.md
  docs/releases/ez_platform_v3.1.md
  docs/releases/ibexa_dxp_v3.2.md
  docs/releases/ibexa_dxp_v3.3.md
Labels: Needs DOC review

#1369 IBX-323 - Extending Solr
  code_samples/search/solr/config/packages/services.yaml
  code_samples/search/solr/src/FieldMapper/WebinarEventTitleFulltextFieldMapper.php
  code_samples/search/solr/src/Query/Aggregation/PriorityAggregationResultExtractor.php
  code_samples/search/solr/src/Query/Aggregation/PriorityRangeAggregation.php
  code_samples/search/solr/src/Query/Aggregation/PriorityRangeAggregationVisitor.php
  code_samples/search/solr/src/Query/Criterion/CameraManufacturerCriterion.php
  code_samples/search/solr/src/Query/Criterion/CameraManufacturerVisitor.php
  code_samples/search/solr/src/Query/SortClause/ScoreSortClause.php
  code_samples/search/solr/src/Query/SortClause/ScoreVisitor.php
  docs/guide/search/extend_solr.md
  docs/guide/search/solr.md
  mkdocs.yml
Labels: Needs DOC review

#1380 Branding updates to security issue reporting
  docs/guide/reporting_issues.md
Labels: Ready for MERGE

#1372 IBX-150: Schedule block snapshots
  docs/guide/config_repository.md
Labels: Ready for MERGE

#1370 IBX-181: Rewrite query and controller documentation
  code_samples/front/custom_query_type/config/packages/views.yaml
  code_samples/front/custom_query_type/src/QueryType/LatestContentQueryType.php
  code_samples/front/custom_query_type/src/QueryType/OptionsBasedLatestContentQueryType.php
  code_samples/front/embed_content/config/packages/views.yaml
  code_samples/front/embed_content/src/Controller/RelationController.php
  code_samples/front/embed_content/templates/themes/my_theme/full/article.html.twig
  code_samples/front/embed_content/templates/themes/my_theme/full/blog_post.html.twig
  code_samples/front/list_content/config/packages/views.yaml
  code_samples/front/list_content/templates/themes/my_theme/full/blog_post.html.twig
  code_samples/front/list_content/templates/themes/my_theme/full/folder.html.twig
  code_samples/front/query_pagination/config/packages/views.yaml
  code_samples/front/query_pagination/templates/themes/my_theme/full/folder.html.twig
  docs/api/field_types_reference/contentqueryfield.md
  docs/extending/richtext_block.md
  docs/getting_started/first_steps.md
  docs/guide/architecture.md
  docs/guide/configuration.md
  docs/guide/content_rendering/embed_and_list_content/embed_content.md
  docs/guide/content_rendering/embed_and_list_content/list_content.md
  docs/guide/content_rendering/queries_and_controllers/built-in_query_types.md
  docs/guide/content_rendering/queries_and_controllers/content_queries.md
  docs/guide/content_rendering/queries_and_controllers/controllers.md
  docs/guide/content_rendering/queries_and_controllers/custom_query_type.md
  docs/guide/content_rendering/templates/template_configuration.md
  docs/guide/content_rendering/twig_function_reference/content_twig_functions.md
  docs/guide/img/content_query_field_definition.png
  docs/guide/multisite.md
  docs/releases/ez_platform_v1.11.0.md
  docs/releases/ez_platform_v3.0.md
  docs/releases/ibexa_dxp_v3.2.md
  docs/releases/ibexa_dxp_v3.3.md
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
  docs/updating/5_update_2.2.md
  mkdocs.yml
Labels: Ready for MERGE

#1375 Namespace fix
  docs/community_resources/package_structure.md
Labels: Needs DOC review

#1385 IBX-182: Document templating layout parts
  code_samples/front/layouts/breadcrumbs/src/Controller/BreadcrumbController.php
  code_samples/front/layouts/breadcrumbs/templates/themes/my_theme/pagelayout.html.twig
  code_samples/front/layouts/breadcrumbs/templates/themes/my_theme/parts/breadcrumbs.html.twig
  code_samples/front/layouts/menu/src/Menu/MenuBuilder.php
  code_samples/front/layouts/menu/src/QueryType/MenuQueryType.php
  code_samples/front/layouts/menu/templates/themes/my_theme/pagelayout.html.twig
  code_samples/front/layouts/menu/templates/themes/my_theme/pagelayout_menu.html.twig
  code_samples/front/shop/override_navigation/config/packages/design.yaml
  code_samples/front/shop/override_navigation/templates/themes/my_theme/Navigation/left_menu.html.twig
  docs/guide/content_rendering/layout/add_breadcrumbs.md
  docs/guide/content_rendering/layout/add_menu.md
  docs/guide/content_rendering/layout/add_search_form.md
  docs/guide/content_rendering/layout/customize_basket.md
  docs/guide/content_rendering/templates/overriding_shop_templates.md
  docs/guide/content_rendering/twig_function_reference/content_twig_functions.md
  mkdocs.yml
Labels: Ready for MERGE

#1367 Update to v3.3.x
  docs/updating/updating_to_3.3.md
Labels: QA approved, Ready for MERGE

#1388 Add note about Composer version in update guide
  docs/updating/updating_to_3.3.md
Labels: Ready for MERGE

#1386 IBX-281: Enable binary file fields indexing
  docs/guide/file_management.md
Labels: Ready for MERGE

#1382 Fix adding credentials to installation procedure
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE
