Repository ibexa/documentation-developer, pull requests merged in 2021-08, with the labels that each got.

#1432 IBX-833: As a Developer I want to configure CSRF validation in REST e…
  docs/api/extending_the_rest_api.md
Labels: Ready for MERGE

#1430 IBX-704: LocationChildrenTermAggregation
  docs/guide/search/aggregation_reference.md
  docs/guide/search/aggregation_reference/locationchildrenterm_aggregation.md
  mkdocs.yml
Labels: Ready for MERGE

#1428 IBX-525: Provide list of all available routes
  docs/guide/content_rendering/urls_and_routes.md
Labels: Ready for MERGE

#1424 IBX-368: Image normalization command
  docs/guide/images.md
  docs/migrating/common_issues.md
Labels: Ready for MERGE

#1436 Remove Shop features section
  docs/guide/shop_features/catalog.md
  docs/guide/shop_features/erp.md
  docs/guide/shop_features/img/addresses.png
  docs/guide/shop_features/img/catalog_categories_and_products.png
  docs/guide/shop_features/img/comparison_list.png
  docs/guide/shop_features/img/manage_addresses.png
  docs/guide/shop_features/img/price_mgmt.png
  docs/guide/shop_features/img/price_providers.png
  docs/guide/shop_features/img/product_catalog_2.png
  docs/guide/shop_features/img/product_detail.png
  docs/guide/shop_features/img/quickorder.png
  docs/guide/shop_features/img/quickorder_upload.png
  docs/guide/shop_features/img/registration_advanced.png
  docs/guide/shop_features/img/stock_info_in_basket.png
  docs/guide/shop_features/img/stock_management.png
  docs/guide/shop_features/img/stored_basket.png
  docs/guide/shop_features/img/user_information.png
  docs/guide/shop_features/img/wishlist.png
  docs/guide/shop_features/payment_and_shipping.md
  docs/guide/shop_features/pricing.md
  docs/guide/shop_features/product_management.md
  docs/guide/shop_features/shop_features.md
  docs/guide/shop_features/user_management.md
  mkdocs.yml
Labels: Ready for MERGE

#1437 richtext update doc fix
  docs/releases/ez_platform_v3.0_deprecations.md
Labels: Ready for MERGE

#1429 IBX-822: Docbook format
  docs/api/field_types_reference/richtextfield.md
  docs/api/public_php_api_creating_content.md
Labels: Ready for MERGE

#1433 IBX-154: Optional alt text requirement for Image FT
  docs/api/field_types_reference/imagefield.md
  docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
Labels: Needs DOC review

#1440 IBX-766: Diagrams rebranding
  docs/api/img/create_content_sequence.png
  docs/api/img/diagrams_source/create_content_sequence.xml
  docs/api/img/diagrams_source/field_type_overview.xml
  docs/api/img/diagrams_source/load_content_sequence.xml
  docs/api/img/diagrams_source/publish_content_sequence.xml
  docs/api/img/diagrams_source/update_content_sequence.xml
  docs/api/img/field_type_overview.png
  docs/api/img/load_content_sequence.png
  docs/api/img/publish_content_sequence.png
  docs/api/img/update_content_sequence.png
  docs/guide/img/architecture.png
  docs/guide/img/config_content_structure.png
  docs/guide/img/content_model_diagram.png
  docs/guide/img/content_model_item_diagram.png
  docs/guide/img/content_model_type_diagram.png
  docs/guide/img/diagram_source/config_content_structure.xml
  docs/guide/img/diagram_source/content_model_diagram.xml
  docs/guide/img/diagram_source/content_model_item_diagram.xml
  docs/guide/img/diagram_source/content_model_type_diagram.xml
  docs/guide/img/diagram_source/full_content_export.xml
  docs/guide/img/diagram_source/incremental_content_export.xml
  docs/guide/img/diagram_source/locations_visibility.xml
  docs/guide/img/diagram_source/node_visibility_hide.xml
  docs/guide/img/diagram_source/node_visibility_hide_invisible.xml
  docs/guide/img/diagram_source/node_visibility_unhide1.xml
  docs/guide/img/diagram_source/node_visibility_unhide2.xml
  docs/guide/img/diagram_source/organising_templates.xml
  docs/guide/img/diagram_source/server_setup.xml
  docs/guide/img/diagram_source/signal_slots_diagram.xml
  docs/guide/img/diagram_source/spi_cache.xml
  docs/guide/img/diagram_source/subtree_usability_notes_1.xml
  docs/guide/img/diagram_source/subtree_usability_notes_2.xml
  docs/guide/img/diagram_source/~$ganising_templates.xml
  docs/guide/img/full_content_export.png
  docs/guide/img/incremental_content_export.png
  docs/guide/img/locations_visibility.png
  docs/guide/img/node_visibility_hide.png
  docs/guide/img/node_visibility_hide_invisible.png
  docs/guide/img/node_visibility_unhide1.png
  docs/guide/img/node_visibility_unhide2.png
  docs/guide/img/organising_templates.png
  docs/guide/img/server_setup.png
  docs/guide/img/signal_slots_diagram.png
  docs/guide/img/spi_cache.png
  docs/guide/img/subtree_usability_notes_1.png
  docs/guide/img/subtree_usability_notes_2.png
  docs/tutorials/enterprise_beginner/img/diagram_source/enterprise_tut_file_structure.xml
  docs/tutorials/enterprise_beginner/img/enterprise_tut_file_structure.png
  docs/tutorials/platform_beginner/img/bike_tutorial_listing_web_v3.png
  docs/tutorials/platform_beginner/img/diagram_source/bike_tutorial_listing_web_v3.xml
  docs/updating/img/diagram_source/folder_structure_v3.xml
  docs/updating/img/folder_structure_v3.png
Labels: Ready for MERGE

#1431 Add warning about SSL with different SA domains
  docs/guide/multisite/multisite_configuration.md
Labels: Ready for MERGE

#1425 PhpStorm plugin
  docs/community_resources/img/phpstorm_plugin_create_project.png
  docs/community_resources/img/phpstorm_plugin_file_template.png
  docs/community_resources/img/phpstorm_plugin_intention.png
  docs/community_resources/phpstorm_plugin.md
  mkdocs.yml
Labels: Special case (see comments), Ready for MERGE
