Repository ibexa/documentation-developer, pull requests merged in 2021-09, with the labels that each got.

#1449 Redis cache clear 3.3.x
  docs/updating/updating_to_3.3.md
Labels: Needs DOC review

#1434 IBX-810: Extendable repository configuration
  docs/guide/config_repository.md
  docs/guide/multisite/siteaccess_aware_configuration.md
Labels: Special case (see comments), Ready for MERGE

#1441 Page extensibility revision
  code_samples/page/custom_attribute/config/packages/page_blocks.yaml
  code_samples/page/custom_attribute/src/Block/Attribute/MyStringAttributeMapper.php
  code_samples/page/custom_attribute/src/Block/Attribute/MyStringAttributeType.php
  code_samples/page/custom_block_validator/config/packages/page_blocks.yaml
  code_samples/page/custom_block_validator/src/Validator/AlphaOnly.php
  code_samples/page/custom_block_validator/src/Validator/AlphaOnlyValidator.php
  code_samples/page/custom_page_block/config/packages/page_blocks.yaml
  code_samples/page/custom_page_block/templates/themes/standard/blocks/event/config.html.twig
  code_samples/page/custom_page_block/templates/themes/standard/blocks/event/featured_template.html.twig
  code_samples/page/custom_page_block/templates/themes/standard/blocks/event/template.html.twig
  code_samples/page/page_listener/config/packages/page_blocks.yaml
  code_samples/page/page_listener/src/Block/Listener/MyBlockListener.php
  code_samples/page/page_listener/templates/my_block.html.twig
  docs/api/field_types_reference/pagefield.md
  docs/extending/extending_page.md
  docs/extending/img/extending_example_page_block.png
  docs/extending/richtext_block.md
  docs/guide/cache/http_cache_config.md
  docs/guide/content_rendering/render_content/render_page.md
  docs/guide/page/create_custom_page_block.md
  docs/guide/page/page_block_attributes.md
  docs/guide/page/page_block_validators.md
  docs/guide/page/page_blocks.md
  docs/guide/repository/event_reference/page_events.md
  docs/updating/5_update_2.2.md
  mkdocs.yml
Labels: Ready for MERGE

#1452 adapt the name of the file to delete to the one really provided
  docs/getting_started/first_steps.md
Labels: Ready for MERGE

#1450 IBX-815: Workflow extensibility revision
  code_samples/workflow/custom_workflow/config/custom_services.yaml
  code_samples/workflow/custom_workflow/config/packages/workflows.yaml
  code_samples/workflow/custom_workflow/src/EventListener/ApprovedTransitionListener.php
  code_samples/workflow/custom_workflow/src/EventListener/LegalTransitionListener.php
  docs/api/public_php_api_managing_repository.md
  docs/extending/extending_workflow.md
  docs/extending/img/extending_workflow_proofreading.png
  docs/guide/img/workflow_custom_diagram.png
  docs/guide/img/workflow_notification.png
  docs/guide/img/workflow_panel.png
  docs/guide/img/workflow_reviewers.png
  docs/guide/permissions.md
  docs/guide/workflow.md
  docs/guide/workflow/add_custom_workflow_action.md
  docs/guide/workflow/workflow.md
  docs/updating/4_6_upgrade_workflow.md
  mkdocs.yml
Labels: Ready for MERGE

#1439 Improve code highlight
  docs/css/codehilite.css
  docs/css/custom.css
  mkdocs.yml
  requirements.txt
Labels: Ready for MERGE

#1451 IBX-815: Form builder extensibility revision
  code_samples/forms/custom_form_field/config/custom_services.yaml
  code_samples/forms/custom_form_field/config/packages/form_builder.yaml
  code_samples/forms/custom_form_field/src/EventSubscriber/FormFieldDefinitionSubscriber.php
  code_samples/forms/custom_form_field/src/FormBuilder/Field/Mapper/CountryFieldMapper.php
  docs/api/field_types_reference/formfield.md
  docs/extending/extending_form_builder.md
  docs/extending/img/extending_form_builder_country_field.png
  docs/extending/img/extending_form_builder_custom_form_fields.png
  docs/guide/cache/symfony_reverse_proxy.md
  docs/guide/form_builder/create_custom_form_field.md
  docs/guide/form_builder/customize_email_notifications.md
  docs/guide/form_builder/forms.md
  docs/guide/img/email_notification.png
  docs/guide/img/extending_form_builder_captcha_default.png
  docs/guide/img/extending_form_builder_captcha_result.png
  docs/guide/img/extending_form_builder_country_field.png
  docs/guide/img/extending_form_builder_custom_form_fields.png
  docs/tutorials/enterprise_beginner/5_create_newsletter_form.md
  mkdocs.yml
Labels: Ready for MERGE

#1454 IBX-431: Allowed to lock & unlock drafts in workflow
  docs/guide/limitation_reference.md
  docs/guide/limitations.md
  docs/guide/permissions.md
  docs/guide/workflow/workflow.md
Labels: Needs DEV review

#1455 IBX-813: Back Office extensibility
  code_samples/back_office/calendar/config/custom_services.yaml
  code_samples/back_office/calendar/config/packages/calendar.yaml
  code_samples/back_office/calendar/src/Calendar/Holidays/Event.php
  code_samples/back_office/calendar/src/Calendar/Holidays/EventSourceFactory.php
  code_samples/back_office/calendar/src/Calendar/Holidays/EventType.php
  code_samples/back_office/calendar/src/Calendar/Holidays/holidays.json
  code_samples/back_office/dashboard/article_tab/config/custom_services.yaml
  code_samples/back_office/dashboard/article_tab/config/services.yaml
  code_samples/back_office/dashboard/article_tab/src/Tab/Dashboard/Everyone/EveryoneArticleTab.php
  code_samples/back_office/menu/menu_item/config/custom_routes.yaml
  code_samples/back_office/menu/menu_item/src/Controller/AllContentListController.php
  code_samples/back_office/menu/menu_item/src/EventSubscriber/MyMenuSubscriber.php
  code_samples/back_office/menu/menu_item/templates/list/all_content_list.html.twig
  code_samples/back_office/menu/remove_menu_item/src/EventListener/RemoveCommerceMenuListener.php
  code_samples/back_office/settings/config/custom_services.yaml
  code_samples/back_office/settings/config/packages/user_settings.yaml
  code_samples/back_office/settings/src/Setting/Unit.php
  code_samples/back_office/settings/templates/User/Setting/update_unit.html.twig
  docs/extending/add_user_setting.md
  docs/extending/customize_calendar.md
  docs/extending/customizing_calendar.md
  docs/extending/extending_dashboard.md
  docs/extending/extending_menus.md
  docs/extending/extending_settings.md
  docs/extending/extending_tabs.md
  docs/extending/img/extending_calendar_list_view.png
  docs/extending/img/extending_calendar_view.png
  docs/extending/img/extending_custom_tab.png
  docs/extending/menus/add_menu_item.md
  docs/extending/menus/back_office_menus.md
  docs/extending/tabs/add_dashboard_tab.md
  docs/extending/tabs/back_office_tabs.md
  docs/tutorials/extending_admin_ui/1_creating_a_dashboard_tab.md
  docs/updating/4_7_upgrade_extensions.md
  mkdocs.yml
Labels: Ready for MERGE

#1457 Disabling the QR workflow
  code_samples/workflow/custom_workflow/config/packages/workflows.yaml
  docs/guide/workflow/workflow.md
Labels: Needs DOC review

#1460 Fix js error when no menu
  docs/js/custom.js
Labels: Ready for MERGE

#1456 IBX-972: ImageAsset and ContentTypeGroupLimition doesn't work for already created content
  docs/updating/updating_to_3.3.md
Labels: Ready for MERGE
