Repository ibexa/documentation-developer, pull requests merged in 2022-11, with the labels that each got.

#1797 Fix broken links in older release notes
  docs/release_notes/ez_platform_v1.10.0.md
  docs/release_notes/ez_platform_v1.11.0.md
  docs/release_notes/ez_platform_v1.12.0.md
  docs/release_notes/ez_platform_v1.13.0_lts.md
  docs/release_notes/ez_platform_v1.7.0_lts.md
  docs/release_notes/ez_platform_v1.8.0.md
  docs/release_notes/ez_platform_v1.9.0.md
  docs/release_notes/ibexa_dxp_v4.0.md
  docs/release_notes/ibexa_dxp_v4.1.md
  docs/release_notes/ibexa_dxp_v4.2.md
Labels: Ready for MERGE

#1796 IBX-2762 Added base unit configuration
  docs/content_management/field_types/field_type_reference/measurementfield.md
Labels: Ready for MERGE

#1794 IBX-3549: Taxonomy PHP API
  code_samples/api/public_php_api/src/Command/TaxonomyCommand.php
  docs/content_management/taxonomy/taxonomy_api.md
  mkdocs.yml
Labels: Ready for MERGE

#1802 Fix links in PHP API
  docs/api/php_api/php_api.md
Labels: Needs DOC review

#1804 IBX-4276: Command to revoke user passwords
  docs/users/user_management.md
Labels: Ready for MERGE

#1803 Update update guides for 4.2.3, 3.3.28 and 2.5.31 patch releases
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
  mkdocs.yml
Labels: Ready for MERGE

#1780 Release Notes v4.3
  docs/index.md
  docs/release_notes/ibexa_dxp_v4.3.md
  docs/release_notes/img/4.3_collection_dnd.png
  docs/release_notes/img/4.3_edit_product_price.png
  docs/release_notes/img/4.3_self_registration.png
  docs/release_notes/release_notes.md
  mkdocs.yml
Labels: Ready for MERGE

#1805 Fix link to "Update from v4.2.x to v4.3"
  docs/release_notes/ibexa_dxp_v4.3.md
Labels: Ready for MERGE

#1806 fixed db update mysql/postgres
  docs/update_and_migration/from_4.1/update_from_4.1.md
  docs/update_and_migration/from_4.2/update_from_4.2.md
Labels: Ready for MERGE

#1786 IBX-3063 Certify Debian 11 - MOVED to v4.4
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1800 Added note to update about Open Source database update
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.0/to_4.1.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
Labels: Ready for MERGE

#1789 IBX-3944: Reorganized personalization section
  docs/personalization/api_reference/api_reference.md
  docs/personalization/api_reference/content_api.md
  docs/personalization/api_reference/recommendation_api.md
  docs/personalization/api_reference/tracking_api.md
  docs/personalization/api_reference/user_api.md
  docs/personalization/attribute_search_in_elasticsearch.md
  docs/personalization/enable_personalization.md
  docs/personalization/how_it_works.md
  docs/personalization/importing_historical_user_tracking_data.md
  docs/personalization/integrate_recommendation_service.md
  docs/personalization/legacy_recommendation_api.md
  docs/personalization/personalization.md
  docs/personalization/recommendation_integration.md
  docs/personalization/tracking_integration.md
  docs/personalization/tracking_with_yct.md
  mkdocs.yml
  plugins.yml
Labels: Needs DOC review

#1810 Corporate Portal migration update
  docs/update_and_migration/from_4.2/update_from_4.2.md
Labels: Ready for MERGE

#1809 IBX-3863: Configuration HTTP Client for Solr queries added
  docs/search/solr_search_engine.md
Labels: Ready for MERGE

#1811 IBX-3863: Configuration HTTP Client for Solr queries added in v3.3
  docs/guide/search/solr.md
Labels: Needs DOC review, Needs DEV review

#1814 Update password hash type caution box
  docs/content_management/field_types/field_type_reference/userfield.md
Labels: Ready for MERGE

#1813 IBX-3135: Updated missing components
  docs/administration/back_office/back_office_elements/reusable_components.md
Labels: Ready for MERGE

#1750 Replace ez with ibexa in solr commands
  docs/search/solr_search_engine.md
Labels: Ready for MERGE

#1815 Enable PHP zend.exception_ignore_args
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE
