Repository ibexa/documentation-developer, pull requests merged in 2022-03, with the labels that each got.

#1541 IBX-2404: Tables' headers' text is hardly visible
  docs/css/custom.css
Labels: Ready for MERGE

#1545 IBX-2325: Product catalog migrations
  docs/guide/data_migration.md
  docs/guide/data_migration/exporting_and_importing_data.md
Labels: Ready for MERGE

#1546 IBX-381: Image optimization libraries
  docs/guide/image_editor.md
  docs/guide/images.md
Labels: Ready for MERGE

#1539 IBX-2352: Document how to set trusted_proxies when using Fastly
  docs/guide/cache/symfony_reverse_proxy.md
Labels: Ready for MERGE

#1547 IBX-1868: Added information about reference and supplement the missing information
  docs/guide/data_migration/data_migration.md
  docs/guide/data_migration/data_migration_actions.md
  docs/guide/data_migration/exporting_and_importing_data.md
  docs/guide/data_migration/migration_management.md
Labels: Needs DOC review

#1448 Improve HTTP-Cache doc
  docs/guide/cache/content_aware_cache.md
Labels: Needs DOC review

#1554 IBX-2521: Add missing fonts - Noto Sans and Work Sans variants
  docs/css/custom.css
  docs/fonts/Noto_Sans/NotoSans-SemiBold.ttf
  docs/fonts/Noto_Sans/NotoSans-SemiBoldItalic.ttf
  docs/fonts/Work_Sans/WorkSans-SemiBold.ttf
Labels: Ready for MERGE

#1561 Cache tags rebranding
  docs/guide/persistence_cache.md
Labels: Ready for MERGE

#1560 IBX-381: Image optimization libraries - add to requirements
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1555 Catalog migrations: new modes and criteria
  docs/guide/data_migration/exporting_and_importing_data.md
Labels: Ready for MERGE

#1553 IBX-2301: Added configuration to enable translations from i18n package
  docs/guide/back_office_translations.md
Labels: Ready for MERGE

#1562 Added information about translations provided by ibexa/i18n package
  docs/guide/back_office_translations.md
Labels: Ready for MERGE

#1563 Updated information about community translations
  docs/community_resources/translations.md
Labels: Ready for MERGE

#1564 Reorder steps for 3.3 update
  docs/updating/from_2.5/to_3.3.latest.md
  docs/updating/from_2.5/to_3.3.md
  docs/updating/from_2.5/update_from_2.5.md
  docs/updating/from_3.3/to_4.0.md
  docs/updating/from_3.3/update_from_3.3.md
Labels: Ready for MERGE

#1570 Switching flex server in 3.3 update
  docs/updating/from_3.3/update_from_3.3.md
Labels: Ready for MERGE

#1556 IBX-23: Taxonomy
  code_samples/taxonomy/config/packages/ibexa_taxonomy.yaml
  docs/guide/taxonomy/taxonomy.md
  mkdocs.yml
Labels: Ready for MERGE

#1549 IBX-2330: Added remoteid in user tracker
  docs/guide/personalization/recommendation_client.md
Labels: Ready for MERGE

#1565 IBX-2336 documented: "Move VCL macro call"
  docs/snippets/update/vcl_configuration_for_fastly.md
  docs/updating/from_1.x_2.x/update_db_to_2.5.md
  docs/updating/from_2.5/to_3.3.latest.md
  docs/updating/from_3.3/update_from_3.3.md
Labels: Needs DEV review

#1550 IBX-2332: Updated paramaters added remoteId support
  docs/guide/personalization/recommendation_client.md
Labels: Ready for MERGE

#1572 IBX-2332: Added remoteid supported
  docs/guide/personalization/recommendation_client.md
Labels: Ready for MERGE

#1492 GraphQL location handling
  docs/api/graphql.md
  docs/api/graphql_customization.md
  docs/api/graphql_queries.md
Labels: Ready for MERGE

#1569 IBX-2558: Data migration examples
  code_samples/data_migration/examples/create_attribute_group.yaml
  code_samples/data_migration/examples/create_blog_post_ct.yaml
  code_samples/data_migration/examples/create_currency.yaml
  code_samples/data_migration/examples/create_customer_group.yaml
  code_samples/data_migration/examples/create_language.yaml
  code_samples/data_migration/examples/create_parent_and_child_content.yaml
  code_samples/data_migration/examples/create_product_type.yaml
  code_samples/data_migration/examples/create_role.yaml
  code_samples/data_migration/examples/create_user.yaml
  docs/guide/data_migration/add_data_migration_matcher.md
  docs/guide/data_migration/data_migration.md
  docs/guide/data_migration/exporting_data.md
  docs/guide/data_migration/importing_data.md
  mkdocs.yml
Labels: Ready for MERGE

#1544 IBX-2325: Expand new product catalog documentation
  docs/api/public_php_api_search.md
  docs/guide/catalog/catalog.md
  docs/guide/catalog/catalog_configuration.md
  docs/guide/content_rendering/templates/view_matcher_reference.md
  docs/guide/content_rendering/twig_function_reference/product_twig_functions.md
  docs/guide/repository/event_reference/catalog_events.md
  docs/guide/search/criteria_reference/customergroupid_criterion.md
  docs/guide/search/search_criteria_reference.md
  docs/guide/search/sort_clause_reference.md
  mkdocs.yml
Labels: Ready for MERGE

#1552 Custom product Content Type clarification
  docs/guide/catalog/product.md
Labels: Ready for MERGE

#1537 IBX-1784: Translation based HTTP Cache invalidation
  docs/updating/from_3.3/update_from_3.3.md
Labels: Ready for MERGE
