Repository ibexa/documentation-developer, pull requests merged in 2022-08, with the labels that each got.

#1686 Restructuring of the provided example
  docs/extending/creating_custom_dropdowns.md
Labels: Ready for MERGE

#1687 Add and amend alert options
  docs/extending/reusable_back_office_templates.md
Labels: Ready for MERGE

#1688 drag and drop - Provide function definition
  docs/extending/drag_and_drop.md
Labels: Ready for MERGE

#1698 CreatedAt(Range) and ProductCategory Criteria
  docs/guide/search/criteria_reference/createdat_criterion.md
  docs/guide/search/criteria_reference/createdatrange_criterion.md
  docs/guide/search/criteria_reference/productcategory_criterion.md
  docs/guide/search/criteria_reference/search_criteria_reference.md
  mkdocs.yml
Labels: Ready for MERGE

#1680 IBX-2854: Product variants and assets
  docs/guide/catalog/catalog.md
  docs/guide/repository/event_reference/catalog_events.md
Labels: Ready for MERGE

#1689 Fix not rendered icon and add example to override specific contenttype
  docs/extending/extending_thumbnails.md
Labels: Needs DOC review

#1693 Update PR template with checklist
  .github/pull_request_template.md
Labels: Ready for MERGE

#1694 Fix and expand update guide
  docs/updating/from_1.x_2.x/update_app_to_2.5.md
  docs/updating/from_1.x_2.x/update_db_to_2.5.md
  docs/updating/from_1.x_2.x/update_from_1.x_2.x.md
  docs/updating/from_2.5/to_3.3.latest.md
  docs/updating/from_2.5/to_3.3.md
  docs/updating/from_2.5/update_from_2.5.md
  docs/updating/from_3.3/to_4.0.md
  docs/updating/from_3.3/update_from_3.3.md
  docs/updating/from_4.0/to_4.1.md
  docs/updating/from_4.1/update_from_4.1.md
  docs/updating/update_ibexa_dxp.md
  mkdocs.yml
Labels: Ready for MERGE

#1705 Product codes
  docs/guide/catalog/catalog.md
  docs/guide/catalog/catalog_configuration.md
Labels: Ready for MERGE

#1703 EZEE-3357 - Migration exception fix
  docs/migrating/migrating_from_ez_publish.md
  docs/updating/from_1.x_2.x/update_db_to_2.5.md
Labels: Ready for MERGE

#1677 Catalogs
  code_samples/front/shop/list_products_in_catalog/config/custom_routes.yaml
  code_samples/front/shop/list_products_in_catalog/src/Controller/PromoController.php
  code_samples/front/shop/list_products_in_catalog/templates/themes/standard/full/promo.html.twig
  docs/guide/catalog/catalog.md
  docs/guide/content_rendering/embed_and_list_content/list_products_in_catalog.md
  docs/guide/content_rendering/queries_and_controllers/built-in_query_types.md
  docs/guide/img/catalog_query_type_field.png
  docs/guide/img/catalogs_filters.png
  docs/guide/permissions.md
  docs/guide/repository/event_reference/catalog_events.md
  mkdocs.yml
Labels: Ready for MERGE

#1708 Link removal, as the doc is not published yet
  docs/releases/ibexa_dxp_v4.2.md
Labels: Ready for MERGE

#1711 Proofing - badge update
  docs/releases/ibexa_dxp_v4.2.md
Labels: Ready for MERGE

#1713 Missing features for 4.2
  docs/releases/ibexa_dxp_v4.2.md
  docs/releases/img/4.2_address_field_type.png
  docs/releases/img/4.2_content_edit_tabs.png
Labels: Ready for MERGE

#1701 4.2 update guide
  docs/updating/from_4.1/update_from_4.1.md
  mkdocs.yml
Labels: Ready for QA, Ready for MERGE

#1716 Added product categories to upgrade doc
  docs/updating/from_4.1/update_from_4.1.md
Labels: Ready for MERGE

#1718 Measurement search criteria
  docs/guide/search/criteria_reference/rangemeasurementattributemaximum_criterion.md
  docs/guide/search/criteria_reference/rangemeasurementattributeminimum_criterion.md
  docs/guide/search/criteria_reference/search_criteria_reference.md
  docs/guide/search/criteria_reference/simplemeasurementattribute_criterion.md
  mkdocs.yml
Labels: Ready for MERGE

#1717 Update screenshots for 4.2
  docs/api/img/extending_field_type_create.png
  docs/api/img/extending_field_type_definition.png
  docs/api/img/extending_field_type_hello_world.png
  docs/community_resources/img/crowdin_translation.png
  docs/community_resources/img/toggle_incontext.png
  docs/extending/img/dropdown_expanded_state.jpg
  docs/extending/img/dropdown_multiple_selection.jpg
  docs/extending/img/oe_custom_button.png
  docs/extending/img/oe_custom_plugin.png
  docs/getting_started/img/first-steps-add-translation.png
  docs/getting_started/img/first-steps-create-content.png
  docs/getting_started/img/first-steps-create-ct.png
  docs/getting_started/img/first-steps-create-language.png
  docs/getting_started/img/welcome_page.png
  docs/guide/content_management.md
  docs/guide/img/admin_panel.png
  docs/guide/img/admin_panel_languages.png
  docs/guide/img/admin_panel_new_content_type.png
  docs/guide/img/admin_panel_roles.png
  docs/guide/img/admin_panel_sections.png
  docs/guide/img/admin_panel_system_info.png
  docs/guide/img/admin_panel_users.png
  docs/guide/img/availability_flag.png
  docs/guide/img/content_management_media.png
  docs/guide/img/content_management_tree.png
  docs/guide/img/content_structure_media_library.png
  docs/guide/img/customers_vat_setting.png
  docs/guide/img/organising_templates.png
  docs/guide/img/signal_slots_diagram.png
  docs/guide/img/workflow_notification.png
  docs/releases/img/4.2_upload_images.png
  docs/releases/img/dashboard.png
  docs/tutorials/platform_beginner/img/bike_tutorial_nav_hub.png
Labels: Ready for MERGE

#1719 Corrected path to @IbexaPageBuilder/page_builder/block/config.html.twig
  docs/extending/richtext_block.md
Labels: Needs DOC review

#1724 Add post-restructure redirects
  plugins.yml
Labels: Ready for MERGE

#1685 IBX-2493: Added option to invite other users to DXP & register from invitation
  docs/api/php_api/php_api.md
  docs/users/invitations.md
  mkdocs.yml
Labels: Ready for MERGE

#1721 IBX-2532: Added new Address field type
  docs/content_management/field_types/field_type_reference/addressfield.md
  mkdocs.yml
Labels: Ready for MERGE

#1728 IBX-3648 After update yarn.lock causes error during ibexa:encore:compile
  docs/update_and_migration/from_4.1/update_from_4.1.md
Labels: Ready for MERGE

#1727 Split content rendering page
  docs/administration/back_office/back_office_configuration.md
  docs/content_management/content_api/browsing_content.md
  docs/content_management/content_api/managing_content.md
  docs/content_management/content_availability.md
  docs/content_management/content_model.md
  docs/content_management/content_relations.md
  docs/content_management/images/images.md
  docs/content_management/locations.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#1730 Link update to Release Notes
  docs/release_notes/ibexa_dxp_v4.2.md
Labels: Ready for MERGE

#1733 Code update
  docs/api/field_types_reference/nullfield.md
Labels: Ready for MERGE

#1709 IBX-2885: Added group of attributes
  code_samples/page/custom_page_block/config/packages/nested_attribute.yaml
  docs/guide/page/page_block_attributes.md
Labels: Ready for MERGE

#1729 Added nested attribute
  code_samples/page/custom_page_block/config/packages/nested_attribute.yaml
  docs/content_management/pages/page_block_attributes.md
Labels: Ready for MERGE

#1732 IBX-51: Personalization: added delete request
  docs/personalization/developer_guide/user_api.md
Labels: Ready for MERGE

#1735 RT config key deprecated
  code_samples/back_office/online_editor/config/packages/custom_styles.yaml
  code_samples/back_office/online_editor/config/packages/custom_styles_highlight.yaml
  docs/release_notes/ibexa_dxp_v4.0_deprecations.md
Labels: Needs DOC review

#1737 Fixed reference to non existing pagerfanta template
  code_samples/front/query_pagination/templates/themes/my_theme/full/folder.html.twig
Labels: Ready for MERGE

#1738 Mark catalog filters unavailable in Legacy search engine
  docs/commerce/pim/catalog.md
Labels: Ready for MERGE

#1740 Updated search engine compatibility on catalog filters list
  docs/commerce/pim/catalog.md
Labels: Ready for MERGE
