Repository ibexa/documentation-developer, pull requests merged in 2022-04, with the labels that each got.

#1575 Added instructions how to create a migration step
  code_samples/data_migration/config/custom_services.yaml
  code_samples/data_migration/src/Migrations/Step/ReplaceNameStep.php
  code_samples/data_migration/src/Migrations/Step/ReplaceNameStepExecutor.php
  code_samples/data_migration/src/Migrations/Step/ReplaceNameStepNormalizer.php
  docs/guide/data_migration/create_migration_step.md
  mkdocs.yml
Labels: Ready for MERGE

#1576 Correct Fastly / Varnish headline
  docs/guide/security_checklist.md
Labels: Ready for MERGE

#1578 IBX-2324: Added config content remoteid
  docs/guide/personalization/recommendation_client.md
Labels: Ready for MERGE

#1581 Add warning about Flex server during update
  docs/index.md
  docs/updating/from_3.3/to_4.0.md
  docs/updating/from_3.3/update_from_3.3.md
Labels: Ready for MERGE

#1582 Data migration examples: continued
  code_samples/data_migration/examples/create_price.yaml
  code_samples/data_migration/examples/create_segment.yaml
  code_samples/data_migration/examples/update_attribute.yaml
  docs/guide/data_migration/importing_data.md
Labels: Ready for MERGE

#1579 IBX-2355: Product catalog GraphQL API
  docs/api/graphql.md
  docs/api/graphql_queries.md
Labels: Ready for MERGE

#1584 CS-9187 - security checklist update
  docs/guide/security_checklist.md
Labels: Needs DOC review

#1519 Updated personalization section
  docs/guide/architecture.md
  docs/guide/img/diagram_source/full_content_export.xml
  docs/guide/img/diagram_source/incremental_content_export.xml
  docs/guide/img/diagram_source/username_pattern.xml
  docs/guide/img/full_content_export.png
  docs/guide/img/incremental_content_export.png
  docs/guide/multisite/multisite.md
  docs/guide/personalization/basic_integration.md
  docs/guide/personalization/best_practices/tracking_integration.md
  docs/guide/personalization/developer_guide/importing_historical_user_tracking_data.md
  docs/guide/personalization/developer_guide/recommendation_api.md
  docs/guide/personalization/developer_guide/tracking_api.md
  docs/guide/personalization/developer_guide/tracking_with_yct.md
  docs/guide/personalization/developer_guide/user_api.md
  docs/guide/personalization/enabling_personalization.md
  docs/guide/personalization/img/Diagram source/full_content_export.drawio
  docs/guide/personalization/img/Diagram source/full_content_export.xml
  docs/guide/personalization/img/Diagram source/incremental_content_export.drawio
  docs/guide/personalization/img/Diagram source/incremental_content_export.xml
  docs/guide/personalization/img/full_content_export.png
  docs/guide/personalization/img/incremental_content_export.png
  docs/guide/personalization/recommendation_client.md
  mkdocs.yml
Labels: Ready for MERGE

#1594 IBX-2764: Added missing OSS v2.5 -> v3.3 database upgrade scripts
  docs/snippets/update/db/update_db_2.5-3.3.md
Labels: Needs DOC review, Needs DEV review, QA approved

#1595 IBX-2764: Added missing OSS v3.3 -> v4.0 database upgrade scripts
  docs/updating/from_3.3/to_4.0.md
Labels: Needs DOC review, Needs DEV review, QA approved

#1597 IBX-1482: Attribute search in Elasticsearch database
  docs/guide/personalization/developer_guide/attributes_search_elastic.md
  docs/guide/personalization/img/perso_attributes_search.png
  mkdocs.yml
Labels: Ready for MERGE

#1604 Remove mentions of eZ Launchpad
  docs/getting_started/install_ez_platform.md
  docs/guide/performance.md
Labels: Ready for MERGE
