Repository ibexa/documentation-developer, pull requests merged in 2022-12, with the labels that each got.

#1819 CS-10522: Updated with content status description
  docs/content_management/workflow/workflow.md
Labels: Ready for MERGE

#1821 EZP-32192: Added note about not serializing
  docs/api/php_api/php_api.md
Labels: Ready for MERGE

#1820 Corporate Portal Customisation of an approval process
  code_samples/customer_portal/src/Corporate/EventSubscriber/ApplicationDetailsViewSubscriber.php
  code_samples/customer_portal/src/Corporate/EventSubscriber/VerifyStateEventSubscriber.php
  code_samples/customer_portal/src/Form/VerifyType.php
  code_samples/customer_portal/templates/themes/admin/corporate_account/application/details.html.twig
  docs/customer_management/cp_applications.md
  docs/customer_management/img/cp_company_application_policy.png
  docs/customer_management/img/cp_new_status.png
  docs/customer_management/img/cp_verify_status.png
  mkdocs.yml
Labels: Ready for MERGE

#1823 Corporate Portal configuration
  docs/customer_management/cp_configuration.md
  docs/customer_management/create_user_registration_form.md
  docs/customer_management/customer_portal.md
  docs/customer_management/img/cp_dashboard_customer_portal.png
  mkdocs.yml
  plugins.yml
Labels: Needs DOC review, Needs DEV review

#1824 4.3 Release Notes Corporate Portal link update
  docs/release_notes/ibexa_dxp_v4.3.md
Labels: Ready for MERGE

#1828 Update enable_purchasing_products.md
  docs/pim/enable_purchasing_products.md
Labels: Needs DOC review

#1825 Corporate Portal path configuration corrections
  docs/customer_management/cp_configuration.md
Labels: Ready for MERGE

#1829 Update event_reference.md - Wrong event mentioned for copy operation
  docs/guide/repository/event_reference/event_reference.md
Labels: Ready for MERGE

#1808 IBX-3653: Event reference for TaxonomyService
  docs/api/event_reference/taxonomy_events.md
  mkdocs.yml
Labels: Ready for MERGE

#1831 Updated SVG tutorial source code to be compatible with v4
  code_samples/back_office/images/config/routes.yaml
  code_samples/back_office/images/src/SvgController.php
  code_samples/back_office/images/src/SvgExtension.php
Labels: Ready for MERGE

#1835 Add Connect documentation to doc switcher
  mkdocs.yml
Labels: Ready for MERGE

#1837 Change gitignore settings
  .gitignore
Labels: Needs DOC review

#1832 IBX-4548: Changed description for Draft locking
  docs/guide/workflow/workflow.md
Labels: Ready for MERGE

#1836 Screenshots update in Developer Documentation
  docs/administration/img/admin_panel_content_type_groups.png
  docs/administration/img/admin_panel_content_types.png
  docs/administration/img/admin_panel_sections.png
  docs/administration/img/admin_panel_segment.png
  docs/administration/img/udw_tabs.png
  docs/content_management/img/admin_panel_new_content_type.png
  docs/content_management/img/content_management_locations.png
  docs/pim/img/catalogs_filters.png
  docs/pim/img/product_completeness.png
Labels: Needs DOC review

#1839 IBX-4250: Added Taxonomy search criteria reference
  docs/search/criteria_reference/search_criteria_reference.md
  docs/search/criteria_reference/taxonomy_entry_id.md
  mkdocs.yml
Labels: Ready for MERGE
