Repository ibexa/documentation-developer, pull requests merged in 2022-02, with the labels that each got.

#1528 Update Algolia configuration
  docs/js/custom.js
Labels: Ready for MERGE

#1529 IBX-93: Updated Online editor to CKEditor
  code_samples/back_office/online_editor/config/packages/custom_buttons.yaml
  code_samples/back_office/online_editor/config/packages/custom_styles.yaml
  code_samples/back_office/online_editor/config/packages/custom_styles_highlight.yaml
  code_samples/back_office/online_editor/config/packages/custom_styles_note_box.yaml
  code_samples/back_office/online_editor/config/packages/custom_tags.yaml
  code_samples/back_office/online_editor/translations/custom_tags.en.yaml
  docs/extending/extending_online_editor.md
  docs/extending/img/custom_tag_factbox.png
  docs/extending/img/custom_tag_link.png
  docs/extending/img/oe_custom_tag_acronym.png
  docs/extending/img/oe_custom_tag_add_acronym.png
  docs/extending/online_editor_button.md
  docs/extending/online_editor_plugin.md
  mkdocs.yml
Labels: Ready for MERGE

#1520 Product catalog
  code_samples/api/product_catalog/src/Command/AttributeCommand.php
  code_samples/api/product_catalog/src/Command/CurrencyCommand.php
  code_samples/api/product_catalog/src/Command/ProductCommand.php
  code_samples/api/product_catalog/src/Command/ProductPriceCommand.php
  code_samples/api/product_catalog/src/Command/ProductTypeCommand.php
  docs/api/field_type_reference.md
  docs/api/field_types_reference/customergroupfield.md
  docs/api/field_types_reference/varianttype.md
  docs/api/public_php_api_managing_catalog.md
  docs/api/public_php_api_managing_prices.md
  docs/guide/catalog/catalog.md
  docs/guide/catalog/catalog_api/catalog_element.md
  docs/guide/catalog/catalog_api/customer_skus.md
  docs/guide/catalog/catalog_api/extending_a_catalogfactory.md
  docs/guide/catalog/catalog_api/productnode.md
  docs/guide/catalog/catalog_api/producttype.md
  docs/guide/catalog/catalog_api/routing_system.md
  docs/guide/catalog/catalog_configuration.md
  docs/guide/catalog/catalog_templates.md
  docs/guide/catalog/product.md
  docs/guide/catalog/product_rendering.md
  docs/guide/catalog/product_variants/product_variant_api.md
  docs/guide/catalog/product_variants/product_variants.md
  docs/guide/catalog/product_variants/setting_up_variants_from_external_source.md
  docs/guide/config_back_office.md
  docs/guide/content_model.md
  docs/guide/content_rendering/twig_function_reference/product_twig_functions.md
  docs/guide/data_providers/data_providers.md
  docs/guide/data_providers/repository_data_provider.md
  docs/guide/econtent/econtent.md
  docs/guide/econtent/econtent_configuration.md
  docs/guide/econtent/indexing_econtent_data.md
  docs/guide/econtent/staging_system.md
  docs/guide/erp_integration/remotepriceprovider.md
  docs/guide/limitation_reference.md
  docs/guide/limitations.md
  docs/guide/permissions.md
  docs/guide/pricing/price_api/localvatservice.md
  docs/guide/pricing/price_api/price_data_model.md
  docs/guide/pricing/price_api/price_providers.md
  docs/guide/pricing/price_api/standardcountryzoneservice.md
  docs/guide/pricing/price_api/standardpricefactory.md
  docs/guide/pricing/price_api/standardtemplatedebitorservice.md
  docs/guide/pricing/price_engine.md
  docs/guide/search/criteria_reference/currencycode_criterion.md
  docs/guide/search/criteria_reference/iscurrencyenabled_criterion.md
  docs/guide/search/criteria_reference/isproductbased_criterion.md
  docs/guide/search/criteria_reference/productcode_criterion.md
  docs/guide/search/criteria_reference/productname_criterion.md
  docs/guide/search/criteria_reference/producttype_criterion.md
  docs/guide/search/search_criteria_reference.md
  docs/guide/search/sort_clause_reference.md
  docs/guide/search/sort_clause_reference/productcode_sort_clause.md
  docs/guide/search/sort_clause_reference/productname_sort_clause.md
  docs/guide/user_management/customer_groups.md
  mkdocs.yml
Labels: Ready for MERGE

#1527 Update to 4.0
  docs/updating/from_3.3/to_4.0.md
  mkdocs.yml
Labels: Ready for QA, Ready for MERGE

#1409 v4.0 release notes
  docs/index.md
  docs/releases/ibexa_dxp_v4.0.md
  docs/releases/img/4.0_catalog.png
  docs/releases/img/4.0_new_ui.png
  docs/releases/img/4.0_product_price.png
  mkdocs.yml
Labels: Ready for MERGE

#1532 Update to v4: fix step order and improve
  docs/updating/from_3.3/to_4.0.md
Labels: Special case (see comments)

#1538 IBX-2299: Fixed asset generation order to prevent issues on missing m…
  docs/updating/from_3.3/update_from_3.3.md
Labels: Special case (see comments), Ready for MERGE

#1542 Remove references to ERP connection
  docs/api/field_types_reference/sesexternaldata.md
  docs/getting_started/troubleshooting.md
  docs/guide/basket/basket_api/basket_data_model.md
  docs/guide/basket/calculating_prices.md
  docs/guide/checkout/checkout.md
  docs/guide/checkout/checkout_api/checkout_events.md
  docs/guide/checkout/checkout_api/forms/checkout_delivery_address_form.md
  docs/guide/checkout/local_orders.md
  docs/guide/checkout/order_confirmation.md
  docs/guide/content_rendering/urls_and_routes.md
  docs/guide/customers/customer_api/configuration_for_customer_data.md
  docs/guide/customers/customer_api/customer_api.md
  docs/guide/customers/customer_api/customer_profile_data.md
  docs/guide/customers/customer_templates.md
  docs/guide/customers/customers.md
  docs/guide/customers/managing_delivery_addresses.md
  docs/guide/customers/vat_handling.md
  docs/guide/erp_integration/erp_communication.md
  docs/guide/erp_integration/erp_integration.md
  docs/guide/erp_integration/erp_logging.md
  docs/guide/erp_integration/lost_orders.md
  docs/guide/erp_integration/remotepriceprovider.md
  docs/guide/forms/form_api/dataprocessors.md
  docs/guide/logging/logging.md
  docs/guide/order_history/order_history.md
  docs/guide/order_history/order_history_configuration.md
  docs/guide/order_history/order_history_local_orders.md
  docs/guide/order_history/order_history_templates.md
  docs/guide/pricing/price_templates.md
  docs/guide/product_comparison/product_comparison.md
  docs/guide/quick_order/quick_order.md
  docs/guide/shop_configuration.md
  docs/guide/user_management/delegate_function.md
  docs/guide/user_management/login_and_registration.md
  docs/guide/vouchers/voucher_templates.md
  docs/guide/vouchers/vouchers.md
  mkdocs.yml
Labels: Ready for MERGE

#1543 IBX-1445: Update extensiblity section to v4
  code_samples/back_office/image_editor/src/AdditionalInformation.php
  code_samples/field_types/generic_ft/src/FieldType/HelloWorld/Comparison/Comparable.php
  code_samples/field_types/generic_ft/src/FieldType/HelloWorld/Comparison/HelloWorldComparisonEngine.php
  code_samples/field_types/generic_ft/src/FieldType/HelloWorld/Comparison/HelloWorldComparisonResult.php
  code_samples/field_types/generic_ft/src/FieldType/HelloWorld/Comparison/Value.php
  code_samples/page/custom_attribute/config/packages/page_blocks.yaml
  code_samples/page/custom_block_validator/config/packages/page_blocks.yaml
  code_samples/page/custom_page_block/config/packages/page_blocks.yaml
  code_samples/page/custom_page_block/templates/themes/standard/blocks/event/config.html.twig
  docs/api/field_type/create_custom_generic_field_type.md
  docs/extending/extending_thumbnails.md
  docs/extending/extending_udw.md
  docs/guide/image_editor.md
  docs/guide/page/page_block_attributes.md
  docs/guide/search/shop_search/search_api.md
Labels: Ready for MERGE

#1534 IBX-1868: Documentation for migration has been supplemented
  docs/guide/data_migration/data_migration.md
  docs/guide/data_migration/data_migration_actions.md
Labels: Ready for MERGE
