Repository ibexa/documentation-developer, pull requests merged in 2022-05, with the labels that each got.

#1603 Expand 4.1 release notes
  docs/releases/ibexa_dxp_v4.1.md
  docs/releases/img/4.1_content_tree.png
  docs/releases/img/4.1_measurement_attribute.png
  docs/releases/img/4.1_measurement_ft.png
  docs/releases/img/4.1_page_builder_dynamic_targeting.png
  docs/releases/img/4.1_taxonomy_lang_switcher.png
Labels: Ready for MERGE

#1557 Added info about apache_tika_path parameter related to BinaryFile Field indexing
  docs/guide/file_management.md
Labels: Needs DOC review

#1605 Product catalog follow-up
  docs/guide/basket/basket.md
  docs/guide/bestsellers.md
  docs/guide/img/product_comparison_1.png
  docs/guide/img/product_comparison_2.png
  docs/guide/img/product_comparison_categories.png
  docs/guide/order_history/order_history.md
  docs/guide/product_comparison/product_comparison.md
  docs/guide/product_comparison/product_comparison_api.md
  docs/guide/search/shop_search/searching_for_products.md
  docs/guide/search/shop_search/using_solr_spellcheck.md
  mkdocs.yml
Labels: Ready for MERGE

#1609 Fix version specific update notes for 2.5
  docs/updating/from_1.x_2.x/update_app_to_2.5.md
Labels: Ready for MERGE

#1601 Java requirements upgrade
  docs/getting_started/requirements.md
Labels: Needs DOC review, Needs DEV review

#1611 Fix APP_ENV for vhost setup
  docs/getting_started/install_ez_platform.md
  docs/guide/environments.md
Labels: Needs DOC review, Needs DEV review

#1608 Add custom product catalog attribute type
  code_samples/catalog/custom_attribute_type/config/custom_services.yaml
  code_samples/catalog/custom_attribute_type/src/Attribute/Percent/Form/PercentValueFormMapper.php
  code_samples/catalog/custom_attribute_type/src/Attribute/Percent/PercentAttributeOptionsType.php
  code_samples/catalog/custom_attribute_type/src/Attribute/Percent/PercentOptionsFormMapper.php
  code_samples/catalog/custom_attribute_type/src/Attribute/Percent/PercentOptionsValidator.php
  code_samples/catalog/custom_attribute_type/src/Attribute/Percent/PercentValueFormatter.php
  code_samples/catalog/custom_attribute_type/src/Attribute/Percent/PercentValueValidator.php
  docs/guide/catalog/create_custom_attribute_type.md
  docs/guide/img/catalog_custom_attribute_type.png
  mkdocs.yml
Labels: Ready for MERGE

#1614 Clarify configuration scope
  docs/guide/multisite/multisite_configuration.md
Labels: Ready for MERGE

#1617 IBX-2429: Example of UDW extensibility
  code_samples/back_office/udw/assets/js/image-tab/components/image.js
  code_samples/back_office/udw/assets/js/image-tab/components/images.list.js
  code_samples/back_office/udw/assets/js/image-tab/image.tab.module.js
  docs/extending/add_udw_tab.md
  docs/extending/extending_udw.md
  docs/extending/img/udw_image_tab.png
  docs/extending/img/udw_tabs.png
  mkdocs.yml
Labels: Ready for MERGE

#1620 Added modern Ibexa PHP-CS fixer configuration
  .php-cs-fixer.php
  .php_cs
  composer.json
Labels: Ready for MERGE

#1621 IBX-2846: Updated parameters for env
  docs/guide/personalization/enabling_personalization.md
  docs/guide/personalization/recommendation_client.md
Labels: Needs DOC review

#1618 IBX-2834: Document using Form Builder via PHP API
  code_samples/api/public_php_api/src/Command/FormSubmissionCommand.php
  docs/api/public_php_api_managing_forms.md
  docs/guide/form_builder/forms.md
  mkdocs.yml
Labels: Ready for MERGE

#1622 Remove mentions of deprecated search facets
  docs/api/public_php_api_search.md
  docs/guide/persistence_cache.md
  docs/guide/search/elastic.md
  docs/guide/search/extend_elasticsearch.md
  docs/guide/search/search.md
Labels: Ready for MERGE

#1626 IBX-414 - Measurement FT description
  docs/api/field_type_reference.md
  docs/api/field_types_reference/measurementfield.md
  mkdocs.yml
Labels: Needs DOC review, Needs DEV review

#1628 Fix taxonomy for name fieldtype
  docs/guide/taxonomy/taxonomy.md
Labels: Ready for MERGE
