Repository ibexa/documentation-developer, pull requests merged in 2022-10, with the labels that each got.

#1774 Added information about required last position of IbexaCompatibilityLayerBundle
  docs/update_and_migration/from_3.3/to_4.0.md
Labels: Ready for MERGE

#1777 Add note about installing Ibexa OSS
  docs/getting_started/install_ibexa_dxp.md
Labels: Ready for MERGE

#1748 Custom catalog filter
  code_samples/catalog/custom_catalog_filter/config/custom_services.yaml
  code_samples/catalog/custom_catalog_filter/config/packages/catalog_filters.yaml
  code_samples/catalog/custom_catalog_filter/src/CatalogFilter/DataTransformer/ProductNameCriterionTransformer.php
  code_samples/catalog/custom_catalog_filter/src/CatalogFilter/ProductNameFilter.php
  code_samples/catalog/custom_catalog_filter/src/CatalogFilter/ProductNameFilterFormMapper.php
  code_samples/catalog/custom_catalog_filter/templates/themes/admin/product_catalog/catalog_filters_blocks.html.twig
  code_samples/catalog/custom_catalog_filter/templates/themes/admin/product_catalog/form_field_override.html.twig
  docs/pim/create_custom_catalog_filter.md
  docs/pim/img/img/custom_catalog_filter.png
  mkdocs.yml
Labels: Ready for MERGE

#1776 Added taxonomy migration examples to migrations
  code_samples/data_migration/examples/assign_tag.yaml
  code_samples/data_migration/examples/create_tag.yaml
  code_samples/data_migration/examples/update_tag.yaml
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#1778 Corrected command to convert kaliop to our migration
  docs/guide/data_migration/migration_management.md
Labels: Ready for MERGE

#1767 Removing Content Types for v3
  docs/guide/content_model.md
Labels: Ready for MERGE

#1768 Removing Content Types v4
  docs/content_management/content_model.md
Labels: Ready for MERGE

#1783 Fixed anchor navigation code
  code_samples/back_office/content_type/templates/my_template.html.twig
Labels: Needs DEV review

#1782 v4.x online editor attributes naming update
  docs/content_management/rich_text/extend_online_editor.md
Labels: Ready for MERGE

#1785 IBX-3965: Price Sort Clause
  docs/search/sort_clause_reference/baseprice_sort_clause.md
  docs/search/sort_clause_reference/customprice_sort_clause.md
  docs/search/sort_clause_reference/sort_clause_reference.md
  mkdocs.yml
Labels: Ready for MERGE

#1779 Null FT config fix
  docs/content_management/field_types/field_type_reference/nullfield.md
Labels: Needs DOC review

#1788 REST API info on deprecated endpoints
  docs/api/rest_api/rest_api_reference/input/examples/product/catalog/attribute_groups/GET/AttributeGroupList.json.example
  docs/api/rest_api/rest_api_reference/input/examples/product/catalog/attribute_groups/id/GET/AttributeGroup.json.example
  docs/api/rest_api/rest_api_reference/input/examples/product/catalog/attribute_groups/id/GET/AttributeGroupGet.json.example
  docs/api/rest_api/rest_api_reference/input/examples/product/catalog/attributes/GET/AttributeList.json.example
  docs/api/rest_api/rest_api_reference/input/examples/product/catalog/attributes/GET/AttributeListGet.json.example
  docs/api/rest_api/rest_api_reference/input/examples/product/catalog/attributes/id/GET/AttributeGet.json.example
  docs/api/rest_api/rest_api_reference/input/examples/product/catalog/product/code/GET/ProductGet.json.example
  docs/api/rest_api/rest_api_reference/input/ez-product-attributegroups.raml
  docs/api/rest_api/rest_api_reference/input/ez-product-attributes.raml
  docs/api/rest_api/rest_api_reference/input/ez-product-products.raml
  docs/api/rest_api/rest_api_reference/input/ez-product-producttypes.raml
Labels: Ready for MERGE

#1787 IBX-3778: Added posibility to set order of default filters
  docs/pim/pim_configuration.md
Labels: Ready for MERGE

#1791 IBX-2375 - SEO functions
  docs/templating/twig_function_reference/content_twig_functions.md
Labels: Needs DOC review

#1793 4.2.2 update
  docs/update_and_migration/from_4.1/update_from_4.1.md
  mkdocs.yml
Labels: Ready for MERGE

#1784 IBX-3582: Extend catalog-related PHP API doc
  code_samples/api/product_catalog/src/Command/CatalogCommand.php
  code_samples/api/product_catalog/src/Command/ProductAssetCommand.php
  code_samples/api/product_catalog/src/Command/ProductVariantCommand.php
  code_samples/api/product_catalog/src/Command/VatCommand.php
  docs/pim/catalog_api.md
  docs/pim/price_api.md
  docs/pim/product_api.md
  mkdocs.yml
Labels: Ready for MERGE
