Repository ibexa/documentation-developer, pull requests merged in 2023-07, with the labels that each got.

#2032 ENG-69: Revamp documentation design: homepage
  docs/css/custom.css
  docs/css/front-page.css
  docs/css/navigation.css
  docs/images/icons.svg
  docs/images/notification-image.png
  docs/index.md
  docs/js/custom.js
  package.json
  scss/front-page.scss
Labels: Needs DOC review, Needs DEV review

#2044 Fixed links in tiles in landing page
  docs/index.md
Labels: Ready for MERGE

#2050 New in June
  docs/resources/new_in_doc.md
Labels: Ready for MERGE

#1871 IBX-4498: raml2html: Upgrade dependencies
  tools/raml2html/README.md
  tools/raml2html/composer.json
Labels: Needs DOC review

#2034 IBX-5973: Virtual Products checkout added in Dev-doc
  docs/commerce/checkout/checkout.md
  docs/commerce/checkout/img/virtual_product_purchase.png
  docs/pim/products.md
Labels: Needs DOC review

#2052 Simplifed Fastly-IO documentation
  docs/content_management/images/fastly_io.md
  docs/infrastructure_and_maintenance/cache/http_cache/fastly.md
  docs/infrastructure_and_maintenance/cache/http_cache/reverse_proxy.md
  mkdocs.yml
Labels: Needs DOC review

#2055 Changed nav hover bg and search
  docs/css/navigation.css
  docs/images/icons.svg
  theme/partials/search.html
Labels: Ready for MERGE

#2057 Removed references to non-existing stylesheets
  theme/partials/integrations/bootstrap.html
Labels: Ready for MERGE

#2064 Update Platform.sh Web console and CLI usage for Ibexa Cloud
  docs/getting_started/install_on_ibexa_cloud.md
  docs/infrastructure_and_maintenance/cache/http_cache/content_aware_cache.md
Labels: Needs DOC review, Needs DEV review

#2043 Fixes links in tiles in landing page
  docs/guide/data_migration/data_migration.md
  docs/guide/shop_process.md
  docs/guide/vouchers/vouchers.md
  docs/index.md
  docs/updating/from_4.3/update_from_4.3.md
  mkdocs.yml
Labels: Needs DOC review

#2065 Fixes to Commerce and Perso doc
  docs/commerce/commerce.md
  docs/commerce/payment/payment.md
  docs/personalization/api_reference/api_reference.md
  mkdocs.yml
Labels: Needs DOC review

#2063 Changes to triggers doc
  docs/personalization/img/Diagram source/recommendation_overview.xml
  docs/personalization/img/recommendation_overview.png
  docs/personalization/integrate_recommendation_service.md
Labels: Needs DOC review

#2066 IBX-6174 Multiattributes in submodel computation
  docs/personalization/api_reference/recommendation_api.md
Labels: Needs DOC review

#2071 [REST] Fixed Field Criterion input payload format
  docs/search/criteria_reference/field_criterion.md
Labels: Ready for MERGE

#2059 IBX-6185: Add file upload blocklist to security checklist
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE

#2074 Create React App block: Fix JS and JSX paths
  docs/content_management/pages/react_app_block.md
Labels: Ready for MERGE

#2047 IBX-6117: Ibexa Connect scenario block added in Developer Documentation
  code_samples/page/ibexa_connect_scenario_block/config/packages/ibexa_connect.yaml
  code_samples/page/ibexa_connect_scenario_block/config/packages/views.yaml
  code_samples/page/ibexa_connect_scenario_block/templates/blocks/default.html.twig
  code_samples/page/ibexa_connect_scenario_block/templates/pagelayout.html.twig
  composer.json
  docs/content_management/img/ibexa_connect_basic_tab.png
  docs/content_management/img/ibexa_connect_design_tab.png
  docs/content_management/img/ibexa_connect_webhook_preview.png
  docs/content_management/pages/ibexa_connect_scenario_block.md
  mkdocs.yml
Labels: Needs DOC review

#2073 IBX-6054 Improve configuration description of Customer Portal creation
  docs/customer_management/cp_page_builder.md
  docs/customer_management/customer_management.md
  docs/customer_management/img/cp_2_page_view.png
  docs/customer_management/img/cp_edit_in_page_builder.png
  docs/customer_management/img/cp_name_description.png
  docs/customer_management/img/single_cp_permissions.png
  docs/index.md
  mkdocs.yml
Labels: Ready for MERGE

#2077 IBX-5108: X-Expected-User
  docs/api/rest_api/rest_api_usage/rest_requests.md
Labels: Ready for MERGE

#2058 Remove outdated tools/prepare_guidelines_css
  tools/prepare_guidelines_css/README.md
  tools/prepare_guidelines_css/build.sh
  tools/prepare_guidelines_css/prefix_bootstrap.less
  tools/prepare_guidelines_css/prefix_ez.less
Labels: Ready for MERGE

#2072 IBX-6212: Improve the Security Checklist
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE

#2079 Fix style in Content management > Pages
  docs/content_management/pages/create_custom_page_block.md
  docs/content_management/pages/page_block_attributes.md
  docs/content_management/pages/page_block_validators.md
  docs/content_management/pages/page_blocks.md
  docs/content_management/pages/react_app_block.md
Labels: Ready for MERGE

#2060 JS events fired by Page Builder
  docs/content_management/pages/create_custom_page_block.md
Labels: Ready for MERGE

#2076 4.5.1 release note
  docs/release_notes/ibexa_dxp_v4.5.md
  docs/release_notes/img/4.5_product_category_tree.png
  mkdocs.yml
Labels: Ready for MERGE

#2082 Fixed nested lists
  docs/api/rest_api/rest_api_usage/rest_api_usage.md
  docs/infrastructure_and_maintenance/cache/http_cache/content_aware_cache.md
  docs/infrastructure_and_maintenance/cache/http_cache/reverse_proxy.md
  docs/infrastructure_and_maintenance/sessions.md
Labels: Ready for MERGE

#2085 Removed richtext migration command
  docs/update_and_migration/from_3.3/to_4.0.md
Labels: Needs DOC review

#2078 Default regions value
  docs/pim/enable_purchasing_products.md
Labels: Needs DOC review

#2086 rest_responses.md: Fix Response body Accept header example
  docs/api/rest_api/rest_api_usage/rest_responses.md
Labels: Ready for MERGE
