Repository ibexa/documentation-developer, pull requests merged in 2023-01, with the labels that each got.

#1845 Remove links from 404 page
  theme/404.html
Labels: Ready for MERGE

#1840 Added information about policy content/read for Reviewers workflow
  docs/guide/workflow/workflow.md
Labels: Ready for MERGE

#1849 IBX-4722: Fixed rebranded tag name for custom SA matchers
  docs/multisite/siteaccess/siteaccess_matching.md
Labels: Ready for MERGE

#1848 EZEE-1901: Implement Fastly Shielding
  docs/guide/cache/symfony_reverse_proxy.md
Labels: Ready for MERGE

#1830 Cards style update
  docs/css/custom.css
  docs/images/arrow_down.svg
  main.py
Labels: Ready for MERGE

#1852 IBX-4359: Added dedicated service for token-based authentication
  docs/infrastructure_and_maintenance/security/development_security.md
Labels: Ready for MERGE

#1851 Relese Notes update for v4.3.1
  docs/release_notes/ibexa_dxp_v4.3.md
Labels: Ready for MERGE

#1833 IBX-2602: External storage for Field Type settings
  docs/content_management/field_types/field_type_storage.md
  docs/content_management/field_types/type_and_value.md
Labels: Needs DOC review

#1854 Fix card plugin
  main.py
Labels: Ready for MERGE

#1853 Clarify location swap note on beginner tutorial
  docs/tutorials/beginner_tutorial/2_create_the_content_model.md
Labels: Ready for MERGE

#1858 IBX-1439: As a Maintainer I want to upgrade Flysystem to v2
  docs/content_management/file_management/file_management.md
  docs/infrastructure_and_maintenance/clustering/clustering.md
  docs/infrastructure_and_maintenance/clustering/clustering_with_aws_s3.md
Labels: Ready for MERGE

#1855 IBX-4495 - Add a redirect to block reference
  docs/content_management/pages/page_blocks.md
  docs/personalization/recommendation_integration.md
Labels: Needs DOC review

#1863 IBX-3175: Hide assigned content tab
  code_samples/taxonomy/config/packages/ibexa_taxonomy.yaml
  docs/content_management/taxonomy/taxonomy.md
Labels: Ready for MERGE

#1861 IBX-3951: Changed email with credentials in perso
  docs/personalization/enable_personalization.md
Labels: Ready for MERGE

#1841 IBX-4625: TaxonomyEntry/Assignment fields description added in Developer-Documentation
  docs/content_management/field_types/field_type_reference/authorfield.md
  docs/content_management/field_types/field_type_reference/field_type_reference.md
  docs/content_management/field_types/field_type_reference/taxonomyentryassignmentfield.md
  docs/content_management/field_types/field_type_reference/taxonomyentryfield.md
  mkdocs.yml
Labels: Needs DOC review

#1846 IBX 3133: Create Form Builder form attribute - v3.3
  code_samples/forms/custom_form_attribute/config/custom_services.yaml
  code_samples/forms/custom_form_attribute/config/packages/form_attribute_config.yaml
  code_samples/forms/custom_form_attribute/src/FormBuilder/FieldType/Field/Mapper/CheckboxWithRichtextDescriptionFieldMapper.php
  code_samples/forms/custom_form_attribute/src/FormBuilder/Form/Type/CheckboxWithRichtextDescriptionType.php
  code_samples/forms/custom_form_attribute/src/FormBuilder/Form/Type/FieldAttribute/AttributeRichtextDescriptionType.php
  code_samples/forms/custom_form_attribute/src/FormBuilder/FormSubmission/Converter/RichtextDescriptionFieldSubmissionConverter.php
  code_samples/forms/custom_form_attribute/src/Resources/encore/ez.config.js
  code_samples/forms/custom_form_attribute/src/Resources/public/js/formbuilder-richtext-checkbox.js
  code_samples/forms/custom_form_attribute/webpack.config.js
  code_samples/templates/bundles/EzPlatformFormBuilderBundle/fields/config/form_fields.html.twig
  code_samples/templates/formtheme/formbuilder_checkbox_with_richtext_description.html.twig
  docs/guide/form_builder/create_form_attribute.md
  docs/guide/img/new_form.png
  mkdocs.yml
Labels: Needs DOC review, Work in progress

#1864 IBX-3766 [CLOUD] Fastly Image Optimizer Integration
  docs/content_management/images/fastly_io.md
  docs/content_management/images/img/fastly_variations.png
  mkdocs.yml
Labels: Ready for MERGE

#1872 Updating link to a new version of CKEditor
  docs/content_management/rich_text/extend_online_editor.md
Labels: Ready for MERGE
