Repository ibexa/documentation-developer, pull requests merged in 2023-02, with the labels that each got.

#1856 IBX-4759: Twig function to fetch current User
  docs/templating/twig_function_reference/other_twig_filters.md
Labels: Ready for MERGE

#1869 Update gitignore
  .gitignore
Labels: Ready for MERGE

#1873 Fix incomplete random secrets command
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE

#1875 IBX-4642: Storefront config
  code_samples/front/shop/catalog_custom_logic/CatalogResolveEvent.php
  code_samples/front/shop/storefront/config/packages/ibexa.yaml
  code_samples/front/shop/storefront/src/EventSubscriber/BreadcrumbsMenuSubscriber.php
  code_samples/front/shop/storefront/templates/themes/storefront/storefront/knp_menu/breadcrumbs.html.twig
  code_samples/front/shop/storefront/templates/themes/storefront/storefront/product.html.twig
  docs/commerce/storefront/configure_storefront.md
  docs/commerce/storefront/extend_storefront.md
  docs/commerce/storefront/storefront.md
  mkdocs.yml
Labels: Ready for MERGE

#1874 Storefront templates
  docs/templating/embed_and_list_content/list_products.md
  docs/templating/embed_and_list_content/list_products_in_catalog.md
  docs/templating/layout/customize_basket.md
  docs/templating/layout/customize_storefront_layout.md
  docs/templating/render_content/customize_product_view.md
  docs/templating/render_content/render_product.md
  docs/templating/twig_function_reference/storefront_twig_functions.md
  docs/templating/twig_function_reference/twig_function_reference.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#1850 Update installation instruction for PHP 7.4
  docs/getting_started/install_ibexa_dxp.md
Labels: Ready for MERGE

#1870 Update from v4.3.x to v4.4
  docs/update_and_migration/from_4.3/update_from_4.3.md
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
  docs/update_and_migration/from_4.3/update_from_4.3_old_commerce.md
  docs/update_and_migration/update_ibexa_dxp.md
  mkdocs.yml
Labels: Ready for MERGE, QA approved

#1876 Release Notes fixes
  docs/index.md
  docs/release_notes/ibexa_dxp_v4.4.md
Labels: Ready for MERGE

#1867 Outline valid characters in policy module name.
  docs/permissions/custom_policies.md
Labels: Ready for MERGE

#1877 Added tiles to commerce landing page
  docs/commerce/commerce.md
  docs/commerce/storefront/extend_storefront.md
Labels: Ready for MERGE

#1842 IBX-3133: Create Form Builder form attribute - v4.3
  code_samples/forms/custom_form_attribute/config/custom_services.yaml
  code_samples/forms/custom_form_attribute/config/packages/form_attribute_config.yaml
  code_samples/forms/custom_form_attribute/src/FormBuilder/FieldType/Field/Mapper/CheckboxWithRichtextDescriptionFieldMapper.php
  code_samples/forms/custom_form_attribute/src/FormBuilder/Form/Type/CheckboxWithRichtextDescriptionType.php
  code_samples/forms/custom_form_attribute/src/FormBuilder/Form/Type/FieldAttribute/AttributeRichtextDescriptionType.php
  code_samples/forms/custom_form_attribute/src/FormBuilder/FormSubmission/Converter/RichtextDescriptionFieldSubmissionConverter.php
  code_samples/forms/custom_form_attribute/src/public/js/formbuilder-richtext-checkbox.js
  code_samples/forms/custom_form_attribute/webpack.config.js
  code_samples/templates/bundles/EzPlatformFormBuilderBundle/fields/config/form_fields.html.twig
  code_samples/templates/bundles/IbexaFormBuilderBundle/fields/config/form_fields.html.twig
  code_samples/templates/formtheme/formbuilder_checkbox_with_richtext_description.html.twig
  docs/content_management/forms/create_form_attribute.md
  docs/content_management/img/new_form.png
  mkdocs.yml
Labels: Needs DOC review

#1866 IBX-4651 Cart description, API, cart permissions
  code_samples/api/commerce/src/Command/CartCommand.php
  docs/administration/project_organization/bundles.md
  docs/commerce/cart/cart.md
  docs/commerce/cart/cart_api.md
  docs/commerce/commerce.md
  docs/permissions/limitation_reference.md
  docs/permissions/limitations.md
  docs/permissions/permission_use_cases.md
  docs/permissions/policies.md
  docs/templating/twig_function_reference/cart_twig_functions.md
  docs/templating/twig_function_reference/twig_function_reference.md
  mkdocs.yml
Labels: Ready for MERGE

#1868 Checkout description, API and configuration
  code_samples/api/commerce/config/packages/custom_routes.yaml
  code_samples/api/commerce/src/Controller/CustomCheckoutController.php
  code_samples/api/commerce/templates/custom_checkout.html.twig
  docs/commerce/checkout/checkout.md
  docs/commerce/checkout/checkout_api.md
  docs/commerce/checkout/configure_checkout.md
  docs/commerce/checkout/img/checkout.png
  docs/commerce/commerce.md
  docs/templating/twig_function_reference/cart_twig_functions.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#1847 IBX 2882 - Shop search limitations
  docs/search/shop_search/shop_search.md
Labels: Ready for MERGE

#1801 Limit DDL rights
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE

#1674 Use `http` syntax highlight
  docs/api/rest_api/rest_api_usage/rest_api_usage.md
  docs/api/rest_api/rest_api_usage/rest_requests.md
  docs/api/rest_api/rest_api_usage/rest_responses.md
Labels: Needs DOC review

#1880 Update screenshots to 4.4
  docs/administration/img/admin_panel.png
  docs/administration/img/admin_panel_assignments.png
  docs/administration/img/admin_panel_content_type_groups.png
  docs/administration/img/admin_panel_content_types.png
  docs/administration/img/admin_panel_object_state_groups.png
  docs/administration/img/admin_panel_policies.png
  docs/administration/img/admin_panel_roles.png
  docs/administration/img/admin_panel_sections.png
  docs/administration/img/admin_panel_segment.png
  docs/administration/img/admin_panel_segment_groups.png
  docs/administration/img/admin_panel_system_info.png
  docs/administration/img/admin_panel_users.png
  docs/administration/img/object_state_lock.png
  docs/content_management/img/content_management_forms.png
  docs/content_management/img/content_management_media.png
  docs/content_management/img/content_management_tree.png
  docs/content_management/img/content_management_visibility.png
  docs/content_management/img/custom_tag_factbox.png
  docs/content_management/img/oe_custom_class_note_box_select.png
  docs/content_management/img/oe_custom_style_highlight_select.png
  docs/content_management/img/oe_custom_style_note_box_select.png
  docs/customer_management/img/cp_company_application_policy.png
  docs/customer_management/img/cp_dashboard_customer_portal.png
  docs/getting_started/first_steps.md
  docs/getting_started/img/first-steps-create-ct.png
  docs/getting_started/img/welcome_page.png
  docs/multisite/img/site_factory_site_list.png
  docs/multisite/site_factory/site_factory.md
  docs/search/img/search_categories.png
  docs/search/img/search_limits.png
  docs/search/img/search_product_list.png
  docs/templating/img/catalog_query_type_field.png
  docs/templating/img/content_query_field_definition.png
  docs/users/img/log_in_via_google.png
  docs/users/img/password_expiry.png
  docs/users/img/username_pattern.png
Labels: Ready for MERGE

#1882 IBX-4621: Clarify update to v3 requirements
  docs/update_and_migration/from_2.5/to_3.2.md
  docs/update_and_migration/from_2.5/update_from_2.5.md
Labels: Ready for MERGE

#1883 Readme update
  README.md
Labels: Ready for MERGE

#1878 IBX-4004 Upgrade doc for 4.1 missing Fastly VCL changes needed for shielding support
  docs/snippets/update/vcl_configuration_for_fastly_v3.md
  docs/snippets/update/vcl_configuration_for_fastly_v4.md
  docs/update_and_migration/from_1.x_2.x/update_db_to_2.5.md
  docs/update_and_migration/from_2.5/to_3.3.latest.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.0/to_4.1.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
Labels: Ready for MERGE

#1889 Fastly code samples update
  docs/content_management/images/fastly_io.md
  docs/update_and_migration/from_1.x_2.x/update_db_to_2.5.md
  docs/update_and_migration/from_2.5/to_3.3.latest.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
Labels: Ready for MERGE

#1891 Invitations yaml code update
  docs/users/invitations.md
Labels: Ready for MERGE

#1893 Fix tiles orders for Commerce
  docs/commerce/commerce.md
Labels: Ready for MERGE

#1660 improve-file_type_blacklist-overwrite
  docs/content_management/images/images.md
Labels: Ready for MERGE

#1885 IBX-4334: Changed yct and yoochoose mentions in Perso
  docs/personalization/api_reference/tracking_api.md
  docs/personalization/enable_personalization.md
  docs/personalization/tracking_integration.md
  docs/personalization/tracking_with_ibexa-tracker.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#1888 Product catalog root view matcher
  docs/templating/templates/view_matcher_reference.md
Labels: Ready for MERGE

#1890 IBX-5061: DateMetadata Criterion PUBLISHED target
  docs/search/criteria_reference/datemetadata_criterion.md
Labels: Ready for MERGE

#1765 Fix CACHE_POOL injection in 3.3
  docs/guide/persistence_cache.md
Labels: Needs DEV review

#1899 Rename view matcher sections for pim matchers
  docs/templating/templates/view_matcher_reference.md
Labels: Ready for MERGE

#1862 Added Media section permission for anonymous user to be able to visua…
  docs/tutorials/beginner_tutorial/5_display_a_list_of_content_items.md
  docs/tutorials/beginner_tutorial/8_enable_account_registration.md
  docs/tutorials/beginner_tutorial/img/step5_admin_anonymous_policies_with_media_section.png
  docs/tutorials/beginner_tutorial/img/step5_admin_anonymous_policies_without_media_section.png
Labels: Ready for MERGE

#1887 Override default settings
  docs/content_management/images/images.md
  docs/customer_management/cp_configuration.md
Labels: Needs DEV review

#1903 IBX-3096: not_blank_richtext page attribute validator
  docs/guide/page/page_block_validators.md
Labels: Ready for MERGE

#1704 IBX-3465: Added Nginx vhost template
  code_samples/install/vhost_template/vhost.template
  docs/getting_started/install_ibexa_dxp.md
  docs/infrastructure_and_maintenance/environments.md
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE
