Repository ibexa/documentation-developer, pull requests merged in 2023-03, with the labels that each got.

#1894 IBX-4939: Doc changelog
  docs/resources/new_in_doc.md
  mkdocs.yml
Labels: Ready for MERGE

#1907 Fix tag for solr field mapper.
  code_samples/search/solr/config/field_mapper_services.yaml
  docs/search/extensibility/solr_document_field_mappers.md
Labels: Ready for MERGE

#1909 v4.3.5 RNs
  docs/release_notes/ibexa_dxp_v4.3.md
  mkdocs.yml
Labels: Ready for MERGE

#1917 Update doc site dependencies
  .readthedocs.yml
  docs/css/custom.css
  docs/css/ez-guidelines-badges.css
  docs/css/ez-guidelines-buttons.css
  docs/css/ez-guidelines-colors.css
  docs/css/ez-guidelines-form-components.css
  docs/css/ez-guidelines-icons.css
  docs/css/ez-guidelines-modals.css
  docs/css/ez-guidelines-pagination.css
  docs/css/ez-guidelines-switchers.css
  docs/css/ez-guidelines-tables.css
  docs/css/ez-guidelines-tabs.css
  docs/css/ez-guidelines-tooltips.css
  docs/css/ez-guidelines-typography.css
  docs/css/ez-guidelines-utilities.css
  docs/css/ez-guidelines.css
  docs/css/navigation.css
  docs/js/ez-guidelines-modals.js
  docs/js/ez-guidelines-switchers.js
  docs/js/ez-guidelines-tooltips.js
  mkdocs.yml
  requirements.txt
  theme/partials/header.html
Labels: Ready for MERGE

#1910 IBX-4996: Storefront tutorial
  docs/commerce/cart/cart.md
  docs/templating/layout/customize_storefront_layout.md
Labels: Ready for MERGE

#1919 IBX-5113 - Anonymous access to store
  docs/permissions/permission_use_cases.md
Labels: Needs DOC review, Needs DEV review

#1908 IBX-4760: Unsuported ezstarrating in upgrade
  docs/update_and_migration/from_1.x_2.x/update_db_to_2.5.md
  docs/update_and_migration/migrate_to_ibexa_dxp/migrating_from_ez_publish_platform.md
Labels: Ready for MERGE

#1920 IBX-5100: Reorganize Admin Panel/Content model doc
  docs/administration/admin_panel.md
  docs/administration/admin_panel/admin_panel.md
  docs/administration/admin_panel/corporate_admin_panel.md
  docs/administration/admin_panel/languages_admin_panel.md
  docs/administration/admin_panel/roles_admin_panel.md
  docs/administration/admin_panel/segments_admin_panel.md
  docs/administration/admin_panel/system_information_admin_panel.md
  docs/administration/admin_panel/url_management_admin_panel.md
  docs/administration/admin_panel/users_admin_panel.md
  docs/administration/admin_panel/workflow_admin_panel.md
  docs/administration/administration.md
  docs/administration/content_organization/content_types.md
  docs/administration/content_organization/object_states.md
  docs/administration/content_organization/sections.md
  docs/administration/img/admin_panel_assignments.png
  docs/administration/img/admin_panel_content_type_groups.png
  docs/administration/img/admin_panel_content_types.png
  docs/administration/img/admin_panel_corporate.png
  docs/administration/img/admin_panel_icon.png
  docs/administration/img/admin_panel_languages.png
  docs/administration/img/admin_panel_object_state_groups.png
  docs/administration/img/admin_panel_policies.png
  docs/administration/img/admin_panel_roles.png
  docs/administration/img/admin_panel_sections.png
  docs/administration/img/admin_panel_segment.png
  docs/administration/img/admin_panel_segment_groups.png
  docs/administration/img/admin_panel_system_info.png
  docs/administration/img/admin_panel_url_management.png
  docs/administration/img/admin_panel_users.png
  docs/administration/img/admin_panel_workflow.png
  docs/administration/img/assigning_an_object_state.png
  docs/administration/img/object_state_lock.png
  docs/content_management/content_model.md
  mkdocs.yml
  plugins.yml
Labels: Needs DOC review

#1927 CS-10851: Moving PB attributes removes their value
  docs/content_management/pages/page_block_attributes.md
Labels: Ready for MERGE

#1921 IBX-5261 Doc : Changing block config ( page builder ) requires clearing the persistance cache
  docs/content_management/pages/create_custom_page_block.md
  docs/content_management/pages/page_block_attributes.md
  docs/content_management/pages/page_blocks.md
  docs/snippets/page_block_cache_clear.md
  docs/templating/render_content/render_page.md
Labels: Ready for MERGE

#1929 Add note for changed URL_ALIAS_ROUTE_NAME
  docs/release_notes/ibexa_dxp_v4.0_deprecations.md
Labels: Ready for MERGE

#1911 IBX-5022 - Checkout customization
  code_samples/front/shop/checkout/assets/styles/app.css
  code_samples/front/shop/checkout/config/packages/ibexa.yaml
  code_samples/front/shop/checkout/src/Controller/SelectSeatStepController.php
  code_samples/front/shop/checkout/src/Controller/SinglePageCheckout.php
  code_samples/front/shop/checkout/src/Form/Type/SelectSeatType.php
  code_samples/front/shop/checkout/src/Form/Type/SinglePageCheckoutType.php
  code_samples/front/shop/checkout/templates/themes/storefront/checkout/checkout.html.twig
  code_samples/front/shop/checkout/templates/themes/storefront/checkout/step/select_seat.html.twig
  code_samples/front/shop/checkout/templates/themes/storefront/layout.html.twig
  docs/commerce/checkout/configure_checkout.md
  docs/commerce/checkout/customize_checkout.md
  docs/commerce/checkout/img/additional_checkout_step.png
  docs/commerce/checkout/img/checkout.png
  docs/commerce/checkout/img/single_page_checkout.png
  docs/commerce/commerce.md
  mkdocs.yml
Labels: Needs DOC review, Needs DEV review

#1926 IBX-2667 - Anchor menu configuration
  docs/administration/back_office/content_type_anchor_menu.md
  docs/administration/img/content_type_edit_screen_anchor_menu.png
  mkdocs.yml
Labels: Needs DOC review, Needs DEV review

#1933 IBX-5282 Order management permissions
  docs/permissions/permission_use_cases.md
  docs/permissions/policies.md
Labels: Needs DOC review, Needs DEV review

#1934 Missing ext-sodium in PHP packages
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1723 Fix custom taxonomy creation steps and conf
  code_samples/taxonomy/config/packages/ibexa_taxonomy.yaml
  docs/content_management/taxonomy/taxonomy.md
Labels: Ready for MERGE

#1928 IBX-4162 Map custom Field Type to GraphQL
  code_samples/api/graphql/src/DependencyInjection/Compiler/MyCustomTypeGraphQLCompilerPass.php
  code_samples/api/graphql/src/GraphQL/Schema/MyCustomFieldDefinitionMapper.php
  docs/api/graphql/graphql_custom_ft.md
  mkdocs.yml
Labels: Ready for MERGE

#1935 Moved 4.1 Upgrade Docs for Fastly Shielding
  docs/update_and_migration/from_4.0/to_4.1.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
Labels: Ready for MERGE

#1938 IBX-5321: Improved data migration feature description
  docs/content_management/data_migration/data_migration.md
  docs/content_management/data_migration/managing_migrations.md
Labels: Ready for MERGE

#1936 IBX-5376: Added possibility to change config of CKE
  docs/content_management/rich_text/extend_online_editor.md
Labels: Ready for MERGE

#1844 IBX-3962: Introduced ModifyFieldDefinitionFieldsSubscriber
  docs/content_management/content_model.md
  docs/content_management/customize_field_type_metadata.md
  docs/content_management/img/disable-required-field.png
  mkdocs.yml
Labels: Ready for MERGE
