Repository ibexa/documentation-developer, pull requests merged in 2023-05, with the labels that each got.

#1975 Update from v4.4.x to v4.5
  docs/update_and_migration/from_4.4/update_from_4.4.md
  docs/update_and_migration/update_ibexa_dxp.md
  mkdocs.yml
Labels: Ready for MERGE

#1981 IBX-2762: Prevented invalid unit conversion configuration
  docs/update_and_migration/from_4.4/update_from_4.4.md
Labels: Ready for MERGE

#1946 Release notes v4.5
  docs/index.md
  docs/release_notes/ibexa_dxp_v4.5.md
  docs/release_notes/img/4.5_bestsellers_block.png
  docs/release_notes/img/4.5_comparison_view.png
  docs/release_notes/img/4.5_order_list.png
  docs/release_notes/img/4.5_page_builder_b2b.png
  docs/release_notes/img/4.5_payment_methods.png
  docs/release_notes/img/4.5_product_categories.png
  docs/release_notes/img/4.5_react_app_block.png
  docs/release_notes/img/4.5_segment_management.png
  docs/release_notes/img/4.5_shipping_methods.png
  docs/release_notes/release_notes.md
  mkdocs.yml
Labels: Ready for MERGE

#1982 New in doc: April 2023
  docs/resources/new_in_doc.md
Labels: Ready for MERGE

#1941 IBX-5374: Fixed add layout template
  code_samples/front/render_page/templates/themes/my_theme/layouts/sidebar.html.twig
  docs/content_management/field_types/field_type_reference/pagefield.md
  docs/templating/render_content/render_page.md
Labels: Ready for MERGE

#1986 IBX-4844: Added addresses validation
  docs/content_management/field_types/field_type_reference/addressfield.md
Labels: Ready for MERGE

#1994 Dividing migrations between Commerce and Experience
  docs/update_and_migration/from_4.4/update_from_4.4.md
Labels: Ready for MERGE

#1992 IBX-5847 - Add Commerce events to documentation
  docs/api/event_reference/cart_events.md
  docs/api/event_reference/order_management_events.md
  docs/api/event_reference/payment_events.md
  mkdocs.yml
Labels: Needs DOC review, Needs DEV review

#1943 Update context_aware_cache.md:FOS HTTPCAHCE documentation from 2.8.0 to latest? or stable?
  docs/infrastructure_and_maintenance/cache/http_cache/context_aware_cache.md
Labels: Ready for MERGE

#1997 `Node.js` 14+ has reached its End of Life
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#1979 IBX-5316 - Front page redesign
  docs/css/front-page.css
  docs/customer_management/customer_management.md
  docs/images/Build site.svg
  docs/images/Idea.svg
  docs/images/Reward.svg
  docs/images/Site Factory.svg
  docs/images/Value.svg
  docs/images/content.png
  docs/images/content_edit.svg
  docs/images/customer.png
  docs/images/four.png
  docs/images/number_one.png
  docs/images/one.png
  docs/images/product.png
  docs/images/three.png
  docs/images/two.png
  docs/images/user.png
  docs/index.md
  mkdocs.yml
Labels: Needs DOC review

#1998 Fix customize checkout recipe
  code_samples/front/shop/checkout/assets/styles/checkout.css
  code_samples/front/shop/checkout/config/packages/checkout.yaml
  code_samples/front/shop/checkout/src/Controller/Checkout/SinglePageCheckout.php
  code_samples/front/shop/checkout/src/Controller/Checkout/Step/SelectSeatStepController.php
  code_samples/front/shop/checkout/src/Form/Type/SelectSeatType.php
  code_samples/front/shop/checkout/src/Form/Type/SinglePageCheckoutType.php
  code_samples/front/shop/checkout/templates/themes/storefront/checkout/checkout.html.twig
  code_samples/front/shop/checkout/templates/themes/storefront/checkout/step/select_seat.html.twig
  docs/commerce/checkout/configure_checkout.md
  docs/commerce/checkout/customize_checkout.md
  docs/commerce/checkout/img/single_page_checkout.png
Labels: Ready for MERGE

#1999 Fix customize checkout recipe v4.4
  code_samples/front/shop/checkout/assets/styles/checkout.css
  code_samples/front/shop/checkout/config/packages/checkout.yaml
  code_samples/front/shop/checkout/src/Controller/Checkout/SinglePageCheckout.php
  code_samples/front/shop/checkout/src/Controller/Checkout/Step/SelectSeatStepController.php
  code_samples/front/shop/checkout/src/Form/Type/SelectSeatType.php
  code_samples/front/shop/checkout/src/Form/Type/SinglePageCheckoutType.php
  code_samples/front/shop/checkout/templates/themes/storefront/checkout/checkout.html.twig
  code_samples/front/shop/checkout/templates/themes/storefront/checkout/step/select_seat.html.twig
  docs/commerce/checkout/configure_checkout.md
  docs/commerce/checkout/customize_checkout.md
  docs/commerce/checkout/img/single_page_checkout.png
Labels: Ready for MERGE

#1996 IBX-5609 - Add Extend Payment article
  code_samples/api/commerce/src/Command/PaymentCommand.php
  code_samples/api/commerce/src/Command/PaymentMethodCommand.php
  code_samples/front/shop/payment/config/packages/services.yaml
  code_samples/front/shop/payment/src/Form/Type/PayPalOptionsType.php
  code_samples/front/shop/payment/src/PaymentMethodType/PayPal/OptionsFormMapper.php
  code_samples/front/shop/payment/src/PaymentMethodType/PayPal/PayPal.php
  code_samples/front/shop/payment/src/PaymentMethodType/PayPal/UrlOptionValidator.php
  docs/commerce/payment/configure_payment.md
  docs/commerce/payment/extend_payment.md
  docs/commerce/payment/img/custom_paymant_type.png
  docs/commerce/payment/payment_api.md
  docs/commerce/payment/payment_method_api.md
  mkdocs.yml
Labels: Needs DOC review, Needs DEV review

#2003 Misc post-audit fixes
  docs/content_management/content_model.md
  docs/content_management/field_types/customize_field_type_metadata.md
  docs/content_management/file_management/binary_and_media_download.md
  docs/content_management/file_management/file_management.md
  docs/content_management/images/images.md
  docs/content_management/locations.md
  docs/content_management/rich_text/extend_online_editor.md
  docs/content_management/taxonomy/taxonomy.md
  docs/content_management/workflow/workflow.md
  docs/content_management/workflow/workflow_api.md
  docs/infrastructure_and_maintenance/backup.md
  docs/infrastructure_and_maintenance/databases.md
  docs/users/segment_api.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#2002 Add Google Tag Manager scripts
  docs/js/custom.js
  theme/main.html
Labels: Ready for MERGE
