Repository ibexa/documentation-developer, pull requests merged in 2023-06, with the labels that each got.

#2008 New in May
  docs/resources/new_in_doc.md
Labels: Ready for MERGE

#2010 Add instructrions for how to install debug toolbar
  docs/infrastructure_and_maintenance/devops.md
Labels: Ready for MERGE

#2009 IBX-5523 - Fix commerce doc
  docs/commerce/storefront/storefront.md
Labels: Needs DOC review

#2013 Extended example of create product price migration
  code_samples/data_migration/examples/create_price.yaml
Labels: Ready for MERGE

#2015 IBX-5806: Add php-cs-fixer
  .github/workflows/build.yaml
  code_samples/api/migration/src/Command/MigrationCommand.php
  code_samples/api/rest_api/create_image.json.php
  code_samples/api/rest_api/create_image.xml.php
  code_samples/api/rest_api/src/Rest/Controller/DefaultController.php
  code_samples/api/rest_api/src/Rest/InputParser/GreetingInput.php
  code_samples/api/rest_api/src/Rest/Output/ValueObjectVisitorDispatcher.php
  code_samples/api/rest_api/src/Rest/ValueObjectVisitor/Greeting.php
  code_samples/api/rest_api/src/Rest/ValueObjectVisitor/RestLocation.php
  code_samples/api/rest_api/src/Rest/Values/Greeting.php
  code_samples/back_office/images/src/PlaceholderProvider.php
  code_samples/back_office/images/src/SvgController.php
  code_samples/back_office/images/src/SvgExtension.php
  code_samples/back_office/notifications/src/EventListener/ContentPublishEventListener.php
  code_samples/back_office/notifications/src/Notification/MyRenderer.php
  code_samples/back_office/online_editor/src/event/subscriber/RichTextBlockSubscriber.php
  code_samples/data_migration/src/Migrations/Action/AssignSectionExecutor.php
  code_samples/data_migration/src/Migrations/Matcher/SectionIdentifierNormalizer.php
  code_samples/data_migration/src/Migrations/Step/ReplaceNameStepExecutor.php
  code_samples/field_types/2dpoint_ft/src/FieldType/Point2D/Type.php
  code_samples/field_types/2dpoint_ft/src/Form/Type/Point2DSettingsType.php
  code_samples/field_types/2dpoint_ft/src/Form/Type/Point2DType.php
  code_samples/field_types/2dpoint_ft/src/Serializer/Point2D/ValueDenormalizer.php
  code_samples/field_types/2dpoint_ft/src/Serializer/Point2D/ValueNormalizer.php
  code_samples/field_types/2dpoint_ft/steps/step_1/Value.php
  code_samples/field_types/2dpoint_ft/steps/step_3/Point2DType.php
  code_samples/field_types/2dpoint_ft/steps/step_3/Type.php
  code_samples/field_types/2dpoint_ft/steps/step_6/Type.php
  code_samples/tutorials/page_tutorial/src/Event/RandomBlockListener.php
  code_samples/tutorials/page_tutorial/src/QueryType/MenuQueryType.php
  code_samples/tutorials/page_tutorial_starting_point/src/QueryType/MenuQueryType.php
  code_samples/workflow/custom_workflow/src/EventListener/ApprovedTransitionListener.php
  code_samples/workflow/custom_workflow/src/EventListener/LegalTransitionListener.php
  composer.json
  docs/content_management/data_migration/data_migration_api.md
  docs/tutorials/generic_field_type/3_create_form_for_point2d.md
  docs/tutorials/generic_field_type/6_settings.md
  tests/source_files/step4/RandomBlockListener.php
  tests/src/ConfigurationEditor.php
  tests/src/ContentDataCreator.php
  tests/src/Context/ConfigurationContext.php
  tests/src/Context/ContentContext.php
  tests/src/Context/FileContext.php
  tests/src/Context/TutorialContentTypeContext.php
Labels: Ready for MERGE

#2012 Update symfony_reverse_proxy.md
  docs/guide/cache/symfony_reverse_proxy.md
Labels: Needs DOC review

#2019 IBX-5757: Fixed custom classes and attributes on headings
  docs/content_management/rich_text/extend_online_editor.md
Labels: Ready for MERGE

#2018 IBX-5865: Ensure all templates examples use design engine
  code_samples/back_office/images/config/default_settings.yaml
  code_samples/back_office/images/templates/themes/standard/svg_helper.html.twig
  code_samples/back_office/online_editor/config/packages/ibexa_page_fieldtype.yaml
  code_samples/back_office/settings/config/packages/user_settings.yaml
  code_samples/back_office/settings/templates/themes/admin/user/setting/update_unit.html.twig
  code_samples/forms/custom_form_attribute/templates/bundles/EzPlatformFormBuilderBundle/fields/config/form_fields.html.twig
  code_samples/forms/custom_form_attribute/templates/bundles/IbexaFormBuilderBundle/fields/config/form_fields.html.twig
  code_samples/forms/custom_form_attribute/templates/themes/standard/formtheme/formbuilder_checkbox_with_richtext_description.html.twig
  docs/administration/back_office/add_user_setting.md
  docs/administration/back_office/back_office_menus/add_menu_item.md
  docs/content_management/forms/create_form_attribute.md
  docs/content_management/images/add_image_asset_from_dam.md
  docs/content_management/images/images.md
  docs/content_management/rich_text/create_custom_richtext_block.md
Labels: Ready for MERGE

#2021 Data migration Content type deletion
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#2020 IBX-5108: Stock Search Criteria and Aggregation
  docs/search/aggregation_reference/aggregation_reference.md
  docs/search/aggregation_reference/productstockrange_aggregation.md
  docs/search/criteria_reference/product_search_criteria.md
  docs/search/criteria_reference/productstock_criterion.md
  docs/search/criteria_reference/productstockrange_criterion.md
  mkdocs.yml
Labels: Ready for MERGE

#1991 IBX-2762 Implement measurements conversion
  docs/content_management/field_types/field_type_reference/measurementfield.md
Labels: Ready for MERGE

#1990 Improved DX of product availability create/update structs
  code_samples/api/product_catalog/src/Command/ProductCommand.php
  docs/pim/product_api.md
Labels: Ready for MERGE

#2024 IBX-5315: Revise search engine documentation
  docs/administration/project_organization/architecture.md
  docs/content_management/field_types/field_type_reference/field_type_reference.md
  docs/content_management/field_types/field_type_search.md
  docs/content_management/url_management/url_api.md
  docs/getting_started/install_ibexa_dxp.md
  docs/infrastructure_and_maintenance/cache/persistence_cache.md
  docs/infrastructure_and_maintenance/clustering/clustering.md
  docs/infrastructure_and_maintenance/performance.md
  docs/search/extensibility/create_custom_sort_clause.md
  docs/search/extensibility/index_custom_elasticsearch_data.md
  docs/search/reindex_search.md
  docs/search/search.md
  docs/search/search_engines.md
  docs/search/search_engines/elastic_search/configure_elastic_search.md
  docs/search/search_engines/elastic_search/elastic_search_overview.md
  docs/search/search_engines/elastic_search/install_elastic_search.md
  docs/search/search_engines/legacy_search_engine/configure_repository.md
  docs/search/search_engines/legacy_search_engine/legacy_search_overview.md
  docs/search/search_engines/search_engines.md
  docs/search/search_engines/solr_search_engine/configure_solr.md
  docs/search/search_engines/solr_search_engine/install_solr.md
  docs/search/search_engines/solr_search_engine/solr_overview.md
  docs/search/solr_search_engine.md
  docs/search/url_search_reference/url_search_criteria.md
  docs/search/url_search_reference/url_search_sort_clauses.md
  docs/users/login_and_registration.md
  mkdocs.yml
  plugins.yml
Labels: Needs DOC review

#2025 IBX-5978: Clean up Limitation doc
  docs/permissions/limitation_reference.md
  docs/permissions/limitations.md
  docs/permissions/policies.md
Labels: Ready for MERGE

#2017 Update pagefield.md fieldtype call
  docs/content_management/field_types/field_type_reference/pagefield.md
Labels: Ready for MERGE

#2029 IBX-5901 - Commerce landing page formatting
  code_samples/front/shop/checkout/config/packages/checkout.yaml
  code_samples/front/shop/checkout/src/Controller/Checkout/OnePageCheckout.php
  code_samples/front/shop/checkout/src/Form/Type/OnePageCheckoutType.php
  docs/commerce/cart/cart_api.md
  docs/commerce/checkout/configure_checkout.md
  docs/commerce/checkout/customize_checkout.md
  docs/commerce/commerce.md
  docs/commerce/order_management/configure_order_management.md
  docs/commerce/order_management/order_management_api.md
  docs/commerce/payment/configure_payment.md
  docs/commerce/payment/extend_payment.md
  docs/commerce/payment/payment.md
  docs/commerce/payment/payment_method_api.md
  docs/commerce/shipping_management/configure_shipment.md
  docs/commerce/storefront/storefront.md
  mkdocs.yml
Labels: Needs DEV review

#2030 Update back_office_translations.md
  docs/multisite/languages/back_office_translations.md
Labels: Ready for MERGE

#2007 IBX-5797: Ibexa Content to Ibexa Headless
  .github/pull_request_template.md
  docs/administration/project_organization/bundles.md
  docs/getting_started/install_ibexa_dxp.md
  docs/resources/release_process_and_roadmap.md
  mkdocs.yml
Labels: Ready for MERGE

#2028 Tile admonition type
  docs/css/custom.css
Labels: Ready for MERGE

#2011 IBX-5805: Vale.sh PoC
  .github/workflows/build.yaml
Labels: Needs DEV review

#2033 Update available data migration modes, types and matches
  docs/content_management/data_migration/exporting_data.md
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#2039 Update screenshots after 4.5 release
  docs/administration/img/admin_panel.png
  docs/administration/img/admin_panel_content_types.png
  docs/administration/img/assigning_an_object_state.png
  docs/administration/img/extending_thumbnail_can_be.png
  docs/content_management/img/admin_panel_new_content_type.png
  docs/getting_started/img/first-steps-add-translation.png
  docs/getting_started/img/first-steps-assign-roles.png
  docs/getting_started/img/first-steps-create-content.png
  docs/getting_started/img/first-steps-create-ct.png
  docs/getting_started/img/first-steps-policy-limitations.png
  docs/getting_started/img/welcome_page.png
  docs/tutorials/beginner_tutorial/img/bike_tutorial_homepage_install_clean.png
  docs/tutorials/page_and_form_tutorial/img/enterprise_tut_empty_single_block.png
  docs/tutorials/page_and_form_tutorial/img/enterprise_tut_new_layout.png
  docs/users/img/password_expiry.png
Labels: Needs DOC review

#2041 IBX-6038: Added PHP API for cart merge
  docs/api/event_reference/cart_events.md
Labels: Ready for MERGE
