Repository ibexa/documentation-developer, pull requests merged in 2023-12, with the labels that each got.

#2224 Details basic auth VS BO
  docs/api/rest_api/rest_api_authentication.md
Labels: Ready for MERGE

#2203 CS-11412: Avoid special characters in config
  docs/administration/configuration/configuration.md
  docs/multisite/multisite_configuration.md
  docs/update_and_migration/migrate_to_ibexa_dxp/common_issues.md
Labels: Ready for MERGE

#2236 Updated doc changelog November
  docs/resources/new_in_doc.md
Labels: Ready for MERGE

#2234 Document events layer for Segmentation Service
  docs/api/event_reference/segmentation_events.md
  mkdocs.yml
Labels: Needs DOC review

#2237 PHP 8.0 is EOL now
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#2239 Fix solr config
  docs/search/solr_search_engine.md
Labels: Needs DEV review, Ready for MERGE

#2243 Added Duplicate taxonomy fields warning to TaxonomyEntryAssignment Field Type
  docs/content_management/field_types/field_type_reference/taxonomyentryassignmentfield.md
Labels: Ready for MERGE

#2245 IBX-4160: Add taxonomy view matchers to reference
  docs/templating/templates/view_matcher_reference.md
Labels: Needs DOC review

#2251 IBX-7187: Get content category Twig filter
  docs/templating/twig_function_reference/other_twig_filters.md
Labels: Needs DOC review

#2249 `ibexa_render` optional args' default values
  docs/templating/twig_function_reference/content_twig_functions.md
Labels: Ready for MERGE

#2253 IBX-3796: Document segment group protection
  docs/release_notes/ibexa_dxp_v4.2.md
Labels: Needs DOC review

#2255 Focus mode replaced with Distraction free mode.
  docs/content_management/img/distraction_free_mode.png
  docs/content_management/img/focus_mode.png
  docs/content_management/pages/page_builder_guide.md
  docs/content_management/rich_text/online_editor_guide.md
Labels: Needs DOC review

#2257 v3.3 - IBX-6744 Sort and design user section of the documentation
  docs/getting_started/first_steps.md
  docs/guide/content_rendering/layout/add_forgot_password.md
  docs/guide/content_rendering/layout/add_login_form.md
  docs/guide/content_rendering/twig_function_reference/url_twig_functions.md
  docs/guide/content_rendering/urls_and_routes.md
  docs/guide/forms/form_api/dataprocessors.md
  docs/guide/security.md
  docs/guide/security_checklist.md
  docs/guide/user_management/user_management.md
  docs/guide/users/delegate_function.md
  docs/guide/users/login_and_registration.md
  docs/guide/users/login_methods.md
  docs/guide/users/login_via_external_service.md
  docs/guide/users/oauth.md
  docs/guide/users/passwords.md
  docs/guide/users/token.md
  docs/guide/users/user_authentication.md
  docs/guide/users/user_management.md
  docs/guide/users/user_registration.md
  docs/guide/users/users.md
  docs/tutorials/platform_beginner/8_enable_account_registration.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
  docs/update_and_migration/from_4.2/update_from_4.2.md
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
  docs/update_and_migration/from_4.3/update_from_4.3_old_commerce.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#2254 v4.5 - IBX-6744 Sort and design user section of the documentation
  docs/commerce/storefront/configure_storefront.md
  docs/customer_management/create_user_registration_form.md
  docs/getting_started/first_steps.md
  docs/infrastructure_and_maintenance/security/development_security.md
  docs/infrastructure_and_maintenance/security/security_checklist.md
  docs/release_notes/ez_platform_v3.0.md
  docs/templating/layout/add_forgot_password_option.md
  docs/templating/layout/add_login_form.md
  docs/tutorials/beginner_tutorial/8_enable_account_registration.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
  docs/update_and_migration/from_4.2/update_from_4.2.md
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
  docs/update_and_migration/from_4.3/update_from_4.3_old_commerce.md
  docs/users/customer_groups.md
  docs/users/invitations.md
  docs/users/login_methods.md
  docs/users/passwords.md
  docs/users/user_authentication.md
  docs/users/user_management.md
  docs/users/user_registration.md
  docs/users/users.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#2250 master - IBX-6744 Sort and design user section of the documentation
  docs/commerce/storefront/configure_storefront.md
  docs/customer_management/create_user_registration_form.md
  docs/getting_started/first_steps.md
  docs/infrastructure_and_maintenance/security/development_security.md
  docs/infrastructure_and_maintenance/security/security_checklist.md
  docs/release_notes/ez_platform_v3.0.md
  docs/templating/layout/add_forgot_password_option.md
  docs/templating/layout/add_login_form.md
  docs/tutorials/beginner_tutorial/8_enable_account_registration.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
  docs/update_and_migration/from_4.2/update_from_4.2.md
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
  docs/update_and_migration/from_4.3/update_from_4.3_old_commerce.md
  docs/users/customer_groups.md
  docs/users/invitations.md
  docs/users/login_methods.md
  docs/users/passwords.md
  docs/users/user_authentication.md
  docs/users/user_management.md
  docs/users/user_management_guide.md
  docs/users/user_registration.md
  docs/users/users.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#2256 Fix line numbers
  docs/content_management/content_api/browsing_content.md
  docs/content_management/content_api/creating_content.md
  docs/search/search_api.md
Labels: Ready for MERGE

#2238 IBX-7276: New User / Field twig functions
  docs/templating/twig_function_reference/field_twig_functions.md
  docs/templating/twig_function_reference/other_twig_filters.md
  docs/templating/twig_function_reference/user_twig_functions.md
  mkdocs.yml
Labels: Needs DOC review
