Repository ibexa/documentation-developer, pull requests merged in 2023-10, with the labels that each got.

#2146 Updated new in documentation for September
  docs/resources/new_in_doc.md
Labels: Ready for MERGE

#2149 fixed dictionary-entry create/list
  docs/infrastructure_and_maintenance/cache/http_cache/fastly.md
Labels: Ready for MERGE

#2145 Expression language functions
  docs/content_management/data_migration/importing_data.md
Labels: Needs DOC review

#2153 IBX-6274: Added Name criterion for payment methods filtering
  docs/search/criteria_reference/payment_method_name_criterion.md
  docs/search/criteria_reference/payment_method_search_criteria.md
  mkdocs.yml
Labels: Ready for MERGE

#2155 Link to vhosts in install doc, rather than directly
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE

#2162 IBX-6270 merge down
  docs/personalization/api_reference/tracking_api.md
  docs/personalization/how_it_works.md
  docs/personalization/img/Diagram source/recommendation_overview.xml
  docs/personalization/img/recommendation_overview.png
  docs/personalization/integrate_recommendation_service.md
Labels: Needs DOC review

#2164 IBX-6270 merge down
  docs/guide/personalization/basic_integration.md
  docs/guide/personalization/developer_guide/tracking_api.md
  docs/guide/personalization/img/Diagram source/recommendation_overview.xml
  docs/guide/personalization/img/recommendation_overview.png
  docs/guide/personalization/personalization.md
Labels: Needs DOC review

#2168 "Public API" → "public PHP API": Doc 4.5+
  docs/administration/project_organization/architecture.md
  docs/api/php_api/php_api.md
  docs/content_management/content_relations.md
  docs/content_management/field_types/field_types.md
  docs/content_management/field_types/type_and_value.md
  docs/content_management/file_management/binary_and_media_download.md
  docs/content_management/file_management/file_url_handling.md
  docs/content_management/url_management/url_management.md
  docs/permissions/limitation_reference.md
  docs/release_notes/ez_platform_v3.0.md
  docs/release_notes/ez_platform_v3.0_deprecations.md
  docs/templating/render_content/render_content_in_php.md
Labels: Needs DOC review, Needs DEV review

#2158 Remove whitespaces from permission_overview
  docs/permissions/permission_overview.md
Labels: Ready for MERGE

#2144 IBX-6625: Document changed VAT category config
  docs/pim/enable_purchasing_products.md
  docs/pim/pim_configuration.md
Labels: Needs DOC review

#2177 IBX-6804 - VAT rate assignment in product type
  docs/pim/enable_purchasing_products.md
  docs/pim/img/catalog_vat_rates.png
Labels: Needs DOC review

#2178 IBX-6618: Updated variables
  README.md
  docs/api/field_types_reference/richtextfield.md
  docs/community_resources/report_follow_issues.md
  docs/getting_started/requirements.md
  docs/guide/cache/content_aware_cache.md
  docs/guide/reporting_issues.md
  docs/guide/security_checklist.md
  docs/releases/ibexa_dxp_v3.2.md
  docs/releases/ibexa_dxp_v3.3.md
  docs/releases/ibexa_dxp_v4.0.md
  docs/releases/ibexa_dxp_v4.0_deprecations.md
  docs/releases/ibexa_dxp_v4.2.md
  docs/releases/ibexa_dxp_v4.3.md
  docs/releases/ibexa_dxp_v4.4.md
  docs/releases/ibexa_dxp_v4.5.md
  docs/snippets/update/finish_the_update.md
  docs/updating/from_2.5/to_3.3.latest.md
  docs/updating/from_2.5/to_3.3.md
  docs/updating/from_3.3/to_4.0.md
  docs/updating/from_3.3/update_from_3.3.md
  docs/updating/from_4.0/to_4.1.md
  docs/updating/from_4.1/update_from_4.1.md
  docs/updating/from_4.2/update_from_4.2.md
  docs/updating/from_4.3/update_from_4.3.md
  docs/updating/from_4.3/update_from_4.3_new_commerce.md
  docs/updating/from_4.3/update_from_4.3_old_commerce.md
  docs/updating/from_4.4/update_from_4.4.md
  mkdocs.yml
Labels: Needs DOC review

#2173 IBX-4737 Files cannot be migrated when external DFS is configured
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#2099 Extend shipping example needs a region
  docs/commerce/shipping_management/extend_shipping.md
Labels: Needs DOC review, Needs DEV review

#2179 User product guide
  docs/users/diagram_source/user_management.drawio
  docs/users/img/user_management.png
  docs/users/img/users_invitation.png
  docs/users/img/users_section.png
  docs/users/user_management_guide.md
  mkdocs.yml
Labels: Needs DOC review

#2182 IBX-6441 - Add post visit and price drop
  docs/personalization/api_reference/tracking_api.md
  docs/personalization/integrate_recommendation_service.md
Labels: Needs DOC review

#2175 Enhance data migration doc (3.3+)
  code_samples/data_migration/examples/delete_role.yaml
  code_samples/data_migration/examples/update_role.yaml
  docs/content_management/data_migration/create_data_migration_step.md
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#2184 Enhance data migration doc (3.3)
  code_samples/data_migration/examples/create_blog_post_ct.yaml
  code_samples/data_migration/examples/create_role.yaml
  code_samples/data_migration/examples/delete_role.yaml
  code_samples/data_migration/examples/update_role.yaml
  docs/guide/data_migration/exporting_and_importing_data.md
Labels: Ready for MERGE

#2190 IBX-6851 Unify update folder structure between 4.5+ and 3.3
  docs/guide/security_checklist.md
  docs/index.md
  docs/release_notes/ez_platform_v3.0_deprecations.md
  docs/release_notes/ibexa_dxp_v3.3.md
  docs/update_and_migration/from_1.x_2.x/update_app_to_2.5.md
  docs/update_and_migration/from_1.x_2.x/update_db_to_2.5.md
  docs/update_and_migration/from_1.x_2.x/update_from_1.x_2.x.md
  docs/update_and_migration/from_2.5/adapt_code_to_v3.md
  docs/update_and_migration/from_2.5/to_3.2.md
  docs/update_and_migration/from_2.5/to_3.3.latest.md
  docs/update_and_migration/from_2.5/to_3.3.md
  docs/update_and_migration/from_2.5/update_code/1_update_templates.md
  docs/update_and_migration/from_2.5/update_code/2_update_configuration.md
  docs/update_and_migration/from_2.5/update_code/3_update_field_types.md
  docs/update_and_migration/from_2.5/update_code/4_update_signal_slots.md
  docs/update_and_migration/from_2.5/update_code/5_update_online_editor.md
  docs/update_and_migration/from_2.5/update_code/6_update_workflow.md
  docs/update_and_migration/from_2.5/update_code/7_update_extensions.md
  docs/update_and_migration/from_2.5/update_code/8_update_rest.md
  docs/update_and_migration/from_2.5/update_code/9_update_other.md
  docs/update_and_migration/from_2.5/update_from_2.5.md
  docs/update_and_migration/from_3.3/to_4.0.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.0/to_4.1.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
  docs/update_and_migration/from_4.2/update_from_4.2.md
  docs/update_and_migration/from_4.3/update_from_4.3.md
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
  docs/update_and_migration/from_4.3/update_from_4.3_old_commerce.md
  docs/update_and_migration/from_4.4/update_from_4.4.md
  docs/update_and_migration/img/diagram_source/folder_structure_v3.xml
  docs/update_and_migration/img/folder_structure_v3.png
  docs/update_and_migration/update_ibexa_dxp.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#2191 IBX-6851 Unify update folder structure between 4.5+ and 2.5
  docs/guide/extending/extending_online_editor.md
  docs/guide/security_checklist.md
  docs/index.md
  docs/release_notes/ez_platform_v3.0_deprecations.md
  docs/release_notes/ibexa_dxp_v3.3.md
  docs/update_and_migration/from_1.x_2.x/update_app_to_2.5.md
  docs/update_and_migration/from_1.x_2.x/update_db_to_2.5.md
  docs/update_and_migration/from_1.x_2.x/update_from_1.x_2.x.md
  docs/update_and_migration/from_2.5/adapt_code_to_v3.md
  docs/update_and_migration/from_2.5/to_3.2.md
  docs/update_and_migration/from_2.5/to_3.3.latest.md
  docs/update_and_migration/from_2.5/to_3.3.md
  docs/update_and_migration/from_2.5/update_code/1_update_templates.md
  docs/update_and_migration/from_2.5/update_code/2_update_configuration.md
  docs/update_and_migration/from_2.5/update_code/3_update_field_types.md
  docs/update_and_migration/from_2.5/update_code/4_update_signal_slots.md
  docs/update_and_migration/from_2.5/update_code/5_update_online_editor.md
  docs/update_and_migration/from_2.5/update_code/6_update_workflow.md
  docs/update_and_migration/from_2.5/update_code/7_update_extensions.md
  docs/update_and_migration/from_2.5/update_code/8_update_rest.md
  docs/update_and_migration/from_2.5/update_code/9_update_other.md
  docs/update_and_migration/from_2.5/update_from_2.5.md
  docs/update_and_migration/from_3.3/to_4.0.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.0/to_4.1.md
  docs/update_and_migration/from_4.1/update_from_4.1.md
  docs/update_and_migration/from_4.2/update_from_4.2.md
  docs/update_and_migration/from_4.3/update_from_4.3.md
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
  docs/update_and_migration/from_4.3/update_from_4.3_old_commerce.md
  docs/update_and_migration/from_4.4/update_from_4.4.md
  docs/update_and_migration/img/diagram_source/folder_structure_v3.xml
  docs/update_and_migration/img/folder_structure_v3.png
  docs/update_and_migration/update_ibexa_dxp.md
  mkdocs.yml
Labels: Ready for MERGE

#2194 IBX-6654 - Fix code in create form attrib tutorial
  code_samples/forms/custom_form_attribute/public/js/formbuilder-richtext-checkbox.js
  code_samples/forms/custom_form_attribute/templates/bundles/EzPlatformFormBuilderBundle/fields/config/form_fields.html.twig
  code_samples/forms/custom_form_attribute/templates/bundles/IbexaFormBuilderBundle/fields/config/form_fields.html.twig
Labels: Needs DOC review, QA approved

#2186 IBX-5874: Allow to attach context data to Cart and Cart Entries
  docs/commerce/cart/cart_api.md
Labels: Ready for MERGE

#1958 Changed PostgreSQL to 14
  docs/getting_started/requirements.md
Labels: Ready for MERGE
