Repository ibexa/documentation-developer, pull requests merged in 2023-08, with the labels that each got.

#2088 IBX-5900 Improvements to Commerce docs
  docs/commerce/cart/cart.md
  docs/commerce/storefront/extend_storefront.md
  docs/commerce/storefront/storefront.md
  docs/templating/layout/customize_storefront_layout.md
Labels: Needs DOC review

#2090 New in July
  docs/resources/new_in_doc.md
Labels: Needs DOC review

#1657 Clarify "Update from v3.3.x to v3.3.latest"
  docs/update_and_migration/from_3.3/update_from_3.3.md
Labels: Ready for MERGE, QA approved

#2093 Fix style in REST API usage
  docs/api/rest_api/rest_api_usage/rest_api_usage.md
  docs/api/rest_api/rest_api_usage/rest_requests.md
  docs/api/rest_api/rest_api_usage/rest_responses.md
  docs/api/rest_api/rest_api_usage/testing_rest_api.md
Labels: Ready for MERGE

#2095 Changed order of the storefront table to alphabetical
  docs/commerce/storefront/storefront.md
Labels: Ready for MERGE

#2094 3.3 requirements: sort PHP versions
  docs/getting_started/requirements.md
Labels: Needs DOC review

#2056 IBX-5948: 'Create Custom Name Schema strategy' page added in PIM
  code_samples/catalog/percent_name_schema_strategy/NameSchema/PercentNameSchemaStrategy.php
  code_samples/catalog/percent_name_schema_strategy/src/bundle/Resources/config/services/name_schema.yaml
  docs/pim/create_custom_name_schema_strategy.md
  mkdocs.yml
Labels: Needs DOC review

#2097 Fix services.yaml dir & indent
  code_samples/front/shop/payment/config/services.yaml
  code_samples/front/shop/shipping/config/packages/ibexa.yaml
  code_samples/front/shop/shipping/config/services.yaml
  docs/commerce/payment/extend_payment.md
  docs/commerce/shipping_management/extend_shipping.md
Labels: Ready for MERGE

#2091 IBX-6264: Clarify what hidden state is
  docs/content_management/locations.md
Labels: Ready for MERGE

#2092 IBX-6264: Clarify what hidden state is
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE

#2100 Fix in VAT rates configuration
  docs/pim/pim_configuration.md
Labels: Needs DOC review

#1970 3.3 install: PHP versions needing `composer update`
  docs/getting_started/install_ez_platform.md
Labels: Ready for MERGE

#2102 siteaccess_matching.md: Detail importance of matcher order
  docs/multisite/siteaccess/siteaccess_matching.md
Labels: Ready for MERGE

#2104 IBX-5997: Replaced twig helper for ibexa_format_price
  docs/templating/twig_function_reference/cart_twig_functions.md
  docs/templating/twig_function_reference/product_twig_functions.md
Labels: Ready for MERGE

#2106 Removed product version from Elasticsearch
  docs/search/search_engines.md
Labels: Needs DOC review

#2107 IBX-6219: Added payment and shipping create migrations
  code_samples/data_migration/examples/create_payment_method.yaml
  code_samples/data_migration/examples/create_shipping_method.yaml
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#2098 IBX-6009: Implement payment method filtering
  code_samples/front/shop/payment/src/bundle/Resources/config/services/payment_method.yaml
  code_samples/front/shop/payment/src/src/lib/PaymentMethod/Voter/NewPaymentMethodTypeVoter.php
  docs/commerce/payment/img/new_payment_method_type.png
  docs/commerce/payment/payment_method_filtering.md
  mkdocs.yml
Labels: Needs DOC review

#2108 Add timeouts info to security checklist
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Ready for MERGE

#1983 IBX-5706: DDEV usage
  docs/getting_started/install_with_ddev.md
  docs/infrastructure_and_maintenance/clustering/clustering_with_ddev.md
  docs/infrastructure_and_maintenance/clustering/ibexa_cloud_and_ddev.md
  mkdocs.yml
Labels: Ready for MERGE, QA approved

#2113 Add timeouts info to security checklist (#2108) - fix
  docs/guide/security_checklist.md
Labels: Ready for MERGE

#2080 Database update for v3.3.34 and v4.5.2
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.4/update_from_4.4.md
Labels: Ready for MERGE

#2087 IBX-4516 As a QA I want to introduce Node version 18 on CI
  docs/getting_started/requirements.md
Labels: Ready for MERGE

#2105 IBX-6055: Description of Quick Order in the dev documentation
  docs/api/php_api/php_api.md
  docs/commerce/cart/cart.md
  docs/commerce/cart/img/quick_order_add_order.png
  docs/commerce/cart/img/quick_order_list.png
  docs/commerce/cart/quick_order.md
  docs/commerce/storefront/storefront.md
  docs/templating/layout/customize_storefront_layout.md
  mkdocs.yml
Labels: Ready for MERGE

#2116 Tab switcher typo fix
  docs/administration/back_office/content_tab_switcher.md
Labels: Ready for MERGE

#2111 IBX-6181: Describe extension point for Checkout workflow
  code_samples/workflow/services/workflow.yaml
  code_samples/workflow/strategy/NewWorkflow.php
  code_samples/workflow/strategy/NewWorkflowConditionalStep.php
  docs/commerce/checkout/customize_checkout.md
Labels: Needs DOC review

#2119 IBX-6431: `IsVirtual` Search Criterion added
  docs/search/criteria_reference/isvirtual_criterion.md
  docs/search/criteria_reference/product_search_criteria.md
  mkdocs.yml
Labels: Needs DOC review

#2089 IBX-6241: Rewrite REST examples w/ other clients
  code_samples/api/rest_api/create_image.json.php
  code_samples/api/rest_api/create_image.xml.php
  code_samples/api/rest_api/load_content.php
  docs/api/rest_api/rest_api_usage/rest_requests.md
  docs/api/rest_api/rest_api_usage/testing_rest_api.md
Labels: Ready for MERGE
