Repository ibexa/documentation-developer, pull requests merged in 2024-12, with the labels that each got.

#2569 Moved GitHub token info to the tokens section
  docs/getting_started/install_ibexa_dxp.md
Labels: Needs DOC review

#2564 November 2024 changelog
  docs/ai_actions/ai_actions.md
  docs/ai_actions/ai_actions_guide.md
  docs/ai_actions/install_ai_actions.md
  docs/api/rest_api/rest_api_authentication.md
  docs/content_management/data_migration/data_migration_actions.md
  docs/content_management/pages/create_custom_page_block.md
  docs/infrastructure_and_maintenance/cache/http_cache/reverse_proxy.md
  docs/personalization/api_reference/recommendation_api.md
  docs/personalization/enable_personalization.md
  docs/personalization/integrate_recommendation_service.md
  docs/personalization/tracking_integration.md
  docs/personalization/tracking_with_ibexa-tracker.md
  docs/pim/product_api.md
  docs/resources/new_in_doc.md
  docs/search/criteria_reference/isbookmarked_criterion.md
  docs/search/criteria_reference/isuserenabled_criterion.md
  docs/update_and_migration/from_2.5/to_3.3.md
  docs/update_and_migration/from_3.3/to_4.0.md
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
Labels: Ready for MERGE

#2566 IBX-4064: Search adjustements
  docs/js/custom.js
Labels: Ready for MERGE

#2565 Improve and extend the security checklist
  docs/infrastructure_and_maintenance/security/security_checklist.md
Labels: Needs DOC review

#2571 3.3: Improve and extend the security checklist
  docs/guide/security_checklist.md
Labels: Ready for MERGE

#2578 code_samples_usage.php: Handle --8<-- syntax
  tools/code_samples/code_samples_usage.php
Labels: Needs DOC review

#2576 [v5] Moved from Criterion to CriterionInterface
  code_samples/search/elasticsearch/src/Query/Criterion/Elasticsearch/CameraManufacturerVisitor.php
  code_samples/search/solr/src/Query/Criterion/Solr/CameraManufacturerVisitor.php
Labels: Needs DOC review, Needs DEV review

#2500 Fix bazinga usage
  docs/administration/project_organization/project_organization.md
  docs/multisite/languages/back_office_translations.md
Labels: Needs DOC review

#2579 [v4.6.15] Added mention about removed Symfony packs
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.6/update_from_4.6.md
  mkdocs.yml
Labels: Ready for MERGE

#2582 Cast contentId and locationId command arguments to integer
  code_samples/api/public_php_api/src/Command/AddLocationToContentCommand.php
  code_samples/api/public_php_api/src/Command/BookmarkCommand.php
  code_samples/api/public_php_api/src/Command/BrowseLocationsCommand.php
  code_samples/api/public_php_api/src/Command/CreateContentCommand.php
  code_samples/api/public_php_api/src/Command/DeleteContentCommand.php
  code_samples/api/public_php_api/src/Command/FindComplexCommand.php
  code_samples/api/public_php_api/src/Command/FindInTrashCommand.php
  code_samples/api/public_php_api/src/Command/HideLocationCommand.php
  code_samples/api/public_php_api/src/Command/MoveContentCommand.php
  code_samples/api/public_php_api/src/Command/ObjectStateCommand.php
  code_samples/api/public_php_api/src/Command/SectionCommand.php
  code_samples/api/public_php_api/src/Command/SetMainLocationCommand.php
  code_samples/api/public_php_api/src/Command/TranslateContentCommand.php
  code_samples/api/public_php_api/src/Command/TrashContentCommand.php
  code_samples/api/public_php_api/src/Command/UpdateContentCommand.php
  code_samples/api/public_php_api/src/Command/ViewContentCommand.php
  code_samples/api/public_php_api/src/Command/WorkflowCommand.php
Labels: Ready for MERGE

#2586 Fixed broken link and included Extending AI in cards
  docs/ai_actions/ai_actions.md
  docs/ai_actions/extend_ai_actions.md
Labels: Needs DOC review
