Repository ibexa/documentation-developer, pull requests merged in 2024-01, with the labels that each got.

#2247 Specify SiteAccess for translations data migrations
  docs/content_management/data_migration/exporting_data.md
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#2260 Fix broken links
  docs/content_management/content_management_guide.md
  docs/getting_started/requirements.md
  docs/infrastructure_and_maintenance/clustering/clustering_with_aws_s3.md
  docs/personalization/api_reference/content_api.md
  docs/personalization/api_reference/tracking_api.md
  docs/resources/new_in_doc.md
  docs/search/search_engines/elastic_search/configure_elastic_search.md
  docs/search/search_engines/elastic_search/install_elastic_search.md
  docs/search/search_engines/legacy_search_engine/legacy_search_overview.md
  docs/search/sort_clause_reference/datetrashed_sort_clause.md
  docs/search/sort_clause_reference/userlogin_sort_clause.md
Labels: Ready for MERGE

#2261 Perso API: reworks price and currency definition
  docs/personalization/api_reference/content_api.md
Labels: Ready for MERGE

#2252 IBX-6702: BasePriceStatsAggregation and CustomPriceStatsAggregation described
  docs/search/aggregation_reference/aggregation_reference.md
  docs/search/aggregation_reference/basepricestats_aggregation.md
  docs/search/aggregation_reference/custompricestats_aggregation.md
  mkdocs.yml
Labels: Needs DOC review

#2265 Modified Perso diagram
  docs/guide/personalization/img/Diagram source/full_content_export.drawio
  docs/personalization/img/full_content_export.png
Labels: Ready for MERGE

#2264 Modified diagram in Perso
  docs/personalization/img/Diagram source/full_content_export.xml
  docs/personalization/img/full_content_export.png
Labels: Ready for MERGE

#2269 Added segment parameters
  docs/personalization/api_reference/recommendation_api.md
Labels: Ready for MERGE

#2267 Fix endpoint URL in perso tracking API
  docs/personalization/api_reference/tracking_api.md
Labels: Needs DEV review

#2271 Taxonomy subtree deletion and clean-up
  docs/content_management/taxonomy/taxonomy.md
  docs/update_and_migration/from_4.2/update_from_4.2.md
  docs/update_and_migration/from_4.4/update_from_4.4.md
Labels: Ready for MERGE

#2272 Add links between image variations pages
  docs/content_management/images/images.md
  docs/templating/image_variations.md
Labels: Needs DOC review

#2262 Sort aggregation reference
  docs/search/aggregation_reference/aggregation_reference.md
  mkdocs.yml
Labels: Ready for MERGE

#2181 Continue product migration doc (4.6)
  code_samples/data_migration/examples/create_attribute_group.yaml
  code_samples/data_migration/examples/create_product_asset.yaml
  code_samples/data_migration/examples/create_product_price.yaml
  code_samples/data_migration/examples/create_product_variant.yaml
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE

#2266 Mention the Composer repository change in 3.3 update/upgrade
  docs/update_and_migration/from_2.5/to_3.3.md
Labels: Ready for MERGE

#2274 IBX-7111: Add changes resulting from the introduction of Focus mode
  docs/administration/content_organization/object_states.md
  docs/content_management/img/content_management_locations.png
  docs/content_management/locations.md
  docs/customer_management/cp_page_builder.md
  docs/getting_started/first_steps.md
  docs/getting_started/img/first-steps-add-translation.png
  docs/multisite/site_factory/site_factory.md
  docs/tutorials/beginner_tutorial/2_create_the_content_model.md
  docs/tutorials/beginner_tutorial/4_display_single_content_item.md
  docs/tutorials/page_and_form_tutorial/1_get_a_starter_website.md
Labels: Needs DEV review
