Repository ibexa/documentation-developer, pull requests merged in 2024-10, with the labels that each got.

#2508 Update to 4.6.12
  mkdocs.yml
Labels: Needs DOC review

#2438 Code samples usage
  .github/workflows/build.yaml
  code_samples/api/product_catalog/src/Command/AttributeCommand.php
  code_samples/api/product_catalog/src/Command/ProductCommand.php
  docs/pim/price_api.md
  docs/pim/product_api.md
  tools/code_samples/code_samples_usage.php
  tools/code_samples/code_samples_usage_diff2html.php
Labels: Ready for MERGE

#2509 Update to 4.6.12: ibexa/core-search
  docs/update_and_migration/from_4.5/update_from_4.5.md
Labels: Ready for MERGE

#2515 IBX-8970 Improved personalization details.
  docs/personalization/enable_personalization.md
  docs/personalization/integrate_recommendation_service.md
  docs/personalization/tracking_integration.md
  docs/personalization/tracking_with_ibexa-tracker.md
Labels: Ready for MERGE

#2518 Update Ibexa Cloud during 3.3. update or 4.x migration
  docs/update_and_migration/from_3.3/to_4.0.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
Labels: Ready for MERGE

#2510 Drop old Commerce tables
  docs/update_and_migration/from_4.3/update_from_4.3_new_commerce.md
Labels: Ready for MERGE

#2511 Fix FormSubmissionServiceInterface::create usage
  code_samples/api/public_php_api/src/Command/FormSubmissionCommand.php
  phpstan-baseline.neon
Labels: Ready for MERGE

#2514 Enhance create page blocks doc
  docs/content_management/data_migration/data_migration_actions.md
  docs/content_management/pages/create_custom_page_block.md
Labels: Needs DEV review

#2522 IBX-9107 Added link to the min.js ibexa tracker file.
  docs/personalization/tracking_with_ibexa-tracker.md
Labels: Needs DOC review

#2520 Fix 3.2 to 3.3
  docs/update_and_migration/from_2.5/to_3.3.md
Labels: Ready for MERGE

#2519 Reorganize "Update and migration"
  docs/update_and_migration/from_2.5/to_3.3.latest.md
  docs/update_and_migration/from_2.5/to_3.3.md
  docs/update_and_migration/from_2.5/update_from_2.5.md
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.4/update_from_4.4.md
  docs/update_and_migration/from_4.5/update_from_4.5.md
  docs/update_and_migration/from_4.6/update_from_4.6.md
  mkdocs.yml
  plugins.yml
Labels: Ready for MERGE

#2521 Link Product API to criteria, sort clauses, and PHP API Ref
  docs/pim/product_api.md
Labels: Ready for MERGE

#2526 Added instructions on how to combine varnish with basic-auth
  docs/infrastructure_and_maintenance/cache/http_cache/reverse_proxy.md
Labels: Needs DOC review

#2523 IBX-9124: Dynamic attribute submodels described in Developer Documentation
  docs/personalization/api_reference/recommendation_api.md
Labels: Needs DOC review
