Repository ibexa/documentation-developer, pull requests merged in 2024-09, with the labels that each got.

#2482 Enh. cards title & description extract
  main.py
Labels: Ready for MERGE

#2483 Workflows: Document how to set which user group can review
  code_samples/workflow/custom_workflow/config/packages/workflows.yaml
  docs/content_management/workflow/add_custom_workflow_action.md
  docs/content_management/workflow/workflow.md
Labels: Ready for MERGE

#2397 IBX-8377: Fix OAuth server installation
  docs/users/oauth_server.md
Labels: Ready for MERGE

#2489 Update Ibexa Cloud conf when upgrading to 4.6.11+
  docs/update_and_migration/from_4.5/update_from_4.5.md
Labels: Ready for MERGE

#2497 Latest tag update: 4.6.10 -> 4.6.11
  mkdocs.yml
Labels: Needs DOC review

#2486 IBX-8858: Update Solr config between 4.5 and 4.6
  docs/update_and_migration/from_3.3/update_from_3.3.md
  docs/update_and_migration/from_4.5/update_from_4.5.md
Labels: Ready for MERGE

#2481 IBX-8855: Ensure DDEV's MySQL character set & collation
  docs/getting_started/install_with_ddev.md
Labels: Ready for MERGE

#2480 IBX-8855: Change ibexa_payment_token collation to utf8mb4_unicode_520_ci
  docs/update_and_migration/from_4.5/update_from_4.5.md
Labels: Needs DEV review

#2346 Perso REST: ezp -> ibexa
  docs/personalization/enable_personalization.md
Labels: Ready for MERGE

#2502 Update DDEV options
  docs/getting_started/install_with_ddev.md
Labels: Ready for MERGE

#2472 IBX-8792: Ibexa Engage - fixes
  docs/ibexa_engage/create_campaign.md
  docs/ibexa_engage/img/campaign_custom_tag.png
Labels: Needs DOC review

#2504 IBX-8844: Added metadata for Location
  docs/content_management/data_migration/importing_data.md
Labels: Ready for MERGE
